### ISSUE TITLE
segmentation violation on OnResourceUpdate

### ISSUE THREAD

**Issue by logici** [projectcalico/calico#6517] opened 2022-08-09 07:35 UTC
## Expected Behavior

I do not know what cause of this issuer. but it should be handled if it is necessary.
## Current Behavior

when I log the calico-node-xxx pod in my cluster, it tell me segmentation violation on OnResourceUpdate. But, I do not know what happen, and I do not know what operations I have done. Anyway, it should be handled, right?
```
CALICO_NETWORKING_BACKEND is vxlan - no need to run a BGP daemon
Calico node started successfully
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x164c5ae]

goroutine 190 [running]:
github.com/projectcalico/felix/calc.(*VXLANResolver).OnResourceUpdate(0xc0004f89c0, 0x2123160, 0xc00026b620, 0x1d33920, 0x0, 0xc000880cf3, 0x9, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/vxlan_resolver.go:185 +0x37e
github.com/projectcalico/felix/dispatcher.updateHandlers.DispatchToAll(0xc000010848, 0x1, 0x1, 0x2123160, 0xc00026b620, 0x1d33920, 0x0, 0xc000880cf3, 0x9, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:45 +0x8b
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdate(0xc000307940, 0x2123160, 0xc00026b620, 0x1d33920, 0x0, 0xc000880cf3, 0x9, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:102 +0x3a2
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdates(0xc000307940, 0xc000932410, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:80 +0x136
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).loop(0xc0004f8a80)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:150 +0x43d
created by github.com/projectcalico/felix/calc.(*AsyncCalcGraph).Start
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:237 +0xb3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x164c5ae]

goroutine 197 [running]:
github.com/projectcalico/felix/calc.(*VXLANResolver).OnResourceUpdate(0xc000146600, 0x2123160, 0xc00044a450, 0x1d33920, 0x0, 0xc0008cd373, 0x9, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/vxlan_resolver.go:185 +0x37e
github.com/projectcalico/felix/dispatcher.updateHandlers.DispatchToAll(0xc0005aa080, 0x1, 0x1, 0x2123160, 0xc00044a450, 0x1d33920, 0x0, 0xc0008cd373, 0x9, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:45 +0x8b
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdate(0xc0005c0200, 0x2123160, 0xc00044a450, 0x1d33920, 0x0, 0xc0008cd373, 0x9, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:102 +0x3a2
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdates(0xc0005c0200, 0xc0001487d0, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:80 +0x136
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).loop(0xc0001466c0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:150 +0x43d
created by github.com/projectcalico/felix/calc.(*AsyncCalcGraph).Start
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:237 +0xb3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x164c5ae]

goroutine 211 [running]:
github.com/projectcalico/felix/calc.(*VXLANResolver).OnResourceUpdate(0xc0004e0a20, 0x2123160, 0xc000747080, 0x1d33920, 0x0, 0xc000910a43, 0x9, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/vxlan_resolver.go:185 +0x37e
github.com/projectcalico/felix/dispatcher.updateHandlers.DispatchToAll(0xc000146160, 0x1, 0x1, 0x2123160, 0xc000747080, 0x1d33920, 0x0, 0xc000910a43, 0x9, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:45 +0x8b
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdate(0xc00000e3a0, 0x2123160, 0xc000747080, 0x1d33920, 0x0, 0xc000910a43, 0x9, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:102 +0x3a2
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdates(0xc00000e3a0, 0xc000944250, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:80 +0x136
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).loop(0xc0004e0ba0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:150 +0x43d
created by github.com/projectcalico/felix/calc.(*AsyncCalcGraph).Start
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:237 +0xb3
```
## Possible Solution

I have no idea.
## Steps to Reproduce (for bugs)

I am so sorry. I do not know what operations I have done.

## Your Environment

* Calico version: calico/node:v3.13.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): using microk8s:1.19/stable
* Operating System and version:  Ubuntu 20.04.1 LTS

**Comment by caseydavenport** [comment] 2022-08-26 15:54
Assigned to @coutinhop since it says "VXLAN" in the strack trace :laughing:

**Comment by coutinhop** [comment] 2022-09-01 19:41
@logici sorry for the delay.

I see you're using calico v3.13.2, that is pretty old, as we've just released v3.24.1... There have been numerous code changes since then and the issue is most probably fixed in a more recent calico version.

Could you try updating and see if that resolves it? Any specific reason to still be on v3.13?

**Comment by logici** [comment] 2022-09-02 01:51
Thank you for your answers. I am using this tool `microk8s` v1.19  to build my cluster. It takes the calico v3.13.2. I will try the new version depending on the situation.

**Comment by caseydavenport** [comment] 2022-09-02 15:45
Going to close this for now, but please open a new issue if you encounter this on a modern Calico version.

**Closed by caseydavenport** 2022-09-02 15:45 UTC
Labels: kind/support
