### ISSUE TITLE
Tigera Operator not adding nodeSelector to  calico-typha deployment pod spec

### ISSUE THREAD

**Issue by TechnicalMercenary** [projectcalico/calico#6099] opened 2022-05-14 19:27 UTC
## Expected Behavior

In the Installation 'default' I have set the controlPlaneNodeSelector and the controlPlaneTolerations 

```
  controlPlaneNodeSelector:
    example.com/role-id: devops-server
  controlPlaneTolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: devops-server
```

 I would have expected the deployment that was generated by the operator to have these values in its podSpec.  Unfortunately, only the Toleration appears.  The pod for the calico-kube-controllers does have both the nodeSelector and the Toleration.

## Current Behavior

The podSpec snippet from the calico-typha deployment

```
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-typha
      serviceAccountName: calico-typha
      terminationGracePeriodSeconds: 0
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: devops-server
```
## Possible Solution

I would have expected the nodeSelector I provided to be added to the list of deployment container nodeSelectors

## Context

I'm trying to get these auto-generated calico-typha pods to not be scheduled onto our really large and expensive nodes.

## Your Environment

* Calico (typha) operator 1.25.8
* Calico version: 3.22.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s 1.20
* Operating System and version: AWS Linux
* Link to your project (optional):

**Comment by TechnicalMercenary** [comment] 2022-05-14 21:50
Oh heck.  I think I created this ticket in the wrong project.  Would this be a Tigera issue ?

**Comment by lmm** [comment] 2022-05-17 16:27
Hey @TechnicalMercenary , yeah this issue might be better placed in the operator repo: https://github.com/tigera/operator

It looks like you're hitting this issue: https://github.com/tigera/operator/issues/1653
We are looking into filling in some of the operator config gaps which will include support for affinities/nodeSelectors for typha.

**Comment by caseydavenport** [comment] 2022-05-17 18:25
> Oh heck. I think I created this ticket in the wrong project. Would this be a Tigera issue ?

No worries, we look in both places :grin:  - but probably better placed in tigera/operator.

In this case though, I agree with @lmm this is a duplicate of https://github.com/tigera/operator/issues/1653. I believe @lmm is actually already looking into addressing this gap in the near future. 

I''m going to close this in favor of the linked existing issue, but agree this needs to be fixed.

**Closed by caseydavenport** 2022-05-17 18:25 UTC
Labels: kind/bug
