### ISSUE TITLE
tigera-operator chart Chart.yaml version mismatch with index.yaml

### ISSUE THREAD

**Issue by gclawes** [projectcalico/calico#4757] opened 2021-07-19 03:55 UTC
## Expected Behavior
The `version` field in `Chart.yaml` does not match the version published in index.yaml and associated tarballs.  This breaks certain helm-related tools such as [Praqma/helmsman](https://github.com/Praqma/helmsman)
```
$ curl -s https://calico-public.s3.amazonaws.com/charts/index.yaml | grep -E "version:|appVersion:|tgz" | head -3
    appVersion: v3.19.1
    - https://github.com/projectcalico/calico/releases/download/v3.19.1/tigera-operator-v3.19.1-2.tgz
    version: v3.19.1
$ ls
tigera-operator-v3.19.1-2.tgz
$ tar xvf tigera-operator-v3.19.1-2.tgz tigera-operator/Chart.yaml
tigera-operator/Chart.yaml
$ grep -E "version:|appVersion:" tigera-operator/Chart.yaml
appVersion: v3.19.1-e9e1e40ca
version: v3.19
```
```
$ helm search repo calico/tigera-operator --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
calico/tigera-operator  v3.19.1         v3.19.1         Installs the Tigera operator for Calico
calico/tigera-operator  v3.19.0         v3.19.0         Installs the Tigera operator for Calico
calico/tigera-operator  v3.18.4         v3.18.4         Installs the Tigera operator for Calico
calico/tigera-operator  v3.18.3         v3.18.3         Installs the Tigera operator for Calico
calico/tigera-operator  v3.18.2         v3.18.2         Installs the Tigera operator for Calico
calico/tigera-operator  v3.18.1         v3.18.1         Installs the Tigera operator for Calico
calico/tigera-operator  v3.18.0         v3.18.0         Installs the Tigera operator for Calico
```

## Current Behavior
When running `helmsman` with the following Desired State File (yaml):
`helmsman.yaml`
```
helmRepos:
  calico: https://calico-public.s3.amazonaws.com/charts

namespaces:
  tigera-operator: {}

apps:
  tigera-operator:
    name: tigera-operator
    chart: calico/tigera-operator
    version: v3.19.1
    namespace: tigera-operator
    enabled: true
    priority: 0
```
The following error is thrown:
```
$ helmsman -f helm/helmsman.yaml --target tigera-operator

 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.7.2
A Helm-Charts-as-Code tool.

2021-07-18 23:49:51 INFO: Parsed [[ helm/helmsman.yaml ]] successfully and found [ 1 ] apps
2021-07-18 23:49:51 INFO: Validating desired state definition
2021-07-18 23:49:51 INFO: Setting up kubectl
2021-07-18 23:49:51 INFO: Setting up helm
2021-07-18 23:49:55 INFO: Getting chart information
2021-07-18 23:49:55 ERROR: chart [ calico/tigera-operator ] with version [ v3.19.1 ] was found with a mismatched version: v3.19
2021-07-18 23:49:55 CRITICAL: chart validation failed
```

## Possible Solution
Adjust helm chart build/publishing process to match `Chart.yaml` `version` field with `index.yaml` version.

## Steps to Reproduce (for bugs)

1. Download helm + helmsman.
2. Add calico chart repo (preview URL): `helm repo add calico https://calico-public.s3.amazonaws.com/charts`
3. Install the `tigera-operator` chart using helmsman with the above helmsman.yaml file: `helmsman -f helmsman.yaml --apply`

## Context
Helm itself is able to tolerate the version mismatch, but helm-related tools fail. 

## Your Environment

* Calico version: `v3.19.1`
* Orchestrator version (e.g. kubernetes, mesos, rkt): `k3s v1.21.0+k3s1`
* Operating System and version: `5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project (optional):

**Comment by lmm** [comment] 2021-08-10 16:40
Pinging @lwr20 (who knows more about helm stuff than I do 😁 )

**Comment by lwr20** [comment] 2021-08-11 10:12
And @ozdanborne knows more about this than I do :)

**Comment by lwr20** [comment] 2021-08-11 10:16
So this part of the makefile should be setting the https://github.com/projectcalico/calico/blob/master/Makefile#L66-L88

**Comment by lwr20** [comment] 2021-11-22 09:22
@mgleung Any idea who did the v3.19.1 release?  I think that RELEASE_CHART was not set?

**Comment by mgleung** [comment] 2021-12-07 20:02
@lwr20 it looks like there was an issue with our release process as you've pointed out and we didn't build a release version of the chart as a part of the v3.19.1 release. My understanding is that we had some old scripts that were setting `RELEASE` (the old env variable that signified release values) as opposed to `RELEASE_CHART`. That being said, those scripts appear to have been corrected now so I'm hoping that this is only an issue with the `v3.19.1` chart.

**Comment by mgleung** [comment] 2021-12-15 19:47
@gclawes I just updated the `v3.19.1` release with the `tigera-operator-v3.19.1-3.tgz` chart which should be the same as the `v3.19.1-2` chart except for the changes to the versions. The helm index should be updated to point to that chart within the next 24 hours.

**Comment by mgleung** [comment] 2021-12-16 22:02
I just confirmed that the helm index has been updated properly. I will close this issue, but if anyone continues to run into this, feel free to comment and we'll reopen the issue.

**Closed by mgleung** 2021-12-16 22:02 UTC
Labels: kind/bug, likelihood/high, impact/high
