### ISSUE TITLE
calico BGP mode in Rancher

### ISSUE THREAD

**Issue by behnm** [projectcalico/calico#4338] opened 2021-01-23 09:34 UTC
I need to rancher rancher with calico in bgp mode, however, the cluster runs just in IPIP mode.

**Comment by song-jiang** [comment] 2021-01-26 17:10
My understanding is Rancher using Calico with BGP mode and IPIP. BGP for routes propagation and IPIP for inter-subents connections.

**Comment by behnm** [comment] 2021-01-26 17:42
Thanks for the answer. 
When we create a cluster in rancher, after choosing **"calico"** from the menu, calico run on all nodes of the cluster in IPIP mode. we can see this config on the nodes. All of them have **"tun0"** interface which means, calico works in IPIP mode not in BGP mode. If calico works in BGP mode, all the routes must be assigned to ETH0 not TUN0.
Please help me, How can I create a cluster in rancher in BGP mode by calico. 
Should I delete calico installed by rancher and install calico in BGP mode manually , or we can do better way to install calico in BGP mode?

**Comment by caseydavenport** [comment] 2021-01-26 17:47
Closing as a duplicate of https://github.com/projectcalico/calico/issues/4337

**Closed by caseydavenport** 2021-01-26 17:47 UTC
Labels: kind/support

**Comment by behnm** [comment] 2021-01-26 17:54
please dont close it. another one was duplicate (#4337 )

**Comment by caseydavenport** [comment] 2021-01-26 17:58
Please review the Calico documentation, and if you're still having trouble open another issue (just one). When you do, please make sure to follow the issue template that is provided, giving all of the steps you have taken, etc.
