### ISSUE TITLE
IP block isn't released to ipPool

### ISSUE THREAD

**Issue by madianjun** [projectcalico/calico#1578] opened 2018-01-04 13:49 UTC
## Expected Behavior
calico/node will free a block  when the IPs in the block are no longer in use, and the blackhole route corresponding to the block will also be removed.

## Current Behavior
block isn't freed to ip pool, other nodes haven't  assigned ip from the block which should be freed, and the blackhole route is not removed.

 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  v3.0.1
* Orchestrator version  kubernetes v1.8.4
* Operating System and version:  CentOS 7.2
* Link to your project (optional):

**Comment by fasaxc** [comment] 2018-01-04 15:13
@madianjun Please can you give us a step-by-step process to reproduce this.  What test were you trying?  What steps did you take to verify that the block wasn't in use?

**Comment by mdianjun** [comment] 2018-01-05 03:24
1. Init a k8s cluster(k8s-v1.8.4) master at IP 90 , kubeadm init  --pod-network-cidr 10.188.240.0/25 <and other arguments>
2. Start calico, calico version is 3.0.1.   set ipPool:    "ipv4_pools": ["10.188.240.0/25"]
     https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/
3. Join 4 k8s worker nodes(IPs are 91,92,93,94), and create 128 pods. 
Here is deployment yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos-ssh
spec:
  replicas: 128
  template:
    metadata:
      labels:
        app: centos-ssh
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: centos-ssh
        image: aipr.jd.local/library/centos-mdj:1.2
        command: ["sleep", "10000000"]
        ports:
        - name: ssh
          containerPort: 22
        - name: web
          containerPort: 80
```
Blackhole routes are as follows:
```
[root@BJYFB3-Druid-18290 install]# ansible -i inventory/inventory.cfg k8s-cluster -k -m shell -a "ip route |grep blackhole "
SSH password: 
172.19.182.92 | SUCCESS | rc=0 >>
blackhole 10.188.240.0/28  proto bird 
blackhole 10.188.240.48/28  proto bird 

172.19.182.94 | SUCCESS | rc=0 >>
blackhole 10.188.240.32/28  proto bird 
blackhole 10.188.240.64/28  proto bird 
blackhole 10.188.240.96/28  proto bird 

172.19.182.90 | FAILED | rc=1 >>
non-zero return code

172.19.182.93 | SUCCESS | rc=0 >>
blackhole 10.188.240.16/28  proto bird 
blackhole 10.188.240.112/28  proto bird 

172.19.182.91 | SUCCESS | rc=0 >>
blackhole 10.188.240.80/28  proto bird 
```
4. Delete all the pods. But blackhole routes are always present.
5. Create the pods on 92,93,94, not use 91 (use node label and nodeSelector). 
nodes:
```
[root@BJYFB3-Druid-18290 tool]# kubectl get nodes
NAME                                 STATUS    ROLES     AGE       VERSION   LABELS
bjyfb3-druid-18290.hadoop.jd.local   Ready     master    1d        v1.8.4    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=bjyfb3-druid-18290.hadoop.jd.local,node-role.kubernetes.io/master=
bjyfb3-druid-18291.hadoop.jd.local   Ready     <none>    1d        v1.8.4    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=bjyfb3-druid-18291.hadoop.jd.local
bjyfb3-druid-18292.hadoop.jd.local   Ready     <none>    1d        v1.8.4    app=centos,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=bjyfb3-druid-18292.hadoop.jd.local
bjyfb3-druid-18293.hadoop.jd.local   Ready     <none>    1d        v1.8.4    app=centos,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=bjyfb3-druid-18293.hadoop.jd.local
bjyfb3-druid-18294.hadoop.jd.local   Ready     <none>    1d        v1.8.4    app=centos,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=bjyfb3-druid-18294.hadoop.jd.local
```
yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos-ssh
spec:
  replicas: 128
  template:
    metadata:
      labels:
        app: centos-ssh
    spec:
      nodeSelector:
        app: centos
      terminationGracePeriodSeconds: 0
      containers:
      - name: centos-ssh
        image: aipr.jd.local/library/centos-mdj:1.2
        command: ["sleep", "10000000"]
        ports:
        - name: ssh
          containerPort: 22
        - name: web
          containerPort: 80
```
After create 128 pods, blackhole routes are the same with above: 
```
[root@BJYFB3-Druid-18290 install]# ansible -i inventory/inventory.cfg k8s-cluster -k -m shell -a "ip route |grep blackhole"
SSH password: 
172.19.182.94 | SUCCESS | rc=0 >>
blackhole 10.188.240.32/28  proto bird 
blackhole 10.188.240.64/28  proto bird 
blackhole 10.188.240.96/28  proto bird 

172.19.182.93 | SUCCESS | rc=0 >>
blackhole 10.188.240.16/28  proto bird 
blackhole 10.188.240.112/28  proto bird 

172.19.182.90 | FAILED | rc=1 >>
non-zero return code

172.19.182.92 | SUCCESS | rc=0 >>
blackhole 10.188.240.0/28  proto bird 
blackhole 10.188.240.48/28  proto bird 

172.19.182.91 | SUCCESS | rc=0 >>
blackhole 10.188.240.80/28  proto bird 
```
the "calixxxx" network interface count(kube-dns pod is at IP 91):
```
[root@BJYFB3-Druid-18290 install]# ansible -i inventory/inventory.cfg k8s-cluster -k -m shell -a "ip route |grep cali|wc -l"
SSH password: 
172.19.182.94 | SUCCESS | rc=0 >>
43

172.19.182.90 | SUCCESS | rc=0 >>
0

172.19.182.93 | SUCCESS | rc=0 >>
32

172.19.182.91 | SUCCESS | rc=0 >>   
0

172.19.182.92 | SUCCESS | rc=0 >>
32
```
pods on IP 92 : 
```
[root@BJYFB3-Druid-18290 install]# kubectl get pods -o wide  | grep 18292 | wc -l
35
[root@BJYFB3-Druid-18290 install]# kubectl get pods -o wide  | grep 18292
centos-ssh-8ddcb68d-2jwsj   1/1       Running             0          9m        10.188.240.49    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-2zpns   1/1       Running             0          9m        10.188.240.59    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-4dv4j   0/1       ContainerCreating   0          9m        <none>           bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-4nt8b   1/1       Running             0          9m        10.188.240.9     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-674l9   1/1       Running             0          9m        10.188.240.60    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-74s9p   1/1       Running             0          9m        10.188.240.15    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-7hklh   1/1       Running             0          9m        10.188.240.2     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-7pdwg   1/1       Running             0          9m        10.188.240.0     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-7rkfs   1/1       Running             0          9m        10.188.240.12    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-84slm   1/1       Running             0          9m        10.188.240.4     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-85fzq   1/1       Running             0          9m        10.188.240.61    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-9vlbv   1/1       Running             0          9m        10.188.240.6     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-bptbs   1/1       Running             0          9m        10.188.240.1     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-drvzz   1/1       Running             0          9m        10.188.240.48    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-fdcqn   1/1       Running             0          9m        10.188.240.54    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-fmh2l   1/1       Running             0          9m        10.188.240.50    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-fqthq   1/1       Running             0          9m        10.188.240.53    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-fxdkb   1/1       Running             0          9m        10.188.240.56    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-fxh7h   1/1       Running             0          9m        10.188.240.10    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-g7789   1/1       Running             0          9m        10.188.240.63    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-ggds6   0/1       ContainerCreating   0          9m        <none>           bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-gvd7v   1/1       Running             0          9m        10.188.240.51    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-hrfkp   1/1       Running             0          9m        10.188.240.52    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-jrkzk   1/1       Running             0          9m        10.188.240.13    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-kzncf   1/1       Running             0          9m        10.188.240.62    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-md48n   1/1       Running             0          9m        10.188.240.8     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-mmms6   1/1       Running             0          9m        10.188.240.58    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-nx5fw   1/1       Running             0          9m        10.188.240.5     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-pjx85   1/1       Running             0          9m        10.188.240.11    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-pscmp   1/1       Running             0          9m        10.188.240.55    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-q4s8q   0/1       ContainerCreating   0          9m        <none>           bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-q946j   1/1       Running             0          9m        10.188.240.14    bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-qbpbx   1/1       Running             0          9m        10.188.240.3     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-v854q   1/1       Running             0          9m        10.188.240.7     bjyfb3-druid-18292.hadoop.jd.local
centos-ssh-8ddcb68d-z8fkb   1/1       Running             0          9m        10.188.240.57    bjyfb3-druid-18292.hadoop.jd.local
```

There are 3 pods not assigned ip address,  expect behavior is that 91 should release it's block, and the block will be used by other 3 nodes(92,93,94).

**Comment by caseydavenport** [comment] 2018-01-08 16:24
@madianjun I've only skimmed so far, but you should note that if you have `ip-in-ip` enabled on your IP pool, then Calico will reserve an IP address from each node's first block to use on the IPIP tunnel.

This means that even if there are no pods running on that node, a block has been allocated to that node.

**Comment by mdianjun** [comment] 2018-01-15 09:10
@caseydavenport  I enabled IPIP。

**Comment by caseydavenport** [comment] 2018-01-17 18:32
@mdianjun reviewing the code again, I've realized that we don't actually release block affinities when the last IP address is removed from a block. However, the blocks for a host will be deleted when a Node is deleted.

This is done to minimize route churn in the network. What is your use case for wanting the block affinity to be deleted when the last IP is freed?

**Comment by caseydavenport** [comment] 2018-05-31 01:27
I'm going to close this since it's expected behavior. Let's open another issue if there is a use-case for changing this behavior.

**Closed by caseydavenport** 2018-05-31 01:27 UTC
Labels: priority/P3
