### ISSUE TITLE
 bird process is not running

### ISSUE THREAD

**Issue by WVenus** [projectcalico/calico#7527] opened 2023-04-04 08:48 UTC
Calico 3.23.3 version is installed, but the bird process is not running. The node's host route is normal. Calicoctl node status output shows that no IPv4 peers have been found.
## Expected Behavior
 The bird process is running normally, and the output of Calicoctl node status is normal.
![image](https://user-images.githubusercontent.com/39941928/229735130-57312c83-e266-4cea-9e95-9df60530c577.png)
![image](https://user-images.githubusercontent.com/39941928/229736111-338ed6fd-8da7-449d-ba92-278d8f7d387e.png)

## Current Behavior
1、 bird process is not running
![1680598044413](https://user-images.githubusercontent.com/39941928/229738898-4399d70f-24ca-4f01-a49a-d2cf310589e8.png)

2、the command "calicoctl node status" outputing "No IPv4 peers found"。
![1680598096502](https://user-images.githubusercontent.com/39941928/229739090-489a6a3f-7cee-4969-815b-269feb380356.png)

## Steps to Reproduce (for bugs)
1、I cannot provide a reproducible scenario.

## Context
1、I have enabled NetworkManager on the Linux host, and created a configuration file at /etc/NetworkManager/conf.d/calico.conf to prevent NetworkManager from interfering with the interface.

## Your Environment

* Calico version 
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by mgleung** [comment] 2023-04-04 16:22
Hey @WVenus , can you provide any other Calico config that you are using to set this cluster up and the logs from the `calico-node` pods? I'm not quite sure why bird might not be running in your cluster without some more details about the scenario.

**Comment by WVenus** [comment] 2023-04-06 09:46
@mgleung  Here is the configuration file for installing Calico, including thecalico-node log files and the IPPool configuration. The listenPort value in the BGPConfiguration section is 12020, but I'm not sure if this configuration has any impact because the system is not listening on the 12020 port.

[calico-3.23.2-ipv6-vxlan.txt](https://github.com/projectcalico/calico/files/11168827/calico-3.23.2-ipv6-vxlan.txt)
[calico-bgpport.txt](https://github.com/projectcalico/calico/files/11168830/calico-bgpport.txt)
[calico-node.txt](https://github.com/projectcalico/calico/files/11168831/calico-node.txt)

```yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv4-ippool
    resourceVersion: "108793"
    uid: b263cdf2-94b7-4066-abe9-667d4c60b525
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 197.166.0.0/16
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv6-ippool
    resourceVersion: "108796"
    uid: c2982278-47cc-4de4-95fd-6145ed9ec702
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: fdf3:8f2d:d955::/48
    ipipMode: Never
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "14608699"
```
```yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: FelixConfiguration
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default
    resourceVersion: "108800"
    uid: 825ef260-7b93-4813-879b-a0165e58780e
  spec:
    bpfLogLevel: ""
    floatingIPs: Disabled
    logSeverityScreen: Info
    reportingInterval: 0s
kind: FelixConfigurationList
metadata:
  resourceVersion: "14608608"
```

**Comment by WVenus** [comment] 2023-04-12 01:19
@mgleung Hello, is there a thought for this question?

**Comment by mgleung** [comment] 2023-04-18 16:52
@WVenus sorry for the delay, I just took a look at your logs and found that you've set up VXLAN for your default IPv4 pool. Is that intentional? We do not run bird when VXLAN is enabled so that might be why you're seeing this.

**Comment by WVenus** [comment] 2023-04-19 01:03
@mgleung  Can I understand that this is caused by the use of an overlay network?  
  Because we are using the vxlanMode set to Always

**Comment by mgleung** [comment] 2023-05-02 17:04
@WVenus , it is not necessarily that this is caused by an overlay networking, but that VXLAN in particular does not need BGP to function. Since you are running in VXLAN mode, BGP is not running or needed and that is why BIRD is not running and there are no BGP peers.

**Comment by mgleung** [comment] 2023-05-16 16:49
I'm closing this since I think the issue is resolved. If there are any more questions or concerns about this, please shout out and we can reopen this.

**Closed by mgleung** 2023-05-16 16:49 UTC
Labels: kind/support

**Comment by eliassal** [comment] 2024-10-22 12:22
Hi, me too, all of a sudden, I started getting

> no BGP backend process BIRD is not running

Yesterday, when I ran 
`calicoctl node status`

I got a table indicating

> IPv4 BGP status .....

with 2 lines

**Comment by ryanhashemi-tmx** [comment] 2025-02-27 05:21
In case someone is switching from Canal/Flannel VXLAN to Calico BGP, make sure you set `calico_backend: "vxlan"` to `calico_backend: "bird"` in calico-config configmap. This enables calico bird engine, otherwise you see the following error message in the calico-node logs

```
CALICO_NETWORKING_BACKEND is vxlan - no need to run a BGP daemon
```
