### ISSUE TITLE
Probe failing on pods post network error

### ISSUE THREAD

**Issue by tarun-asthana** [projectcalico/calico#6662] opened 2022-09-05 04:58 UTC
## Expected Behavior
Normally probes should not be failing for several pods at once.

## Current Behavior
Firstly, I can see these two odd logs in my syslog:

```
networkd-dispatcher[781]: WARNING:Unknown index 56 seen, reloading interface list
systemd-udevd[455717]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
```

Next, I see my probes getting failed for multiple pods like

```
Startup probe for "pod1:app" failed (failure): Get http://100.125.215.114:8081/ping: dial tcp 100.125.215.114:8081: connect: connection refused
```

Here are the full syslogs:
```
Aug 31 03:50:34 ip-10-50-117-248 systemd-networkd[630]: cali805c5f20419: Link UP Aug 31 03:50:34 ip-10-50-117-248 systemd-networkd[630]: cali805c5f20419: Gained carrier Aug 31 03:50:34 ip-10-50-117-248 networkd-dispatcher[781]: WARNING:Unknown index 56 seen, reloading interface list Aug 31 03:50:34 ip-10-50-117-248 systemd-udevd[455717]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable. Aug 31 03:50:34 ip-10-50-117-248 kubelet[455785]: 2022-08-31 03:50:34.635 [INFO][455785] k8s.go 391: Added Mac, interface name, and active container ID to endpoint ContainerID=pod1
Aug 31 03:50:34 ip-10-50-117-248 systemd-udevd[455717]: Using default interface naming scheme 'v245'. Aug 31 03:50:34 ip-10-50-117-248 kubelet[455785]: 2022-08-31 03:50:34.642 [INFO][455785] k8s.go 423: Wrote updated endpoint to datastore ContainerID="pod1" Namespace="ns1" Pod="pod1" WorkloadEndpoint="ip--10--50--117--248.ap--southeast--1.compute.internal-k8s-pod1-eth0" Aug 31 03:50:34 ip-10-50-117-248 kubelet[11767]: I0831 03:50:34.645890 11767 kubelet.go:1917] SyncLoop (UPDATE, "api"): "pod1_ns" Aug 31 03:50:34 ip-10-50-117-248 dockerd[11657]: time="2022-08-31T03:50:34.669269548Z" level=warning msg="Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap." Aug 31 03:50:34 ip-10-50-117-248 kubelet[11767]: I0831 03:50:34.715092 11767 kubelet.go:1955] SyncLoop (PLEG): "pod1_ns", event: &pleg.PodLifecycleEvent{Type:"ContainerStarted"} Aug 31 03:50:34 ip-10-50-117-248 containerd[11489]: time="2022-08-31T03:50:34.755702861Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/X/shim.sock" debug=false pid=455908 Aug 31 03:50:35 ip-10-50-117-248 kubelet[11767]: I0831 03:50:35.761946 11767 kubelet.go:1955] SyncLoop (PLEG): "pod1_ns", event: &pleg.PodLifecycleEvent{Type:"ContainerStarted"} Aug 31 03:50:36 ip-10-50-117-248 systemd-networkd[630]: cali805c5f20419: Gained IPv6LL Aug 31 03:50:37 ip-10-50-117-248 kubelet[11767]: I0831 03:50:37.284261 11767 prober.go:124] Startup probe for "pod1_ns:app" failed (failure): Get http://100.125.215.114:8081/ping: dial tcp 100.125.215.114:8081: connect: connection refused (repeated 9 times)
Aug 31 03:50:53 ip-10-50-117-248 kubelet[11767]: I0831 03:50:53.717708 11767 kubelet_getters.go:173] status for pod kube-proxy-ip-10-50-117-248.ap-southeast-1.compute.internal updated to {Running [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:41:54 +0000 UTC } {Ready True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:42:07 +0000 UTC } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:42:07 +0000 UTC } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:41:54 +0000 UTC }] 10.50.117.248 10.50.117.248 [{10.50.117.248}] 2022-08-31 02:41:54 +0000 UTC [] [{kube-proxy {nil &ContainerStateRunning{StartedAt:2022-08-31 02:42:07 +0000 UTC,} nil} {nil nil nil} true 0 k8s.gcr.io/kube-proxy:v1.18.9 docker-pullable://k8s.gcr.io/kube-proxy}] Burstable []}

Aug 31 03:54:00 ip-10-50-117-248 kubelet[11767]: I0831 03:54:00.065654 11767 prober.go:124] Liveness probe for "pod2_ns2" failed (failure): HTTP probe failed with statuscode: 500 Aug 31 03:54:00 ip-10-50-117-248 kubelet[11767]: I0831 03:54:00.142305 11767 prober.go:124] Liveness probe for "pod3_ns2" failed (failure): HTTP probe failed with statuscode: 500 Aug 31 03:54:03 ip-10-50-117-248 kubelet[11767]: I0831 03:54:03.995972 11767 prober.go:124] Readiness probe for "pod4_ns2" failed (failure): HTTP probe failed with statuscode: 500 Aug 31 03:54:04 ip-10-50-117-248 kubelet[11767]: I0831 03:54:04.552354 11767 prober.go:124] Readiness probe for "pod5_ns2" failed (failure): HTTP probe failed with statuscode: 500 Aug 31 03:54:05 ip-10-50-117-248 kubelet[11767]: I0831 03:54:05.159822 11767 prober.go:124] Readiness probe for "pod6_ns2" failed (failure): HTTP probe failed with statuscode: 500 Aug 31 03:54:05 ip-10-50-117-248 kubelet[11767]: I0831 03:54:05.403331 11767 prober.go:124] Liveness probe for "pod7_ns3" failed (failure): Aug 31 03:54:06 ip-10-50-117-248 kubelet[11767]: I0831 03:54:06.408768 11767 prober.go:124] Liveness probe for "pod8_ns4" failed (failure): HTTP probe failed with statuscode: 500 Aug 31 03:54:10 ip-10-50-117-248 kubelet[11767]: I0831 03:54:10.066091 11767 prober.go:124] Liveness probe for "pod9_ns5" failed (failure): HTTP probe failed with statuscode: 500
```

Not all the pods have their probe failing ^

```
Aug 31 03:58:09 ip-10-50-117-248 kubelet[11767]: I0831 03:58:09.959675 11767 kubelet.go:1926] SyncLoop (DELETE, "api"): "pod1_ns1" Aug 31 03:58:09 ip-10-50-117-248 kubelet[11767]: I0831 03:58:09.959996 11767 kuberuntime_container.go:648] Killing container "pod1" with 30second grace period
```

## Steps to Reproduce (for bugs)
This is a rare intermittent occurrence so can't reproduce it.

## Your Environment

* Calico version - v3.15.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 
* Operating System and version: Ubuntu 20.04

**Comment by caseydavenport** [comment] 2022-09-12 15:45
> Calico version - v3.15.3


This is a very old Calico version that we can't support any more, please upgrade to a modern version and see if this reproduces.

That said, there's nothing here to me that suggests this is a Calico issue. Sounds more like an application issue:

> dial tcp 100.125.215.114:8081: connect: connection refused

Suggests that your app isn't binding or accepting connections on its healthcheck port as the most likely issue. 

I'm going to close this for now since it's an unsupported version. If you upgrade and are still seeing issues please open another issue and we can discuss.

**Closed by caseydavenport** 2022-09-12 15:45 UTC
