### ISSUE TITLE
AWS EKS x509: cannot validate certificate for 10.100.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by miloup** [projectcalico/calico#7721] opened 2023-05-31 14:11 UTC
Hi,

I've tried to install Calico on an EKS cluster, but I keep getting `x509: cannot validate certificate for 10.100.0.1 because it doesn't contain any IP SANs` error, reason why I am reaching out for help :)

### Installation Steps

- Using Terraform, I deployed an EKS cluster v1.25 with an empty node-group (desired instances = 0)
- Once the cluster deployed, I deleted the VPC cni using `kubectl delete ds aws-node -n kube-system`
- I then applied the Calico manifest `kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico-vxlan.yaml`
- And ran the command `kubectl -n kube-system set env daemonset/calico-node FELIX_AWSSRCDSTCHECK=Disable`
- I updated my existing node-group's desired instance to 1.

### Issue

The calico-kube-controllers pod remains in "ContainerCreating" state and the `kubectl describe pod calico-kube-controllers-xxxxxx -n kube-system` returns the following:
```sh
Events:
  Type     Reason                  Age                    From               Message
  ----     ------                  ----                   ----               -------
  Normal   Scheduled               38m                    default-scheduler  Successfully assigned kube-system/calico-kube-controllers-xxxxxx-xxxx to ip-193-80-228-16.us-west-1.compute.internal
  Warning  FailedCreatePodSandBox  38m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": plugin type="calico" failed (add): error getting ClusterInformation: Get "https://10.100.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: cannot validate certificate for 10.100.0.1 because it doesn't contain any IP SANs
  Normal   SandboxChanged          3m46s (x162 over 38m)  kubelet            Pod sandbox changed, it will be killed and re-created.
```
### Note
My VPC does not have direct access to the internet. Egress traffic goes through an AWS Transit Gateway which is then routed to a proxy (in case this info helps).

Thanks

**Comment by caseydavenport** [comment] 2023-06-01 16:08
>  Get "https://10.100.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: cannot validate certificate for 10.100.0.1 because it doesn't contain any IP SANs

This is suggesting that your API server is presenting Calico with a certificate that doesn't include an IP address subject names in order to verify that Calico is talking to the correct server.

**Comment by miloup** [comment] 2023-06-02 07:41
Ok. But how to fix it?

**Comment by caseydavenport** [comment] 2023-06-02 15:29
You need to provide a certificate to your API server that includes its various IP addresses / domain names so that clients can verify it correctly.

**Comment by mazdakn** [comment] 2023-07-25 17:12
Closing since it seems the issue is clarified. Feel free to re-open think otherwise.

**Closed by mazdakn** 2023-07-25 17:12 UTC
Labels: kind/support
