### ISSUE TITLE
how to modify the advised subenet xxx.xxx.xxx.xxx/26 to xxx.xxx.xxx.xxx/28 for each node.

### ISSUE THREAD

**Issue by hzfeng87** [projectcalico/calico#1568] opened 2017-12-28 04:50 UTC
I  have 2048 container IP addresses in total, 100 calico node. But the TOR requires the minimal subnet xxx.xxx.xxx.xxx/28 from each node.  Some node can only get one container IP, unfortunately the IP subnet  is less then  xxx.xxx.xxx.xxx/28, so it is droped.

## Expected Behavior
I want to modify the advised subenet xxx.xxx.xxx.xxx/26 to xxx.xxx.xxx.xxx/28 for each node.
emergency ！！！！！！

**Comment by fasaxc** [comment] 2018-01-02 14:25
@hzfeng87 this is not a feature that Calico currently offers.  It would require a code change.  If you are interested in contributing the feature, or sponsoring it then please reach out on our calicousers slack.

**Comment by hzfeng87** [comment] 2018-01-03 04:06
@fasaxc  I had to modify it to use it in our environment. Could you please give me some suggestions about where to change if I have to  change the source codes.
Thanks a lot for your kind suggestions.

**Comment by mdianjun** [comment] 2018-01-04 10:12
@hzfeng87    The code is in libcalico-go/lib/ipam/ipam_block.go, as follows:
```
const (
	blockSize = 64   // change to 16
)

type ipVersion struct {
	Number            int
	TotalBits         int
	BlockPrefixLength int
	BlockPrefixMask   net.IPMask
}

var ipv4 ipVersion = ipVersion{
	Number:            4,
	TotalBits:         32,
	BlockPrefixLength: 26,  //change to 28
	BlockPrefixMask:   net.CIDRMask(26, 32),   // and here
}
```

**Comment by ozdanborne** [comment] 2018-03-09 00:34
Closing this issue as a duplicate of the feature request for "configurable block sizes" here: https://github.com/projectcalico/libcalico-go/issues/761

**Closed by ozdanborne** 2018-03-09 00:34 UTC
Labels: kind/support
