### ISSUE TITLE
Documentation and manifest mismatch

### ISSUE THREAD

**Issue by aceeric** [projectcalico/calico#6729] opened 2022-09-17 01:04 UTC
Regarding this page: https://projectcalico.docs.tigera.io/reference/installation/api

It says, regarding the `APIServer`: "At most one instance of this resource is supported. It must be named “tigera-secure”."

However on this page: https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises

Step 2 says to get https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml

It's a little vague, but then it says "If you wish to customize the Calico install, customize the downloaded custom-resources.yaml manifest locally."

The `custom-resources.yaml` has:
```
# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
```
Notice the `APIServer` name is at variance with the reference guidance. So either the manifest is wrong, or the instructions are wrong or  (this would be odd) the instructions are right and you want to make people patch the manifest...

Thanks.

**Comment by Josh-Tigera** [comment] 2022-09-20 16:12
Duplicate of #6730

**Comment by Josh-Tigera** [comment] 2022-09-20 16:27
Upon closer inspection this isn't actually a duplicate.

**Comment by Josh-Tigera** [comment] 2022-09-20 16:40
This looks like a documentation bug. Looking at the code it seems that `tigera-secure` is what the `APIServer` used to be called, and when we transitioned to instead naming it `default` we simply forgot to update this reference doc you've linked.

**Comment by caseydavenport** [comment] 2022-09-20 17:34
This should fix it: https://github.com/tigera/operator/pull/2184

**Closed** 2022-09-20 21:15 UTC
Labels: area/documentation, kind/bug, likelihood/high, impact/low
