### ISSUE TITLE
Add clickable anchor links to headings

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#452] opened 2017-01-18 09:19 UTC
It's very useful for referring people to particular FAQ entries if there's a way to link to a particular heading.

I've seen a lot of sites do that by having a feint link icon next to each heading, which is a link pointing to the heading's anchor.

**Comment by caseydavenport** [comment] 2017-08-07 23:22
Duplicate of #300

**Closed by caseydavenport** 2017-08-07 23:22 UTC
Labels: area/docs/ux, priority/P3
