### ISSUE TITLE
Listen-only UDP services drop all but first incoming datagram from a given source (address, port)

### ISSUE THREAD

**Issue by calder** [projectcalico/calico#2113] opened 2018-08-10 23:26 UTC
UDP services drop all but the first datagram from each source (address, port) unless the service sends a response datagram to complete the connection from conntrack's perspective.

## Expected Behavior

UDP services should support listen-only services that purely receive datagrams and never reply.

## Current Behavior

Instead, only the first datagram to a non-replying service actually makes it to the service's pods. All subsequent datagrams from a given source (address, port) are dropped as long as that source continues sending datagrams.

**This also makes bidirectional UDP services brittle to loss of the first reply packet.**

## Root cause

kube-proxy applies the masquerade mark in the `nat` table, but the Linux kernel only consults the `nat` table for the first UDP datagram it receives from a given source (address, port). This means all subsequent packets skip the `nat:KUBE-MARK-MASQ:rule:1` rule which applies the `0x4000` mark to incoming packets. This in turn prevents the packet from matching the `filter:KUBE-FORWARD:rule:1` which would normally accept the packet.

#### :heavy_check_mark: Sample packet 1 (routed properly)
```sh
# Identical
TRACE: raw:PREROUTING:policy:3 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:PREROUTING:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:cali-PREROUTING:rule:4 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:cali-from-host-endpoint:return:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:cali-PREROUTING:return:6 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:PREROUTING:policy:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9

# Packet 1 only - packet 2 skips NAT table entirely
TRACE: nat:PREROUTING:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:cali-PREROUTING:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:cali-fip-dnat:return:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:cali-PREROUTING:return:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:PREROUTING:rule:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:KUBE-SERVICES:rule:16 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:KUBE-FW-CA3IT7M5HHKE3FKJ:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:KUBE-MARK-MASQ:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: nat:KUBE-MARK-MASQ:return:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:KUBE-FW-CA3IT7M5HHKE3FKJ:rule:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:KUBE-SVC-CA3IT7M5HHKE3FKJ:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:KUBE-SEP-R2YNHF6CDRD4AQYP:rule:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000

# Identical except MARK
TRACE: mangle:FORWARD:policy:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:cali-FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:cali-FORWARD:rule:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:cali-from-hep-forward:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:cali-FORWARD:rule:5 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:cali-to-hep-forward:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:cali-FORWARD:return:7 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: filter:FORWARD:rule:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000

# Packet 1 only
TRACE: filter:KUBE-FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: mangle:POSTROUTING:policy:1 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:POSTROUTING:rule:1 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:cali-POSTROUTING:rule:1 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:cali-fip-snat:return:1 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:cali-POSTROUTING:rule:2 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:cali-nat-outgoing:return:2 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:cali-POSTROUTING:return:4 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:POSTROUTING:rule:2 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
TRACE: nat:KUBE-POSTROUTING:rule:1 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9 MARK=0x4000
```

#### :x: Sample packet 2 (dropped)
```sh
# Identical
TRACE: raw:PREROUTING:policy:3 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:PREROUTING:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:cali-PREROUTING:rule:4 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:cali-from-host-endpoint:return:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:cali-PREROUTING:return:6 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: mangle:PREROUTING:policy:2 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9

# NAT table skipped, MARK never applied.













# Identical except MARK
TRACE: mangle:FORWARD:policy:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:cali-FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:cali-FORWARD:rule:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:cali-from-hep-forward:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:cali-FORWARD:rule:5 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:cali-to-hep-forward:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:cali-FORWARD:return:7 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:FORWARD:rule:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9

# Packet 2 only
TRACE: filter:KUBE-FORWARD:return:4 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:FORWARD:rule:3 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:DOCKER-USER:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:FORWARD:rule:4 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:DOCKER-ISOLATION-STAGE-1:return:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
TRACE: filter:FORWARD:policy:9 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=29 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=41659 DPT=<DEST_PORT> LEN=9
```

#### :heavy_check_mark: Sample packet 3 after server has sent a response packet (routed properly)
```sh
# Identical
TRACE: raw:PREROUTING:policy:3 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: mangle:PREROUTING:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10

# Packet 3 only
TRACE: mangle:cali-PREROUTING:rule:1 IN=eno1 OUT= MAC=<MAC> SRC=<SOURCE_IP> DST=<SERVICE_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=60 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: mangle:FORWARD:policy:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:cali-FORWARD:rule:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:cali-FORWARD:rule:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:cali-from-hep-forward:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:cali-FORWARD:rule:5 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:cali-to-hep-forward:return:1 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:cali-FORWARD:return:7 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:FORWARD:rule:2 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: filter:KUBE-FORWARD:rule:3 IN=eno1 OUT=tunl0 MAC=<MAC> SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
TRACE: mangle:POSTROUTING:policy:1 IN= OUT=tunl0 SRC=<SOURCE_IP> DST=<POD_IP> LEN=30 TOS=0x00 PREC=0x00 TTL=59 ID=<ID> DF PROTO=UDP SPT=43391 DPT=<DEST_PORT> LEN=10
```

## Possible Solution

I don't know enough about iptables or Calico to recommend a solution. If it's possible to apply the mark in the `mangle` table instead of the `nat` table though, that should work.

## Steps to Reproduce (for bugs)

1. Create a pod with UDP port 1234 open.
2. Create a service that exposes UDP port 1234 on that pod.
3. Run `nc -lup 1234` on the pod.
4. Run `nc -u $SERVICE_EXTERNAL_IP 1234` from outside the cluster (this behavior does **not** reproduce on cluster nodes).
5. Type `1<ENTER>2<ENTER>`. You should see `1` but not `2` appear on the pod's console.
6. Type `phony reply<ENTER>` into the pod's console.
7. Type `3<ENTER>4<ENTER>` into the client's console. You should see both `3` and `4` appear on the pod's console now that the kernel's DNAT considers the connection established.

Steps 5-7 must be executed in relatively quick succession, since the kernel waits ~30 seconds for a reply before dropping the pending connection from its DNAT state.

## Context

I want to deploy a listen only UDP service to Kubernetes.

## Your Environment

* **Calico:** typha:v0.7.2, node:v3.1.1
* **MetalLB:** v0.6.2
* **Kubernetes:** v0.10.4
* **OS:** Ubuntu 16.04.4
* **Kernel:** Linux 4.4.0-108-generic

**Comment by calder** [comment] 2018-08-13 19:44
`KUBE-MARK-MASQ` is a kube-proxy chain, not a Calico one. This bug may belong on the Kubernetes project instead...

**Comment by thockin** [comment] 2018-08-14 15:49
I would say this is a general issue for Kubernetes (Note: I have not tried to reproduce or analyze it).

I don't understand the remark about mangle table?

**Comment by calder** [comment] 2018-08-15 12:58
@thockin: I think my `mangle` table suggestion is no good. The mark is specifically the "this packet is being masqueraded" mark (right?), so applying it in the `mangle` table would completely change its meaning.

**Comment by calder** [comment] 2018-08-15 13:01
I've worked around this for now by setting the default `filter.FORWARD` policy to `ACCEPT`, but this isn't a good long-term solution.

```sh
iptables -P FORWARD ACCEPT
```

**Comment by edwarnicke** [comment] 2018-11-28 02:51
@thockin Has any progress been made on this on the Kubernetes side?
Was an issue opened against Kubernetes?

**Comment by skbly7** [comment] 2019-01-17 09:05
We have hit the same. Is there any update?

**Comment by skbly7** [comment] 2019-01-17 21:19
Relevant issue from k8s side: https://github.com/kubernetes/kubernetes/issues/39823

**Comment by caseydavenport** [comment] 2019-03-31 00:03
Closing for now, since this looks like a kube-proxy issue tracked here: https://github.com/kubernetes/kubernetes/issues/72511

**Closed by caseydavenport** 2019-03-31 00:03 UTC
Labels: kind/support
