### ISSUE TITLE
: Failed to resync with dataplane error=exit status 1 family="inet"

### ISSUE THREAD

**Issue by 13567436138** [projectcalico/calico#9310] opened 2024-10-05 08:01 UTC
## Current Behavior

```
2024-10-05 07:57:09.904 [WARNING][6012] felix/ipsets.go 319: Failed to resync with dataplane error=exit status 1 family="inet"
2024-10-05 07:57:10.034 [INFO][6012] felix/ipsets.go 309: Retrying after an ipsets update failure... family="inet"
2024-10-05 07:57:10.041 [ERROR][6012] felix/ipsets.go 569: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.11: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
2024-10-05 07:57:10.041 [WARNING][6012] felix/ipsets.go 319: Failed to resync with dataplane error=exit status 1 family="inet"
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.26.4
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt):k8s1.30.1
* Operating System and version:ubuntu2404
* Link to your project (optional):

**Comment by caseydavenport** [comment] 2024-10-22 16:21
Looks like a duplicate of this one: https://github.com/projectcalico/calico/issues/8372

Please upgrade Calico and report back if it persists.

**Closed by caseydavenport** 2024-10-22 16:21 UTC
