### ISSUE TITLE
calico v3.21 fails k8s pod readiness probe

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [projectcalico/calico#5089] opened 2021-11-16 02:30 UTC
## Expected Behavior
The below test in kubernetes should pass when k8s cluster has calico as the network addon.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/hostport.go#L53

## Current Behavior
The test is failing with the below error when we use calico v3.21.
This is passing with **v3.20.**
```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Normal   Pulled     3m25s                  kubelet  Container image "k8s.gcr.io/e2e-test-images/agnhost:2.33" already present on machine
  Normal   Created    3m25s                  kubelet  Created container agnhost
  Normal   Started    3m25s                  kubelet  Started container agnhost
  Warning  Unhealthy  3m21s (x2 over 3m22s)  kubelet  Readiness probe failed: Get "http://172.20.220.169:8080/hostname": dial tcp 172.20.220.169:8080: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  3m16s (x2 over 3m23s)  kubelet  Readiness probe failed: Get "http://172.20.220.169:8080/hostname": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  29s (x18 over 3m7s)    kubelet  Readiness probe failed: Get "http://172.20.220.169:8080/hostname": dial tcp 172.20.220.169:8080: connect: invalid argument
```

## Steps to Reproduce (for bugs)
1. Setup a k8s cluster using calico manifest for version v3,21.
2. git clone https://github.com/kubernetes/kubernetes
3. cd kubernetes
4.  make WHAT="test/e2e/e2e.test"
5. ./_output/bin/e2e.test -ginkgo.focus="validates\ that\ there\ is\ no\ conflict\ between\ pods\ with"

Examples of failing live links:
1. https://k8s-testgrid.appspot.com/sig-node-ppc64le#conformance
2. https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1460393839087849472
## Context
Failing the k8s conformance runs.

## Your Environment

* Calico version v3.21

* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
[root@conf-fail-single-1636681519-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.4.350+de52812264b60d", GitCommit:"de52812264b60d57f6adb4c6965b8d8bd41418b9", GitTreeState:"clean", BuildDate:"2021-11-11T23:15:49Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.4.350+de52812264b60d", GitCommit:"de52812264b60d57f6adb4c6965b8d8bd41418b9", GitTreeState:"clean", BuildDate:"2021-11-11T23:15:49Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/ppc64le"}
[root@conf-fail-single-1636681519-master ~]#
```
* Operating System and version:
```
[root@conf-fail-single-1636681519-master ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
[root@conf-fail-single-1636681519-master ~]#
```

**Comment by Rajalakshmi-Girish** [comment] 2021-11-16 03:21
[calico-controller.log](https://github.com/projectcalico/calico/files/7543099/calico-controller.log)
[calico-node.log](https://github.com/projectcalico/calico/files/7543101/calico-node.log)

**Comment by Rajalakshmi-Girish** [comment] 2021-11-16 03:23
@mkumatag ^^

**Comment by cdtomkins** [comment] 2021-11-18 09:38
If I understand correctly, this is resolved in v3.21.1, see https://github.com/projectcalico/libcalico-go/pull/1544

**Comment by mkumatag** [comment] 2021-11-19 01:40
> If I understand correctly, this will be resolved in v3.21.1, see https://github.com/projectcalico/libcalico-go/pull/1544

When is this releasing?
Is there a way to test this before releasing this?

**Comment by cdtomkins** [comment] 2021-11-22 12:45
v3.21.1 is intended to release very soon.
In the meantime, I have confirmed that this specific test is passing in our overnight runs (and it was failing before) so we can be confident that it is fixed.
We also have hash releases, which are releases that are as close as possible to the release version. The latest hash release for this version can be found at https://2021-11-21-v3-21-cutrufello.docs.eng.tigera.net/ - you can install it as usual to validate the fixes yourself if you like.

**Comment by lwr20** [comment] 2021-11-30 17:24
v3.21.1 shipped on the 23rd November.
https://docs.projectcalico.org/release-notes/

**Closed by lwr20** 2021-11-30 17:24 UTC
