### ISSUE TITLE
Service conformance test failed: "should be rejected when no endpoints exist" 

### ISSUE THREAD

**Issue by anfernee** [projectcalico/calico#3650] opened 2020-06-11 23:53 UTC
## Expected Behavior
Service Conformance tests passed.

## Current Behavior
The following test failed on calico: 
https://github.com/kubernetes/kubernetes/blob/v1.18.3/test/e2e/network/service.go#L2582 

The root cause is cali-FORWARD got all the packets then the rules in KUBE-SERVICES don't have a chance to be executed. 

An example of iptables rules are like the following: 
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  156 97519 cali-FORWARD  all  --  any    any     anywhere             anywhere             /* cali:wUHhoiAYhphO9Mso */
    0     0 KUBE-FORWARD  all  --  any    any     anywhere             anywhere             /* kubernetes forwarding rules */
    0     0 KUBE-SERVICES  all  --  any    any     anywhere             anywhere             ctstate NEW /* kubernetes service portals */

Chain KUBE-SERVICES (3 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 REJECT     tcp  --  any    any     anywhere             10.96.232.205        /* default/noep:80-8080 has no endpoints */ tcp dpt:http reject-with icmp-port-unreachable
```

## Steps to Reproduce (for bugs)
1. Run conformance test 

```
 _output/bin/e2e.test --provider=<your_provider>  --ginkgo.focus="Services should be rejected" --kubeconfig $KUBECONFIG
```

## Your Environment
* Calico version: 3.8.8
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.16
* Operating System and version:`Linux cluster-1-6c98ff9d7b-8h98z 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by caseydavenport** [comment] 2020-06-17 16:34
Thanks for the issue - I'm going to close it as a duplicate of https://github.com/projectcalico/calico/issues/3548

**Closed by caseydavenport** 2020-06-17 16:34 UTC
