### ISSUE TITLE
Approach to alert when IPPool is going to run out of IP

### ISSUE THREAD

**Issue by zionwu** [projectcalico/calico#4202] opened 2020-11-23 04:00 UTC
My k8s cluster is using Calico v3.6.5. It uses multiple IP Pools and each IP Pool is allocated to a rack.
If the IP Pool is running out of IP, the pod belongs to the rack will be `ContainerCreating` state.
I wonder if there is an approach to alert when an IPPool is going to run out of IP?

**Comment by mgleung** [comment] 2020-11-24 17:16
Hi @zionwu, unfortunately the only current method of checking IP Pool allocation is to run `calicoctl ipam show` and inspect the utilization. We don't have anything that sets up alerts currently though it has been discussed before. What kind of workflow are you thinking about for this? Also, any PRs to accomplish any parts of this would also be welcome.

**Comment by zionwu** [comment] 2020-11-25 01:39
Hi @mgleung , thank you for the reply.

There are two approaches I can come up with. The first approach is to export the ipam utilization as a metric so we can use Prometheus to collect it and alter when utilization is high. Another approach is calico-kube-controller would emit a k8s event if the utilization is over the configured threshold. 
What do you think?

**Comment by caseydavenport** [comment] 2020-11-25 18:20
I believe that this is a duplicate of this existing issue: https://github.com/projectcalico/calico/issues/2715

**Closed by caseydavenport** 2020-11-25 18:20 UTC
Labels: kind/support
