### ISSUE TITLE
Is it possible to replcae amazon-k8s-vpc-cni with calico in a running production cluster?

### ISSUE THREAD

**Issue by bjethwan** [projectcalico/calico#3512] opened 2020-05-06 05:49 UTC
I see this nice presentation from Tigera around using Calico on Amazon EKS clusters.
https://www.youtube.com/watch?v=7LRtytR6ZbA

But I couldn't find official documentation around using calico for packet routing in Amazon EKS cluster. Except for a few mentions in blogs such as below.

https://medium.com/@jwenz723/amazon-vpc-cni-vs-calico-cni-vs-weave-net-cni-on-eks-b0ad8102e849

https://aws.amazon.com/blogs/opensource/networking-foundation-eks-aws-cni-calico/

Is replacing CNI as simple as replacing the daemonset on a k8s cluster? Would the VPC IPs go back to the free IP pool?

**Comment by tmjd** [comment] 2020-05-12 03:51
I do not believe there is any non-disruptive way to switch from the aws cni plugin to calico on a running cluster.
1st, I think there would be the problem that the pod cidr would need to change because with aws cni plugin the pod cidr is the same as the host cidr. When using Calico it would have no knowledge of the IPs used by hosts so a different cidr would need to be used for Calico so that the Calico plugin would not allocate any IPs that are used by any hosts in the system.
2nd, When the pods that had been created with the aws cni were deleted, their IPs would not be properly freed back to since at that point the Calico cni plugin would be used and it would not know how or that the IPs would need to be released in the AWS pool.

**Comment by caseydavenport** [comment] 2020-05-13 19:34
Yeah, I've played around with this. It's certainly possible to use Calico for routing on an EKS cluster just fine. The issue is that you can't do it without disrupting existing workloads, so if you care about that then you need to do it before you launch any pods into the cluster.

**Closed by caseydavenport** 2020-05-13 19:34 UTC
Labels: kind/support
