### ISSUE TITLE
Cannot access kube-apiserver via CLUSTER-IP from pod

### ISSUE THREAD

**Issue by BedivereZero** [projectcalico/calico#3822] opened 2020-07-22 17:06 UTC
1. Run `curl -k https://10.96.0.1/version` in pod failed. Error message: host is unreachable.
2. coredns's pods cannot access kube-apiserver

Kubernetes is deployed via kubeadm, *kube-proxy use IPVS*,  when kube-proxy use IPTABLES every thing is ok.

Run `curl -k https://10.96.0.1/version' on host successfully, so I think IPVS is OK.

## Expected Behavior
kube-apiserver is reachable from pod

## Possible Solution
I add iptables rules to log. The problem may be here:

```iptables
-A cali-INPUT -m comment --comment "cali:ss8lEMQsXi-s6qYT" -j MARK --set-xmark 0x0/0xfff00000
-A cali-INPUT -m comment --comment "cali:PgIW-V0nEjwPhF_8" -j cali-forward-check
-A cali-INPUT -m comment --comment "cali:QMJlDwlS0OjHyfMN" -m mark ! --mark 0x0/0xfff00000 -j RETURN
-A cali-INPUT -i cali+ -m comment --comment "cali:nDRe73txrna-aZjG" -g cali-wl-to-host
```

iptable's log:

```log
Jul 22 10:20:00 node-181 kernel: IPVS:IN=cali94d36b574ae OUT= MAC=ee:ee:ee:ee:ee:ee:0a:fd:d6:f5:a0:d8:08:00 SRC=192.181.115.195 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=8735 DF PROTO=TCP SPT=35382 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0xab240000 
Jul 22 10:20:00 node-181 kernel: IPVS:IN=calie7c56365999 OUT= MAC=ee:ee:ee:ee:ee:ee:fe:58:ee:f5:f5:4d:08:00 SRC=192.181.115.194 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=18546 DF PROTO=TCP SPT=41564 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0xdd140000 
Jul 22 10:20:00 node-181 kernel: IPVS:IN=cali0d46cb987ff OUT= MAC=ee:ee:ee:ee:ee:ee:72:89:f8:9f:47:e5:08:00 SRC=192.181.115.193 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=25315 DF PROTO=TCP SPT=60532 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0x66540000 
Jul 22 10:20:01 node-181 kernel: IPVS:IN=cali94d36b574ae OUT= MAC=ee:ee:ee:ee:ee:ee:0a:fd:d6:f5:a0:d8:08:00 SRC=192.181.115.195 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=42138 DF PROTO=TCP SPT=35400 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0xab240000 
Jul 22 10:20:01 node-181 kernel: IPVS:IN=cali94d36b574ae OUT= MAC=ee:ee:ee:ee:ee:ee:0a:fd:d6:f5:a0:d8:08:00 SRC=192.181.115.195 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=35698 DF PROTO=TCP SPT=35262 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0xab240000 
Jul 22 10:20:01 node-181 kernel: IPVS:IN=calie7c56365999 OUT= MAC=ee:ee:ee:ee:ee:ee:fe:58:ee:f5:f5:4d:08:00 SRC=192.181.115.194 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49044 DF PROTO=TCP SPT=41582 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0xdd140000 
Jul 22 10:20:01 node-181 kernel: IPVS:IN=cali0d46cb987ff OUT= MAC=ee:ee:ee:ee:ee:ee:72:89:f8:9f:47:e5:08:00 SRC=192.181.115.193 DST=10.96.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=50102 DF PROTO=TCP SPT=60550 DPT=443 WINDOW=28000 RES=0x00 SYN URGP=0 MARK=0x66540000 
```

1. Mark bits are set to `000`
2. Different bits are marked according to the nic (cali-xxx) from
3. Package is unaccepted because mark bits are not `000`

If I understand correctly, package should be accepted by the fourth rule, and be transferred to real server by IPVS

## Steps to Reproduce (for bugs)
1. Deploy kubernetes with kubeadm
2. Deploy calico, get manifest from ` https://docs.projectcalico.org/manifests/calico.yaml` and change env `CALICO_IPV4POOL_CIDR`

kubeadm-config.yaml

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.136.181
  bindPort: 6443
nodeRegistration:
  taints: []

---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
imageRepository: acr2.aishu.cn/public
kubernetesVersion: v1.18.5
networking:
  podSubnet: 192.181.0.0/16
  serviceSubnet: 10.96.0.0/12

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
```

## Your Environment
Kubernetes: 1.16.3 & 1.18.5
Calico: 3.10.4 & 3.15.1
Kernel: 3.10.0-1127.13.1-el7.x86_64
OS: CentOS 7.8.2003

**Comment by song-jiang** [comment] 2020-08-06 21:16
@BedivereZero Thanks for reporting this issue. Could you help to see if a packet been dropped by an iptable rule? You can run `sudo iptables-save -c | grep DROP` on the host while running `curl -k https://10.96.0.1/version` in the pod. If the count number of one DROP rule goes up, this indicates packet been dropped by this rule.

**Comment by BedivereZero** [comment] 2020-08-11 10:53
@song-jiang Thanks, I found the reason. Package was dropped by the rule of firewalld. In the default, firewall will REJECT package from cali+. I create a zone and set its default target to ACCEPT to accept package from cali+.

```bash
firewall-cmd --new-zone=calico
firewall-cmd --zone=calico --set-target=ACCEPT
firewall-cmd --zone=calico --add-interface=cali+
```

**Comment by song-jiang** [comment] 2020-08-11 11:38
@BedivereZero Glad to know you've found the root cause. Can we close this issue?

**Comment by BedivereZero** [comment] 2020-08-11 14:56
@song-jiang Of course. Thanks again for your suggestions.

**Closed** 2020-08-11 20:12 UTC
