### ISSUE TITLE
Duplicate CIDR (blockaffinities) allocation

### ISSUE THREAD

**Issue by CharlieR-o-o-t** [projectcalico/calico#6001] opened 2022-05-01 19:05 UTC
I have encountered routing problem with kubernetes - calico setup. The main problem was that the same IP has been assigned by calico for two nodes. Traffic came from node "hostnamefoo" to "worker_node", after that response have been sent to "hostnamebar" node by routing table (bgp bird route):

hostnamefoo (192.168.168.71) -> worker_node -> hostnamebar (192.168.168.71)

1) I have found that there are net block allocation duplicate in kubernetes:
```
kubectl get blockaffinities

hostnamefoo-192-168-168-64-26       275d
hostnamebar-1-192-168-168-128-26   275d
hostnamebar-1-192-168-168-64-26    275d
```
here cidr  "192.168.168.64/26" allocated to both nodes "hostnamefoo" and "hostnamebar".

2)  if we inspect **blockaffinities** we can find out that "state" different for those conflicting objects:

hostnamefoo-192-168-168-64-26
```
spec:
  cidr: 192.168.168.64/26
  deleted: "false"
  node: hostnamefoo
  state: confirmed 
```

hostnamebar-1-192-168-168-64-26
```
 spec:
  cidr: 192.168.168.64/26
  deleted: "false"
  node: hostnamebar
  state: pending
```

3) Finally I have checked bird config, to make sure that configuration generated by confd is valid:
fragment hostnamefoo 
```
protocol static {
   # IP blocks for this host.
   route 192.168.168.64/26 blackhole;
}

 # Aggregation of routes on this host; export the block, nothing beneath it.
function calico_aggr ()
{
      # Block 192.168.168.64/26 is confirmed
      if ( net = 192.168.168.64/26 ) then { accept; }
      if ( net ~ 192.168.168.64/26 ) then { reject; }
}
```

fragment from hostnamebar
```
protocol static {
   # IP blocks for this host.
   route 192.168.168.128/26 blackhole;
   route 192.168.168.64/26 blackhole;
}

# Aggregation of routes on this host; export the block, nothing beneath it
function calico_aggr ()
{
      # Block 192.168.168.128/26 is confirmed
      if ( net = 192.168.168.128/26 ) then { accept; }
      if ( net ~ 192.168.168.128/26 ) then { reject; }
      # Block 192.168.168.64/26 is pending
}
```
As I can see from bird configuration, node hostnamefoo should be "source of truth" for cidr block  192.168.168.64/26, but we have routes pointing to hostnamebar (as gateway) for some reason. 

## Expected Behavior
Node hostnamefoo should be default gw for cidr block 192.168.168.64/26 

## Current Behavior
Node hostnamebar is default gw for cidr block  192.168.168.64/26 

## Possible Solution
Bird bug? 

## Steps to Reproduce (for bugs)
- 

## Your Environment
* Calico version
v3.19.1
* Kubernetes:
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14", GitCommit:"0fd2b5afdfe3134d6e1531365fdb37dd11f54d1c", GitTreeState:"clean", BuildDate:"2021-08-11T18:02:17Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version:
CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.36.2.el7.x86_64

**Comment by caseydavenport** [comment] 2022-05-02 21:05
Yep this looks like a bug. It's possible that two nodes race for the same block - in this case, that seems to be working as intended. Namely, that the "loser" of that race is in "pending" state.

However, the BIRD config should ignore the "pending" block affinity. Instead, it seems to be happily including that.

**Comment by caseydavenport** [comment] 2022-05-02 21:08
Think we either need to:
- Stop including "pending" blocks within the `protocol static` section.
- Explicitly reject "pending" blocks within the `calico_aggr` filter. 

Not sure which (or both) of those is best off the top of my head.

**Comment by caseydavenport** [comment] 2022-10-19 17:10
Fixed in https://github.com/projectcalico/calico/pull/6003

**Closed by caseydavenport** 2022-10-19 17:10 UTC
Labels: kind/bug, likelihood/low, impact/high
