### ISSUE TITLE
Mesos install guide should warn about loose RPF setting

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#282] opened 2016-11-30 09:31 UTC
Seems Mesos sets the kernel's RPF check to loose, which allows containers to spoof.  For containers, that's just about OK, because only privileged containers can spoof their IPs.  For VMs, it's certainly not OK.  Hence we have a config flag that must be disabled to bypass Felix's check on the setting.

Thorough discussion here: https://github.com/projectcalico/calico-containers/issues/1082

**Comment by djosborne** [comment] 2016-11-30 17:14
Closing as dupe of #278

**Closed by djosborne** 2016-11-30 17:14 UTC
