### ISSUE TITLE
Calico Apiserver not delete Resource with OwnerReference 

### ISSUE THREAD

**Issue by dtrouillet** [projectcalico/calico#5715] opened 2022-03-07 16:05 UTC
I have an operator which create a networkpolicies.projectcalico.org/v3 with a OwnerRefernce and when I delete my Custom Resource, the networkpolicies.projectcalico.org/v3 is not deleted.

## Expected Behavior
I expect that the deletion of my Custom Resources delete at the same time the networkpolicies.projectcalico.org/v3 (with the OwnerReference)

## Current Behavior
When I delete my Custom Resources, the networkpolicies.projectcalico.org/v3 is not deleted.

## Steps to Reproduce (for bugs)
1. Create a resource 
2. Create networkpolicies.projectcalico.org/v3 with OwnerReference of last created resource
3. Delete with kubectl the step 1' resource

## Context
The Calico Api Server is deployed inside the cluster

My Custom Resource :
```
apiVersion: mycrd.fr/v1alpha1
kind: FluxNP
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mycrd.fr/v1alpha1","kind":"FluxNP","metadata":{"annotations":{},"name":"ext","namespace":"test"},"spec":{"allow":true,"interval":3600}}
  creationTimestamp: "2022-03-07T16:03:18Z"
  generation: 1
  name: ext
  namespace: test
  resourceVersion: "16336"
  uid: 0e5e3214-5bda-429e-8d53-2f1b77363286
spec:
  allow: true
  interval: 3600
status:
  lastUpdated: "2022-03-07T16:03:18Z"
  revision: 1
```

The networkpolicies.projectcalico.org/v3 : 
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  creationTimestamp: "2022-03-07T16:03:18Z"
  name: ext
  namespace: test
  ownerReferences:
  - apiVersion: mycrd.fr/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: FluxNP
    name: ext
    uid: 0e5e3214-5bda-429e-8d53-2f1b77363286
  resourceVersion: "16335"
  uid: f14af896-94a3-453c-a9b1-4a29aaa9e20f
spec:
  egress:
  - action: Allow
    destination: {}
    source: {}
  types:
  - Egress
```

## Your Environment
* Calico version : 3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): rk2 1.21.5
* Operating System and version: Redhat 8.2

**Comment by dtrouillet** [comment] 2022-03-08 16:44
For information, I have been create a finalizer as workaround, it works.

**Comment by dtrouillet** [comment] 2022-03-08 18:13
Mh, I'm not sure too. Because with a standard kubernetes network policy it works.

**Comment by lwr20** [comment] 2022-03-08 18:16
Perhaps one for @caseydavenport

**Comment by caseydavenport** [comment] 2022-03-09 23:20
Pretty sure this is actually a bug in the way we do owner references for our CRDs. 

In fact, @robbrockbank recently attempted a couple of fixes for this but they each had some problems:

- https://github.com/projectcalico/calico/pull/5532
- https://github.com/projectcalico/calico/pull/5535

The main issue here is that our `projectcalico.org/v3` API resources are in fact stored behind-the-scenes as `crd.projectcalico.org/v1` objects with the same UID, but without the same owner references, which confuses the garbage collector in the Kubernetes API when it sees two objects with the same UID and different owner references.

The two attempts that @robbrockbank make above were to:
1. Use the UID of the backing CRD, but in reverse on the v3 object in order to make it unique. This has the problem of being pretty hacky, and on upgrade any watch clients of the API server might get a bit confused as all of the object's UIDs would change. 
2. Copy owner references through to the backing CRD so that on garbage collection the backing CRD would be deleted. This has the problem of not showing up properly in audit logs, as DELETE requests would be made to the `crd.projectcalico.org/v1` API rather than the `projectcalico.org/v3` API.

I think out of the two options, 1 is preferable although not great. The other option might be to generate a totally new UID for our resources and store it in a new field on the backing CRD. This would would for all new resources and avoid the pitfalls of the above two approaches, but would mean that the UID is editable by any privileged user to intentionally or accidentally edits the wrong API resource, and so is a fairly major footgun. 

CC @fasaxc since he's pretty smart and might have alternative ideas :laughing:

**Comment by fasaxc** [comment] 2022-04-04 14:03
Ugh, nasty problem.  

I'd be careful about reversing a UUID since UUIDs have structure, it'd be better to 
* Unpack the UUID.
* Remove the metadata bytes.
* Scramble the rest (say by encrypting with a fixed key).
* Write a new "random" UUID with the scrambled data.

Sounds like the annotation approach has problems too (missing on deletes, Rob said)

**Comment by robbrockbank** [comment] 2022-04-05 16:29
@fasaxc :  I wasn't entirely sure what the structure of the UUID entailed... couldn't find much about it in my 3s search :-)   The reversal "algorithm" I wrote actually reversed each "section" of the UUID.  So:

abcde-fgh-ijkl    would become  edcba-hgf-lkji  

Would that be sufficient?

Key thing is we can hop algorithmically calculate one from the other in both directions.

**Comment by fasaxc** [comment] 2022-04-05 17:29
https://en.wikipedia.org/wiki/Universally_unique_identifier#Format

**Comment by cmssczy** [comment] 2022-06-23 06:08
Is there any progress on this issue?

**Comment by Redlinkk** [comment] 2023-02-02 16:47
Hello ! 
I think I'm facing a similar issue but with ServiceAccounts and Calico Profiles. I have installed Calico as an add-on to the AWS VPC-CNI.

#### What's happening :
A **foreground** delete is triggered on a ServiceAccount `a` in namespace `n`. Usually everything is fine and the service account is deleted, but sometimes, it is just stuck waiting to be deleted : it has a `deletionTimestamp` set and the `foregroundDeletion` finalizer.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-01-06T08:55:03Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-01-06T08:59:18Z"
  finalizers:
    - foregroundDeletion
  name: a
  namespace: n
  resourceVersion: '172497815'
  uid: ff598753-e546-4d6c-9ba9-2f0eb91ddb0f
secrets:
  - name: a-token-123de
```

#### Controller logs
When everything is fine, I see this kind of logs :
```
I0106 08:55:00.907897      11 graph_builder.go:587] add [v1/ServiceAccount, namespace: n, name: a, uid: 3e593fef-8b58-4217-98c4-287f22e2a172] to the attemptToDelete, because it's waiting for its dependents to be deleted
I0106 08:55:00.908030      11 garbagecollector.go:471] "Processing object" object="n/a" objectUID=3e593fef-8b58-4217-98c4-287f22e2a172 kind="ServiceAccount" virtual=false
I0106 08:55:00.952369      11 garbagecollector.go:590] remove DeleteDependents finalizer for item [v1/ServiceAccount, namespace: n, name: a, uid: 3e593fef-8b58-4217-98c4-287f22e2a172]
```
There is no logs about the Calico Profile.

And when it's stuck :
```
I0106 08:59:18.837337      11 graph_builder.go:587] add [projectcalico.org/v3/Profile, namespace: , name: ksa.n.a, uid: ff598753-e546-4d6c-9ba9-2f0eb91ddb0f] to the attemptToDelete, because it's waiting for its dependents to be deleted
I0106 08:59:18.837447      11 garbagecollector.go:471] "Processing object" object="ksa.n.a" objectUID=ff598753-e546-4d6c-9ba9-2f0eb91ddb0f kind="Profile" virtual=false
I0106 08:59:18.887644      11 garbagecollector.go:590] remove DeleteDependents finalizer for item [projectcalico.org/v3/Profile, namespace: , name: ksa.n.a, uid: ff598753-e546-4d6c-9ba9-2f0eb91ddb0f]
```
And this time, no logs about the ServiceAccount.


I think that using the same UID for both objects breaks the Kubernetes graph builder and garbage collector here. It's flaky and it has a quite low rate of trigger. I'm thinking some kind of race condition when the graph is built, but I'm not sure. I am not able to consistently trigger it, but I has this issue on many ServiceAccounts from different deployments on different clusters.

Do you have any news about this issue ?
Thanks

**Comment by fasaxc** [comment] 2023-02-07 12:12
Looks like we already merged the option 1 fix in Calico Enterprise so let's at least upstream that.  Need to reassess if there's still more to this issue though.

**Comment by Redlinkk** [comment] 2023-02-09 12:53
Awesome, thanks for the fix !

**Comment by fasaxc** [comment] 2023-02-15 15:30
The "fix" caused some regressions that took a while to track down.  I've reverted it for now.

**Comment by edwardzjl** [comment] 2023-03-17 07:21
> Hello ! I think I'm facing a similar issue but with ServiceAccounts and Calico Profiles. I have installed Calico as an add-on to the AWS VPC-CNI.
> 
> #### What's happening :
> A **foreground** delete is triggered on a ServiceAccount `a` in namespace `n`. Usually everything is fine and the service account is deleted, but sometimes, it is just stuck waiting to be deleted : it has a `deletionTimestamp` set and the `foregroundDeletion` finalizer.
> 
> ```
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   creationTimestamp: "2023-01-06T08:55:03Z"
>   deletionGracePeriodSeconds: 0
>   deletionTimestamp: "2023-01-06T08:59:18Z"
>   finalizers:
>     - foregroundDeletion
>   name: a
>   namespace: n
>   resourceVersion: '172497815'
>   uid: ff598753-e546-4d6c-9ba9-2f0eb91ddb0f
> secrets:
>   - name: a-token-123de
> ```
> 
> #### Controller logs
> When everything is fine, I see this kind of logs :
> 
> ```
> I0106 08:55:00.907897      11 graph_builder.go:587] add [v1/ServiceAccount, namespace: n, name: a, uid: 3e593fef-8b58-4217-98c4-287f22e2a172] to the attemptToDelete, because it's waiting for its dependents to be deleted
> I0106 08:55:00.908030      11 garbagecollector.go:471] "Processing object" object="n/a" objectUID=3e593fef-8b58-4217-98c4-287f22e2a172 kind="ServiceAccount" virtual=false
> I0106 08:55:00.952369      11 garbagecollector.go:590] remove DeleteDependents finalizer for item [v1/ServiceAccount, namespace: n, name: a, uid: 3e593fef-8b58-4217-98c4-287f22e2a172]
> ```
> 
> There is no logs about the Calico Profile.
> 
> And when it's stuck :
> 
> ```
> I0106 08:59:18.837337      11 graph_builder.go:587] add [projectcalico.org/v3/Profile, namespace: , name: ksa.n.a, uid: ff598753-e546-4d6c-9ba9-2f0eb91ddb0f] to the attemptToDelete, because it's waiting for its dependents to be deleted
> I0106 08:59:18.837447      11 garbagecollector.go:471] "Processing object" object="ksa.n.a" objectUID=ff598753-e546-4d6c-9ba9-2f0eb91ddb0f kind="Profile" virtual=false
> I0106 08:59:18.887644      11 garbagecollector.go:590] remove DeleteDependents finalizer for item [projectcalico.org/v3/Profile, namespace: , name: ksa.n.a, uid: ff598753-e546-4d6c-9ba9-2f0eb91ddb0f]
> ```
> 
> And this time, no logs about the ServiceAccount.
> 
> I think that using the same UID for both objects breaks the Kubernetes graph builder and garbage collector here. It's flaky and it has a quite low rate of trigger. I'm thinking some kind of race condition when the graph is built, but I'm not sure. I am not able to consistently trigger it, but I has this issue on many ServiceAccounts from different deployments on different clusters.
> 
> Do you have any news about this issue ? Thanks

I have a similar issue, but I'm not deleting the ServiceAccount directly.

I have a CustomResource who owns a ServiceAccount. Usually when deleting the parent resource, the child ServiceAccount should be deleted.

But with calico, on deleting the parent CustomResource, the deletion of ServiceAccount was blocked.

For example I have a parent ConfigMap:

```sh
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: mymap-parent
EOF
```

And if I create a ServiceAccount as a child resource of that ConfigMap:

```sh
CM_UID=$(kubectl get configmap mymap-parent -o jsonpath="{.metadata.uid}")
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa-child
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: mymap-parent
    uid: $CM_UID
EOF
```

When deleting the parent ConfigMap there's a warning event:

```console
$ kubectl get events
LAST SEEN   TYPE      REASON                     OBJECT                           MESSAGE
47m         Warning   OwnerRefInvalidNamespace   profile/ksa.default.mysa-child   ownerRef [v1/ConfigMap, namespace: , name: mymap-parent, uid: 529e7cc5-e3cb-49a1-99e6-22b26a04d84c] does not exist in namespace ""
```

I'm not sure whether it's related to the uid, but it seems that kubernetes garbage collector treats `profile/ksa.default.mysa-child` as a child resource of the parent ConfigMap. And as profile is a custer-scoped resource, it cannot have a namespaced ownerReference, thus the deletion was blocked.

What also confuses me is that I can't find any CRD named profile.projectcalico.org

I opened a issue in kubernetes repo first: kubernetes/kubernetes#116632, there's more information.

**Comment by liggitt** [comment] 2023-03-17 11:13
> I think that using the same UID for both objects breaks the Kubernetes graph builder and garbage collector here

yes, using the same UID for two different objects is incorrect and breaks the garbage collector

**Comment by caseydavenport** [comment] 2023-03-24 00:39
> I'm not sure whether it's related to the uid, but it seems that kubernetes garbage collector treats profile/ksa.default.mysa-child as a child resource of the parent ConfigMap. And as profile is a custer-scoped resource, it cannot have a namespaced ownerReference, thus the deletion was blocked.

Yikes, yes this is pretty terrible and a consequence of some internal baggage the Calico API server is carrying around combined with the UID duplication baggage. 

There's no CRD called "Profile", but there is a `projectcalico.org/v3` API resource called Profile which coincidentally is a different view into the ServiceAccount API, which would be why this is happening.

We'll need another fix for that API as well.

**Comment by piersharding** [comment] 2023-09-13 18:35
I'm also seeing this in a customer operator that creates statefulsets with their own SAs.  On deletion of the parent resource, the SA is left hanging around with an OwnerRefInvalidNamespace Event.  This will also hit any other operator of a similar pattern which I'd expect is fairly common.

**Comment by zoezhangmattr** [comment] 2024-02-20 07:17
heya 
is this issue fixed, we are using version 3.26.1, and still have the same problem,  the profile UUID same with service account UUID, which caused the serviceaccount deletion(foreground) stuck 
thanks

**Closed** 2024-03-15 16:59 UTC
Labels: kind/bug, likelihood/high, impact/high

**Comment by caseydavenport** [comment] 2024-03-15 17:06
Just merged a fix for this targeting v3.28.0. Will let it soak a bit and if it continues to look good will look at backports to earlier branches as well.

**Comment by scottcrawford03** [comment] 2024-08-28 22:14
heya @caseydavenport any more thought towards backporting the fix to earlier branches? 🙏

**Comment by caseydavenport** [comment] 2024-08-28 22:38
@scottcrawford03 thanks for the reminder. 

I think we're looking good for a backport to v3.27. I don't think we'll be able to squeeze this into the (very likely final) v3.26 patch release before v3.29 is released.
