### ISSUE TITLE
[Windows] Issue with ReadinessProbe suddenly failing on all pods of one node

### ISSUE THREAD

**Issue by eyenx** [projectcalico/calico#6196] opened 2022-06-07 14:48 UTC
We have the problem, that on our Windows 2019 Datacenter Servers several times a day all pods of a node show as failing the ReadinessProbe.

This fixes itself after 5-10 minutes, but continues to happen over and over.

All our windows nodes on all our clusters have this problem. No linux nodes have the same behaviour.

We see the Pods becomeing `0/1` suddenly. The Node is then unreachable via SSH, but can be pinged and a `kubectl exec` on a specific Pod running on that nod is working without issues.

After looking for a few hours we could not find the logs to troubleshoot this further.

## Expected Behavior

ReadinessProbes do not fail on Windows nodes without any reason.

## Current Behavior
ReadinessProbes fail several times a day on all pods of a single Windows node, but fix themselves after a few minutes.

## Steps to Reproduce (for bugs)

Can't be actively reproduced. But happens quite often.

## Context

Running Windows Pods on Windows Nodes with ReadinessProbe

## Your Environment

* Calico version `3.20.3` on WIndows (Same version on Linux Nodes)
* Orchestrator version (e.g. kubernetes, mesos, rkt): `k8s v1.22.8`
* Operating System and version: Windows Server 2019 Datacenter 10.0.17763.2305 / ContainerD 1.5.8

Attached several outputs to help out (kube-proxy & kubelet error log from respective node & some output from kubectl and directly from the Node).

[errors.txt](https://github.com/projectcalico/calico/files/8854227/errors.txt)
[kube-proxy.err.log](https://github.com/projectcalico/calico/files/8854228/kube-proxy.err.log)
[kube-proxy.err-20220607T134535.340.log](https://github.com/projectcalico/calico/files/8854229/kube-proxy.err-20220607T134535.340.log)
[kubelet.err.log](https://github.com/projectcalico/calico/files/8854230/kubelet.err.log)

**Comment by caseydavenport** [comment] 2022-06-09 10:55
@song-jiang @lmm

**Comment by song-jiang** [comment] 2022-06-09 12:52
@eyenx According to errors.txt (see below), who owns the IP:Port of `10.147.49.49:80`? 

```
$ kubectl get events -n app-int-app5
LAST SEEN   TYPE      REASON      OBJECT                    MESSAGE
42m         Warning   Unhealthy   pod/app5-cc5b588cb-t67xw   Readiness probe failed: Get "http://10.147.49.49:80/server/status": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by song-jiang** [comment] 2022-06-09 15:58
> But it is reachable
Do you mean when you try to access `10.147.49.49:80` from the Windows node which hosts the pod by yourself, it works fine?

**Comment by eyenx** [comment] 2022-06-09 16:14
this I cannot check as SSH is not working on theu node at that time. but kubectl exec works and the Pod is reachable. As mentioned above this happens for 5-10 minutes on all pod of a node at the same time. after that timeframe the pods go back to being healthy and the Node is again reachable via ssh.

I am assuming something with calico to be not okay.

**Comment by song-jiang** [comment] 2022-06-10 09:24
It is rare Calico can affect traffic in this pattern. Normally if there is an issue with Calico, either the traffic is allowed or denied.

**Comment by eyenx** [comment] 2022-06-10 13:57
We managed to get a local Admin Account so we could access the node during that timeframe without SSH. Curl to the Pod gives back a timeout. 

So you suggest Calico can't be the culprit in this case?

**Comment by lwr20** [comment] 2022-06-14 16:28
What's the interval for this happening?  Sometimes that can hint at the cause.

Without knowing the interval, I'd be guessing things like DHCP renewal.  Check windows logs to find out what's going on around the time it happens.

**Comment by sil-zh** [comment] 2022-06-16 11:08
Hi,

@song-jiang 
i am working with @eyenx at this issue. attached you can find the logs from c:\CalicoWindows\logs directory.

[calico-felix-20220613T211108.090.log](https://github.com/projectcalico/calico/files/8918276/calico-felix-20220613T211108.090.log)
[calico-node.err.log](https://github.com/projectcalico/calico/files/8918277/calico-node.err.log)
[calico-node.log](https://github.com/projectcalico/calico/files/8918278/calico-node.log)
[calico-felix.err.log](https://github.com/projectcalico/calico/files/8918279/calico-felix.err.log)
[calico-felix.log](https://github.com/projectcalico/calico/files/8918280/calico-felix.log)
[calico-felix-20220513T164524.844.log](https://github.com/projectcalico/calico/files/8918281/calico-felix-20220513T164524.844.log)
[calico-felix-20220513T164524.846.log](https://github.com/projectcalico/calico/files/8918282/calico-felix-20220513T164524.846.log)
[calico-felix-20220601T194316.181.log](https://github.com/projectcalico/calico/files/8918283/calico-felix-20220601T194316.181.log)

The issue happend on this node today (16 June) arround 12:55. The logs are from arround 12:58.

@lwr20 - i can't tell the interval, but its quite often (i would guess every 2-3 hours.). DHCP is not the case - as ping is possible during this time and the server has a fixxed ip address, no dhcp.

**Comment by sil-zh** [comment] 2022-07-05 11:57
Some more informations about this issue - as it is still open.

As told before, no ssh connection is possible during the time of the issue. But port 22 is always open (tested with nc).
Also logged in connections via SSH are working. So i was logged in on one server and had a loop running. the loop curled to a website in the internet and did a ping.

when the issue came up, ping was working while curl faiuled (unable to connect to the remote server).

during the time of the issue, i could see that the node sends packages to the pods (i guess readynessprobe).
in netstat i could see (for all the pods):

10.15.19.117:65103     10.147.127.34:80       SYN_SENT

i dont know if it helps, but at least some more informations

**Comment by coutinhop** [comment] 2023-05-16 17:05
@eyenx @sil-zh are you still facing this issue? Calico v3.20 is old at this point, were you able to upgrade to a more recent version? Hopefully that's fixed your issues, but checking in before closing this...

**Comment by tomastigera** [comment] 2023-05-30 16:48
Closing as stale unless there is new info.

**Closed as completed by tomastigera** 2023-05-30 16:48 UTC
Labels: kind/support, area/windows
