### ISSUE TITLE
Calico support for stretched v6 clusters across multiple L2 subnets

### ISSUE THREAD

**Issue by svallala** [projectcalico/calico#4599] opened 2021-05-10 19:26 UTC
Issue:

We have a need to stretch a cluster across multiple v6 subnets. We have tried BGP and VXLAN as the backend with Calico, but both of them expect underneath infrastructure configuration to support stretching the V6 cluster across subnets. With BGP, peering has to be configured with the routers in between. This works seamlessly with V4 clusters, is there any option to have this working with V6?

Calico Version:

3.12.3

**Comment by song-jiang** [comment] 2021-05-20 16:35
@svallala I believe Calico supports BGP in the same way with both v4 and v6 . Not sure why your cluster only got v4 working. Maybe checking v6 routes in between your subnets ?

**Comment by svallala** [comment] 2021-05-20 16:38
Across v6 subnets how will Pod routing work without any kind of tunneling in place. The underneath infrastructure has to have BGP peering enabled. When it's V4 since pod traffic can be tunneled it's easy.

**Comment by song-jiang** [comment] 2021-05-20 16:44
@neiljerram Probably one for you. Could you help?

**Comment by neiljerram** [comment] 2021-05-20 17:30
@svallala With BGP it will only work if the infrastructure router learns how to route pod IPs.  Can you peer from Calico to the infrastructure router?  Or can you teach the infrastructure router about pod IPs in some other way?

**Comment by neiljerram** [comment] 2021-05-20 17:31
With VXLAN I'm not sure but I guess the problem is that we've only implemented IPv4 over VXLAN, and not IPv6 over VXLAN.

**Comment by neiljerram** [comment] 2021-05-20 17:33
Yes, that's right.  Our doc at https://docs.projectcalico.org/archive/v3.19/networking/vxlan-ipip says
> IP in IP and VXLAN support only IPv4 addresses.

**Comment by neiljerram** [comment] 2021-05-20 17:36
@svallala Another possible approach might be for you to use L2TP to simulate a single subnet across your whole cluster.  We do that for some of our testing, so that we can test non-overlay (i.e. BGP) for both IPv4 and IPv6, on GCP instances.

**Comment by svallala** [comment] 2021-05-20 17:47
Thanks, @neiljerram, and @song-jiang for the info. 

Yes, today we are using BGP peering to solve this for certain cases. The moment we have to configure the underneath infrastructure, the flexibility and ease of using a private Pod Network are lost.

Is it in your roadmap to support VXLAN for IPv6? Any timelines that you can share? As more operators are moving to k8s, there are a lot more v6 deployments, since Calico is popular, it would be good if you have a story for v6 sooner. 

Thanks

**Comment by neiljerram** [comment] 2021-05-20 20:39
@caseydavenport Can you comment if VXLAN for IPv6 is on our roadmap?

**Comment by neiljerram** [comment] 2021-05-20 20:49
@svallala Also, though, for the record, I don't think it's clear that
> The moment we have to configure the underneath infrastructure, the flexibility and ease of using a private Pod Network are lost

Peering infrastructure router(s) with Calico can be a fairly trivial thing to set up, and many cluster designers are happy to do that in order to avoid a VXLAN/IPIP overlay for their pod traffic between nodes.

**Comment by svallala** [comment] 2021-05-20 22:40
@neiljerram yes I agree, configuring BGP is a trivial thing. But in big operators, every small change can take a long time, especially if it's network infrastructure-related.

**Comment by caseydavenport** [comment] 2021-09-21 16:30
> @caseydavenport Can you comment if VXLAN for IPv6 is on our roadmap?

Whoops, I missed this one. Yes, this is something I would like to do. It doesn't have a date yet on our roadmap, but there is an enhancement already raised for it.

https://github.com/projectcalico/libcalico-go/issues/996

I'm going to close this one for now since I believe it's a duplicate of that issue ^

**Closed by caseydavenport** 2021-09-21 16:30 UTC
Labels: kind/enhancement
