### ISSUE TITLE
v3.25.1: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#7645] opened 2023-05-12 03:10 UTC
## Expected Behavior

No panic happend

## Current Behavior

```shell
2023-05-12 03:06:32.895 [DEBUG][351] felix/update_filter.go 135: FilterUpdates: add with empty queue, short circuit.
2023-05-12 03:06:32.895 [DEBUG][351] felix/iface_monitor.go 159: Address update addrUpdate={Ifindex: 1 Dst: <nil> Src: <nil> Gw: <nil> Flags: [] Table: 2004 Realm: 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1943bfa]

goroutine 256 [running]:
github.com/projectcalico/calico/felix/ifacemonitor.(*InterfaceMonitor).handleNetlinkRouteUpdate(_, {0x18, {0x1, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...}})
	/go/src/github.com/projectcalico/calico/felix/ifacemonitor/iface_monitor.go:211 +0x7a
github.com/projectcalico/calico/felix/ifacemonitor.(*InterfaceMonitor).MonitorInterfaces(0xc000406e70)
	/go/src/github.com/projectcalico/calico/felix/ifacemonitor/iface_monitor.go:164 +0x7e5
created by github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).Start
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:1244 +0xf6
```

## Steps to Reproduce (for bugs)

1. Update ENV of calico-node `IP_AUTODETECTION_METHOD` to `interface=ens160` 
2. kubectl logs  -n kube-system calico-node <calico-node-pod> | grep panic -B 4 -A 9

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by mazdakn** [comment] 2023-05-16 16:33
@cyclinder thanks for reporting this.

**Comment by mazdakn** [comment] 2023-06-01 00:25
Closing since the issue is fixed. Thanks @cyclinder .

**Closed by mazdakn** 2023-06-01 00:25 UTC
Labels: kind/bug, likelihood/low, impact/high
