### ISSUE TITLE
how to set a static ip use calico for docker container

### ISSUE THREAD

**Issue by flyer5200** [projectcalico/calico#1012] opened 2016-04-29 12:45 UTC
How to set a static ip for docker container by used calico?

In Multi-Host environment, how to keep a static ip for docker container?

**Comment by fasaxc** [comment] 2016-04-29 12:54
Closing as dupe of https://github.com/projectcalico/calico-containers/issues/953

**Closed by fasaxc** 2016-04-29 12:54 UTC
