### ISSUE TITLE
calico-node restarts on master after apply -f calico.yaml

### ISSUE THREAD

**Issue by frnkdny** [projectcalico/calico#1038] opened 2017-08-21 21:48 UTC
Consistently observed that calico-node restarts on master after applying calico.yaml manifest while setting up a cluster with Calico policy with Calico networking. 

Versions: 
calico/node=v2.5.0-rc2

Manifests: 
https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

## Expected Behavior

 calico-node on master should not need to restart for the cluster to achieve a configured steady state. 

## Steps to Reproduce (for bugs)

1. terraform apply 
2. kubectl apply -f https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
3. kubectl apply -f https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
4. observe calico-node restarts on master
```
ubuntu@fd-crc-kubeadm-master:~$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                            READY     STATUS    RESTARTS   AGE       IP            NODE
kube-system   calico-node-3hrsf                               2/2       Running   1          1m        10.128.0.10   fd-crc-kubeadm-master
kube-system   calico-node-f97sb                               2/2       Running   0          1m        10.128.0.12   fd-crc-kubeadm-node-1
kube-system   calico-node-h8h1t                               2/2       Running   0          1m        10.128.0.11   fd-crc-kubeadm-node-0
kube-system   etcd-fd-crc-kubeadm-master                      1/1       Running   0          32s       10.128.0.10   fd-crc-kubeadm-master
kube-system   kube-apiserver-fd-crc-kubeadm-master            1/1       Running   0          32s       10.128.0.10   fd-crc-kubeadm-master
kube-system   kube-controller-manager-fd-crc-kubeadm-master   1/1       Running   0          32s       10.128.0.10   fd-crc-kubeadm-master
kube-system   kube-dns-2425271678-ngl7h                       3/3       Running   0          16m       192.168.2.2   fd-crc-kubeadm-node-1
kube-system   kube-proxy-4klhw                                1/1       Running   0          15m       10.128.0.11   fd-crc-kubeadm-node-0
kube-system   kube-proxy-928kf                                1/1       Running   0          15m       10.128.0.12   fd-crc-kubeadm-node-1
kube-system   kube-proxy-dphvk                                1/1       Running   0          16m       10.128.0.10   fd-crc-kubeadm-master
kube-system   kube-scheduler-fd-crc-kubeadm-master            1/1       Running   0          32s       10.128.0.10   fd-crc-kubeadm-master
```
The logs below do have 
```
ubuntu@fd-crc-kubeadm-master:~$ kubectl logs -n kube-system calico-node-3hrsf -c calico-node -p 
Checking datastore connection
Datastore connection verified
Using autodetected IPv4 address on interface ens4: 10.128.0.10/32
No AS number configured on node resource, using global value
time="2017-08-21T19:15:46Z" level=error msg="Error updating resource" Key=GlobalBGPConfig(name=AsNumber) Name=asnumber Resource=GlobalBGPConfigs Value=64512 error="Operation cannot be fulfilled on globalbgpconfigs.crd.projectcalico.org "asnumber": the object has been modified; please apply your changes to the latest version and try again" 
ERROR: Unable to set global default configuration: update conflict: 'GlobalBGPConfig(name=AsNumber)'
Terminating
Calico node failed to start
```

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by bcreane** [comment] 2017-08-21 22:09
Marking this a duplicate of https://github.com/projectcalico/calico/issues/1009 since that issue was raised first, but referencing the very useful reproduction steps for this bug.

**Closed by bcreane** 2017-08-21 22:09 UTC
Labels: kind/bug
