### ISSUE TITLE
Typos in master kubeadm Hosted Install page

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#1358] opened 2017-11-14 10:31 UTC
At https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubeadm/, the documentation includes:

"To install this Calico and a single node etcd on a run the following command:"

which I guess should be "To install Calico and a single node etcd on a ? run the following command:"

**Comment by ozdanborne** [comment] 2018-02-22 19:41
Closing as duplicate of https://github.com/projectcalico/calico/issues/1442

**Closed by ozdanborne** 2018-02-22 19:41 UTC
Labels: priority/P2
