### ISSUE TITLE
kubernetes endpoints cannot reached after upgrade

### ISSUE THREAD

**Issue by nancykyo** [projectcalico/calico#713] opened 2017-04-25 05:19 UTC
I have a k8s cluster of  3 nodes, call them node[1-3], node1 is master
k8s version: kuberadm 1.5.1
previous:
```
image: quay.io/calico/node:v1.0.0
image: calico/cni:v1.5.5
image: calico/kube-policy-controller:v0.5.1
image: calico/ctl:v1.0.0
```
after upgrading
```
image: quay.io/calico/node:v1.1.0
image: quay.io/calico/cni:v1.6.1
image: quay.io/calico/kube-policy-controller:v0.5.4
```
ip pool
```
# calicoctl get pool -o yaml
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.86.244.0/22
  spec:
    nat-outgoing: true
```
endpoints
```
kubectl get ep jenkins
NAME      ENDPOINTS           AGE
jenkins   10.86.246.68:8080   17h
```
iptables on node 2
```
iptables -t nat -L | grep  10.86.246.68
KUBE-MARK-MASQ  all  --  10.86.246.68         anywhere             /* default/jenkins:http */
DNAT       tcp  --  anywhere             anywhere             /* default/jenkins:http */ tcp to:10.86.246.68:8080
```
and it's not a policy or profile problem,  for 
endpoints on node3 is accessible.
`telnet 10.86.246.68 8080`  and `ping 10.86.246.68` is ok

can you help indicating how to debug this?

**Comment by cokabug** [comment] 2017-04-25 11:41
root cause

**Comment by cokabug** [comment] 2017-04-25 11:46
curl container in calico network from outside, there is no http response, so i try to tcpdump the packet, i found that the tcp handshake is broken, it shows the source send sync and container sync ack back to the source, but the last ack from source cannot received in container

**Comment by cokabug** [comment] 2017-04-25 11:52
same problem here. run curl cmd to container in calico network from outside, but there is no http response, so i try to tcpdump the packet, i found that the tcp handshake is broken, tcpdump result  shows the source sent a sync packet and container sync ack back to the source, but the last tcp ack from source cannot received in container.

**Comment by tmjd** [comment] 2017-04-25 14:22
@nancykyo It looks like your service CIDR and your IP Pool CIDR (cluster-cidr) are the same or they overlap at least, I believe that could cause some problems so I think you should correct that.

Some general questions:
- Where are your nodes running? (Bare-metal, GCE, AWS, OpenStack)
- What version of docker are you using?
- Are you passing `--cluster-cidr` to `kubeadm init`?

I'm a little confused on some details could you clarify:
- What node is the actual pod running on that you are trying to reach?
- Which nodes can reach the service address successfully?
  - You mentioned being able to reach it with curl and ping.

**Comment by tmjd** [comment] 2017-04-25 14:30
@cokabug Could you give some details on your packet captures?  It looks like the first one successfully setup the connection but then sending the HTTP request failed, which to me seems like an odd place for it to fail.
What host/container were these captures done on and which interface(s) were used?

**Comment by nancykyo** [comment] 2017-04-25 15:48
- Where are your nodes running?  (Bare-metal, GCE, AWS, OpenStack)
bare-metal
- What version of docker are you using?
1.12.1
- Are you passing --cluster-cidr to kubeadm init?
can't recall this, kube apiserver is running with this args
` --service-cluster-ip-range=10.96.0.0/12 `

it's able to reach it with telnet and ping, and curl on the **calico node config to our bgp switch**;

but  it's able to reach it with telnet and ping, but not curl on normal calico node

**Comment by nancykyo** [comment] 2017-04-25 15:49
and @cokabug is my colleague, we are trying to describe the same issue \(^o^)/~

**Comment by cokabug** [comment] 2017-04-26 03:13
it seems like tcp handshake is ok ,but ,the 3rd ack from source cannot arrive to container interface, the tcp connection is broken actually. so ,without a complete tcp connection, the http connection cannot established, as you can see , in the tcpdump screenshot , http get request sent ,but no http response come back from container .

**Comment by nancykyo** [comment] 2017-04-26 15:28
the ip range is not conflict:
calico pool 10.86.244.0/22
service range 10.96.0.0/12

BTW I tried dowgrade calico, and it worked again.

**Comment by tmjd** [comment] 2017-04-26 20:26
@nancykyo you said that telnet and ping work but not curl.  That seems like a problem with the container because if telnet can setup a connection then the problem would be higher up the stack.

You said you upgraded and the problem started, what is your process for upgrading?  Could you please give me a detailed description of how the upgrade was performed.

Could you please perform the upgrade once more and do the following and collect the following information?
  - Start a container with `kubectl run nginx --replicas=1 --image=nginx`
    - Please report the IP address too.
  - Perform a curl to the ip address of the pod created above from both the host running the container and another host in the cluster and report the results of both. (that would be to port 80)
    - Perform a curl or wget in a container `kubectl run test --rm -ti --image busybox /bin/sh` to the IP address from above.
  - Collect the output of `calicoctl node status` on the same hosts as above.
  - Collect the iptables info with `iptables-save` on the same hosts as above.
  - Collect the workload endpoints `calicoctl get wep -o yaml`
  - Collect the output from `ip route` and `ifconfig`
  - Collect policy info with `calicoctl get policy -o yaml`

**Comment by nancykyo** [comment] 2017-05-10 15:10
while i'm try to trace the traffic, I found this:
**cksum incorrect** 
may this cause the packet drop while tcp response?

```
tcpdump -vv -n host 10.86.247.137 and port 9000
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
06:07:31.331461 IP (tos 0x0, ttl 59, id 37863, offset 0, flags [DF], proto TCP (6), length 64)
    10.86.205.211.56723 > 10.86.247.137.cslistener: Flags [SEW], cksum 0xfcb4 (correct), seq 582355784, win 65535, options [mss 1240,nop,wscale 5,nop,nop,TS val 310910745 ecr 0,sackOK,eol], length 0
06:07:31.331528 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 52)
    10.86.247.137.cslistener > 10.86.205.211.56723: Flags [S.E], cksum 0xda2f (incorrect -> 0xfd09), seq 872334050, ack 582355785, win 29200, options [mss 1460,nop,nop,sackOK,nop,wscale 9], length 0
06:07:32.533999 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 52)
    10.86.247.137.cslistener > 10.86.205.211.56723: Flags [S.E], cksum 0xda2f (incorrect -> 0xfd09), seq 872334050, ack 582355785, win 29200, options [mss 1460,nop,nop,sackOK,nop,wscale 9], length 0


06:07:34.534000 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 52)
    10.86.247.137.cslistener > 10.86.205.211.56723: Flags [S.E], cksum 0xda2f (incorrect -> 0xfd09), seq 872334050, ack 582355785, win 29200, options [mss 1460,nop,nop,sackOK,nop,wscale 9], length 0
```

**Comment by nancykyo** [comment] 2017-05-10 17:44
guess what~
after upgrading it worked, \(^o^)/~ 
http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml

**Comment by tmjd** [comment] 2017-05-10 17:58
Yes I believe those packets would be dropped by an iptables INVALID rule.  You can double check by doing `sudo iptables -Z` (to clear the packet counters) and then check `sudo iptables-restore -c` after attempting the connection, you should be able to see packet counts go up on the DROP rules.

**Comment by tmjd** [comment] 2017-05-10 18:31
Ok.... I'm glad it is working now, sorry you had these issues. I'm going to close this issue since it is working for you now.  Please if you run into the problem again reopen this or create a new issue as appropriate.
Thank you for reporting back.

**Closed by tmjd** 2017-05-10 18:31 UTC
Labels: kind/support
