### ISSUE TITLE
Calico RBAC missing permissions

### ISSUE THREAD

**Issue by bartlomiejsawicki** [projectcalico/calico#2063] opened 2018-07-05 15:34 UTC
Hi,
It looks like that there is missing permissions in provided RBAC file.
I am getting such errors (RBAC https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml)

```
2018-07-05 15:12:15.645 [INFO][10] startup.go 251: Early log level set to info
2018-07-05 15:12:15.645 [INFO][10] startup.go 267: Using NODENAME environment for node name
2018-07-05 15:12:15.645 [INFO][10] startup.go 279: Determined node name: kubernetes-master-ubuntu
2018-07-05 15:12:15.648 [INFO][10] startup.go 302: Checking datastore connection
2018-07-05 15:12:15.680 [INFO][10] startup.go 326: Datastore connection verified
2018-07-05 15:12:15.680 [INFO][10] startup.go 99: Datastore is ready
Calico node failed to start
2018-07-05 15:12:15.686 [INFO][10] customresource.go 217: Error getting resource Key=ClusterInformation(default) Name="default" Resource="ClusterInformations" Revision="" error=clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:node:kubernetes-master-ubuntu" cannot get clusterinformations.crd.projectcalico.org at the cluster scope
2018-07-05 15:12:15.686 [ERROR][10] startup.go 106: Unable to ensure datastore is migrated. error=unable to query ClusterInformation to determine Calico version: connection is unauthorized
2018-07-05 15:12:15.686 [WARNING][10] startup.go 1058: Terminating
```

To make it work I have to add:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
```

Why is it needed and not in example?

* Calico version 3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.10.5
* Operating System and version: Ubuntu 16.04 and CentOS 7.5

**Comment by tmjd** [comment] 2018-07-05 18:23
How did you install calico-node? By default it should not be using `system:node:kubernetes-master-ubuntu` for the user.

**Comment by bartlomiejsawicki** [comment] 2018-07-06 06:54
This are my yml:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  namespace: kube-system

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # To enable Typha, set this to "calico-typha" *and* set a non-zero value for Typha replicas
  # below.  We recommend using Typha if you have more than 50 nodes. Above 100 nodes it is
  # essential.
  typha_service_name: "none"
  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": 1500,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "k8s_api_root": "https://kubernetes-master-ubuntu:443",
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        # This, along with the CriticalAddonsOnly toleration below,
        # marks the pod as a critical add-on, ensuring it gets
        # priority scheduling and that its resources are reserved
        # if it ever gets evicted.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: calico-node
      tolerations:
        # Make sure calico/node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
#        - effect: NoExecute
#          operator: Exists
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v3.1.3
          env:
            # Use Kubernetes API as the backing datastore.
            - name: IP_AUTODETECTION_METHOD
              value: "interface=eth0"
            - name: DATASTORE_TYPE
              value: "kubernetes"
            - name: K8S_API_ENDPOINT
              value: "https://kubernetes-master-ubuntu:443"
            - name: K8S_CA_FILE
              value: "/etc/ssl/certs/ca.pem"
            - name: K8S_CERT_FILE
              value: "/etc/ssl/certs/kubernetes.pem"
            - name: K8S_KEY_FILE
              value: "/etc/ssl/certs/kubernetes.key"
            # Enable felix info logging.
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPV6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              value: "1440"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.128.0/18"
            # Enable IPIP
            - name: CALICO_IPV4POOL_IPIP
              value: "Always"
            # Enable IP-in-IP within Felix.
            - name: FELIX_IPINIPENABLED
              value: "true"
            # Typha support: controlled by the ConfigMap.
            - name: FELIX_TYPHAK8SSERVICENAME
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: typha_service_name
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /etc/ssl/certs/
              name: etc-certs-ca
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /var/lib/calico
              name: var-lib-calico
              readOnly: false
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v3.1.3
          command: ["/install-cni.sh"]
          env:
            # Name of the CNI config file to create.
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
            # Set the hostname based on the k8s node name.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: etc-certs-ca
          hostPath:
            path: /etc/ssl/certs/
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-lib-calico
          hostPath:
            path: /var/lib/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d

# Create all the CustomResourceDefinitions needed for
# Calico policy and networking mode.
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
   name: felixconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: FelixConfiguration
    plural: felixconfigurations
    singular: felixconfiguration

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bgppeers.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: BGPPeer
    plural: bgppeers
    singular: bgppeer

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bgpconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: BGPConfiguration
    plural: bgpconfigurations
    singular: bgpconfiguration

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ippools.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: IPPool
    plural: ippools
    singular: ippool

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hostendpoints.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: HostEndpoint
    plural: hostendpoints
    singular: hostendpoint

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterinformations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: ClusterInformation
    plural: clusterinformations
    singular: clusterinformation

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalnetworkpolicies.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: GlobalNetworkPolicy
    plural: globalnetworkpolicies
    singular: globalnetworkpolicy

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalnetworksets.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: GlobalNetworkSet
    plural: globalnetworksets
    singular: globalnetworkset

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkpolicies.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  version: v1
  names:
    kind: NetworkPolicy
    plural: networkpolicies
    singular: networkpolicy



And for RBAC:
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-node
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups: ["extensions"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - watch
      - list
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - globalfelixconfigs
      - felixconfigurations
      - bgppeers
      - globalbgpconfigs
      - bgpconfigurations
      - ippools
      - globalnetworkpolicies
      - globalnetworksets
      - networkpolicies
      - clusterinformations
      - hostendpoints
    verbs:
      - create
      - get
      - list
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system

**Comment by tmjd** [comment] 2018-07-06 14:06
Could you do a describe on the calico-node pod to ensure it is using the specified serviceAccount `calico-node`? Could you verify that the ClusterRoleBinding that the rbac manifest creates does exist?
It seems like something might be missing that is linking the calico-node pod to the proper ClusterRole since it is using an unexpected User.

**Comment by dawidmalina** [comment] 2018-09-05 07:00
@tmjd here is description of the calico pod:

```
Name:               calico-node-49n8t
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               10.1.146.11/10.1.146.11
Start Time:         Wed, 29 Aug 2018 14:36:44 +0000
Labels:             controller-revision-hash=2835060633
                    k8s-app=calico-node
                    pod-template-generation=1
Annotations:        kubernetes.io/psp=privileged
                    scheduler.alpha.kubernetes.io/critical-pod=
Status:             Running
IP:                 10.1.146.11
Controlled By:      DaemonSet/calico-node
Containers:
  calico-node:
    Container ID:   docker://46af20f0ea6cd943e2fcd936e0a84e691fc9f1d0e6a58d5aa87ca9e4c2656b6c
    Image:          docker-repo/infra/docker-calico-node:v3.1.3
    Image ID:       docker-pullable://docker-repo/infra/docker-calico-node@sha256:9871f4dde9eab9fd804b12f3114da36505ff5c220e2323b7434eec24e3b23ac5
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 29 Aug 2018 15:01:38 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 29 Aug 2018 14:55:43 +0000
      Finished:     Wed, 29 Aug 2018 14:56:43 +0000
    Ready:          True
    Restart Count:  10
    Requests:
      cpu:      250m
    Liveness:   http-get http://:9099/liveness delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  http-get http://:9099/readiness delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      IP_AUTODETECTION_METHOD:            interface=eth0
      DATASTORE_TYPE:                     kubernetes
      K8S_API_ENDPOINT:                   https://10.1.147.10:3443
      K8S_CA_FILE:                        /etc/ssl/certs/ca.pem
      K8S_CERT_FILE:                      /etc/ssl/certs/kubernetes.pem
      K8S_KEY_FILE:                       /etc/ssl/certs/kubernetes.key
      FELIX_LOGSEVERITYSCREEN:            info
      CLUSTER_TYPE:                       k8s,bgp
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_IPINIPMTU:                    1440
      WAIT_FOR_DATASTORE:                 true
      CALICO_IPV4POOL_CIDR:               192.171.128.0/18
      CALICO_IPV4POOL_IPIP:               Always
      FELIX_IPINIPENABLED:                true
      FELIX_TYPHAK8SSERVICENAME:          <set to the key 'typha_service_name' of config map 'calico-config'>  Optional: false
      NODENAME:                            (v1:spec.nodeName)
      IP:                                 autodetect
      FELIX_HEALTHENABLED:                true
    Mounts:
      /etc/ssl/certs/ from etc-certs-ca (ro)
      /lib/modules from lib-modules (ro)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-jskvr (ro)
  install-cni:
    Container ID:  docker://93d956075f08377a96c2c101629fe9118b45d9a760f3ac231e48e194e8445b1a
    Image:         docker-repo/infra/docker-calico-cni:v3.1.3
    Image ID:      docker-pullable://docker-repo/infra/docker-calico-cni@sha256:0b4eb34f955f35f8d1b182267f7ae9e2be83ca6fe1b1ade63116125feb8d07b9
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Running
      Started:      Wed, 29 Aug 2018 15:01:39 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 29 Aug 2018 14:36:59 +0000
      Finished:     Wed, 29 Aug 2018 15:00:40 +0000
    Ready:          True
    Restart Count:  1
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-jskvr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  etc-certs-ca:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs/
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  calico-node-token-jskvr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-jskvr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoSchedule
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:          <none>
```

**Comment by dawidmalina** [comment] 2018-09-05 07:10
Indeed it looks like calico-node is configured but because we are using kubelet certificates:
```
            - name: K8S_CERT_FILE
              value: "/etc/ssl/certs/kubernetes.pem"
            - name: K8S_KEY_FILE
              value: "/etc/ssl/certs/kubernetes.key"
```
we are authorizing to kube-api as system:node

Today I've discovered that we are not have one more missing permission:
```
2018-09-05 06:41:22.353 [INFO][56] watchercache.go 188: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/profiles" error=connection is unauthorized: serviceaccounts is forbidden: User "system:node:kubernetes-master-ubuntu" cannot list serviceaccounts at the cluster scope: disabled by feature gate TokenRequest
```

**Comment by dawidmalina** [comment] 2018-09-05 07:38
To fix this quickly i've added this rbac:
```
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - list
      - get
      - watch
```

**Comment by dawidmalina** [comment] 2018-09-05 08:03
When I completely remove:
```
#        - name: K8S_API_ENDPOINT
#        - name: K8S_CA_FILE
#        - name: K8S_CERT_FILE
#        - name: K8S_KEY_FILE
```
from the manifest it is working ok.

How we should configure external ip for api but use token approach?

**Comment by caseydavenport** [comment] 2018-09-12 19:42
@dawidmalina why do you want to use an external IP for the api rather than the in cluster config?

**Comment by dawidmalina** [comment] 2018-09-12 20:33
Hmm. This looks like wrong assumption during configuration implementation. We will try to switch to kubernetes default service. As soon as i confirmed it's working for us i will close this ticket.

**Closed** 2018-12-05 01:42 UTC
Labels: kind/support
