### ISSUE TITLE
Unexpected behavior with networkpolicies and service type loadbalancer

### ISSUE THREAD

**Issue by TheKangaroo** [projectcalico/calico#2635] opened 2019-05-29 12:00 UTC
Unexpected behavior with networkpolicies and service type loadbalancer.

## Expected Behavior
I deployed a app to kubernetes and published it as service type loadbalancer. The service listens on 443 and the pods behind on 6443. Ingress on this service is allowed for anyone.
I expected to 
* deploy a network policy to another namespace which allows egress 443 and can access the external IP on port 443.
* deploy a network policy to a namespace in another cluster which allows egress 443 and can access the external IP between clusters on port 443.

## Current Behavior
To access the app between clusters I can deploy a networkpolicy with egress 443 and everything works as expected.
To access the app from the same cluster I need to deploy a networkpolicy with egress 6443 (the pod port) which is unexpected.

## Possible Solution
I dug a bit into kubernetes iptables rules, and I think the root cause is the KUBE-SERVICES chain in the OUTPUT chain which directly maps the external ip to the internal service ip and then to the pod service ip and the port 443 to the pod port 6443.

## Steps to Reproduce (for bugs)
1.
Deploy a service to a namespace, e.g. an ingress:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 6443
    protocol: TCP    
  selector:
    app: ingress-nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
```
and add the according deployment/pods
2.
Add a NetPol to a diffrent Namespace:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  labels:
    app: myapp
  name: allow-ingress access
  namespace: nottheingressnamespace
spec:
  egress:
  - ports:
    - port: 443 (<- works only if you are in a diffrent cluster,
                 needs to be 6443 for the same cluster)
      protocol: TCP
  podSelector:
    matchLabels:
      app: myapp
  policyTypes:
  - Egress
```
3.
run pod with label `app: myapp` and try to access the ingress from within the pod.

## Context
Maybe this is the expected behavior, but it was quite surprising since we accessed the service via an external IP and the behavior is different from different clusters.

## Your Environment

* Calico version v3.4.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.13.4
* Operating System and version: CoreOS 1855.5.0

**Comment by caseydavenport** [comment] 2019-06-03 20:53
> I dug a bit into kubernetes iptables rules, and I think the root cause is the KUBE-SERVICES chain in the OUTPUT chain which directly maps the external ip to the internal service ip and then to the pod service ip and the port 443 to the pod port 6443.

This sounds right - the kube-proxy short-circuits external IPs in this way if it knows the traffic is directed at a service within the cluster. It's potentially the kube-proxy overstepping its bounds... but that's the way it is written today.

Egress policy is necessarily defined in terms of what the traffic looks like after it has traversed kube-proxy (e.g., podSelector not serviceSelector), so in this case I think Calico is doing the right thing, while the kube-proxy is trying to be extra clever and thus causing some unexpected behavior.

Going to close this since I think it's an issue with Kubernetes, not with Calico, but it might be worth raising an issue against Kubernetes since it's not obvious to me that what the kube-proxy is doing is desirable for most people. Thanks for the investigation!

**Closed by caseydavenport** 2019-06-03 20:53 UTC

**Comment by TheKangaroo** [comment] 2019-06-05 11:36
Thank you for the confirmation of the theory ;) I opened the issue over at kubernetes project.
