### ISSUE TITLE
How to configure the route-reflector(s) to forward network traffic?

### ISSUE THREAD

**Issue by fengxsong** [projectcalico/calico#2473] opened 2019-03-07 08:16 UTC
## Expected Behavior

nodes outside the cluster  can directly ping pods in the k8s cluster.

## Steps to Reproduce (for bugs???)

here is my test environment configuration:

I had follow the [instruction](https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/calico) to setup a k8s cluster with 3 nodes

```yaml
items:
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    annotations:
      projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/hostname":"k8stest01","node-role.kubernetes.io/master":""}'
    creationTimestamp: 2019-03-05T10:08:46Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: k8stest01
      node-role.kubernetes.io/master: ""
    name: k8stest01
    resourceVersion: "230859"
    uid: aa131975-3f2e-11e9-bb22-1c1b0dcb5575
  spec:
    bgp:
      ipv4Address: 172.20.10.93/24
      ipv4IPIPTunnelAddr: 172.19.0.1
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    annotations:
      projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/hostname":"k8stest02"}'
    creationTimestamp: 2019-03-05T10:09:08Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: k8stest02
      route-reflector: "true" # ---> label
    name: k8stest02
    resourceVersion: "230867"
    uid: b73c9b25-3f2e-11e9-bb22-1c1b0dcb5575
  spec:
    bgp:
      ipv4Address: 172.20.10.126/24
      ipv4IPIPTunnelAddr: 172.19.1.1
      routeReflectorClusterID: 172.20.10.1 # ---> configure this node as a reflector
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    annotations:
      projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/hostname":"k8stest03"}'
    creationTimestamp: 2019-03-05T10:13:30Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: k8stest03
    name: k8stest03
    resourceVersion: "230857"
    uid: 5325482b-3f2f-11e9-bb22-1c1b0dcb5575
  spec:
    bgp:
      ipv4Address: 172.20.10.92/24
      ipv4IPIPTunnelAddr: 172.19.2.1
```

before configuring in-cluster route reflector, of course, I turned off the `nodeToNodeMeshEnabled`. Then i created a (global) BGPPeer and an external rr peer config

```yaml
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: rr-mesh-all
spec:
  nodeSelector: all()
  peerSelector: has(route-reflector)
---
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: reflector-to-external
spec:
  asNumber: 63401
  nodeSelector: has(route-reflector)
  peerIP: 172.20.10.1 # ---> out-of-cluster network device.
```

in-cluster traffic works as expect.

```bash
ppops@k8stest02:~$ sudo calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+---------------+-------+----------+-------------+
| PEER ADDRESS |   PEER TYPE   | STATE |  SINCE   |    INFO     |
+--------------+---------------+-------+----------+-------------+
| 172.20.10.92 | node specific | up    | 04:00:32 | Established |
| 172.20.10.93 | node specific | up    | 04:00:32 | Established |
| 172.20.10.1  | node specific | up    | 04:01:39 | Established |
+--------------+---------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

ppops@k8stest02:~$ ip route
default via 172.20.10.1 dev enp2s0 onlink
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
172.19.0.0/24 via 172.20.10.93 dev enp2s0  proto bird
blackhole 172.19.1.0/24  proto bird
172.19.1.11 dev calid32461640eb  scope link
172.19.1.13 dev cali12f93137b99  scope link
172.19.1.15 dev cali15b04fc0017  scope link
172.19.2.0/24 via 172.20.10.92 dev enp2s0  proto bird
172.20.10.0/24 dev enp2s0  proto kernel  scope link  src 172.20.10.126
172.20.16.0/24 via 172.20.10.1 dev enp2s0  proto bird
192.168.120.0/24 via 172.20.10.1 dev enp2s0  proto bird
ppops@k8stest02:~$ ping -c2 172.19.2.3
PING 172.19.2.3 (172.19.2.3) 56(84) bytes of data.
64 bytes from 172.19.2.3: icmp_seq=1 ttl=63 time=0.380 ms
64 bytes from 172.19.2.3: icmp_seq=2 ttl=63 time=0.194 ms

--- 172.19.2.3 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.194/0.287/0.380/0.093 ms
ppops@k8stest02:~$ ping -c2 172.19.0.12
PING 172.19.0.12 (172.19.0.12) 56(84) bytes of data.
64 bytes from 172.19.0.12: icmp_seq=1 ttl=63 time=0.267 ms
64 bytes from 172.19.0.12: icmp_seq=2 ttl=63 time=0.390 ms

--- 172.19.0.12 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.267/0.328/0.390/0.064 ms
```

bgp route table shown at L3 device.

![image](https://user-images.githubusercontent.com/7008971/53942002-a0791b00-40f4-11e9-81c4-ea08cbacd4dc.png)

but from my laptop, can only reach to subnet 172.19.1.0/24. It seems that the router reflector did not forward traffic to other subnets.

```bash
➜ traceroute 172.19.1.11
traceroute to 172.19.1.11 (172.19.1.11), 64 hops max, 52 byte packets
 1  192.168.120.1 (192.168.120.1)  2.744 ms  1.925 ms  2.116 ms
 2  10.1.1.1 (10.1.1.1)  2.222 ms  1.143 ms  1.677 ms
 3  * * *
 4  10.1.1.36 (10.1.1.36)  2.196 ms  1.844 ms  1.900 ms
 5  k8stest02 (172.20.10.126)  1.159 ms  1.168 ms  1.013 ms
 6  172.19.1.11 (172.19.1.11)  1.038 ms  1.200 ms  1.043 ms

~ at ☸️ test took 15s
➜ traceroute 172.19.2.3
traceroute to 172.19.2.3 (172.19.2.3), 64 hops max, 52 byte packets
 1  192.168.120.1 (192.168.120.1)  4.289 ms  2.037 ms  1.990 ms
 2  10.1.1.1 (10.1.1.1)  1.728 ms  1.651 ms  1.064 ms
 3  * * *
 4  10.1.1.36 (10.1.1.36)  2.046 ms  2.243 ms  2.861 ms
 5  k8stest02 (172.20.10.126)  1.070 ms  0.863 ms  0.912 ms
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * *
```

## Your Environment
* Calico version: 3.5.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: ubuntu 16.04.5 / Linux 4.4.0-87-generic

**Comment by caseydavenport** [comment] 2019-03-13 22:23
>  It seems that the router reflector did not forward traffic to other subnets.

I wouldn't expect the route relfector to be in the data path itself. It looks like the RR is reflecting the routes to the L3 device, but if traffic isn't working it's likely due to something else in the data path.

The RR won't put itself as the next hop, so data won't go through the RR itself.

**Comment by caseydavenport** [comment] 2019-03-13 22:24
But, looking at your config it _does_ seem to be setting itself as the next hop, which isn't what I'd expect.

**Comment by fengxsong** [comment] 2019-03-14 02:16
@caseydavenport Sorry, I'm not a network guy

Is there any suggestions for solving this problem :-(

**Comment by reinstall** [comment] 2019-03-29 08:10
I had a similar problem and solved it like that:
1. Allow forward traffic on route reflector nodes. 
I wrote a more complicated rules, but it may be used as starting point.
```
$ iptables -P FORWARD ACCEPT
```

2. Turn off the reverse path filter. 
```
#!/bin/bash
for DEV in /proc/sys/net/ipv4/conf/*/rp_filter
do
    echo 0 > $DEV
done
```

Unfortunately I could not find a calico native way to add forward rules :-(

**Comment by fengxsong** [comment] 2019-04-02 09:57
> I had a similar problem and solved it like that.
> 
> 1. Turn off the reverse path filter:
> 
> ```
> #!/bin/bash
> for DEV in /proc/sys/net/ipv4/conf/*/rp_filter
> do
>     echo 0 > $DEV
> done
> ```
> 1. Add HostEndpoint object to nodes with route reflector:
> 
> ```
> apiVersion: projectcalico.org/v3
> kind: HostEndpoint
> metadata:
>   name: rr-node-01
> spec:
>   interfaceName: eth0
>   node: rr-node-01
>   expectedIPs: ["10.10.0.1"]
> ```
> 1. Add GlobalNetworkPolicy object with option applyOnForward like this:
> 
> ```
> apiVersion: projectcalico.org/v3
> kind: GlobalNetworkPolicy
> metadata:
>   name: allow-all
> spec:
>   selector: all()
>   order: 0
>   types:
>     - Ingress
>     - Egress
>   ingress:
>   - action: Allow
>   egress:
>   - action: Allow
>   applyOnForward: true
> ```

From my test results, it seems that the first step is unnecessary.

**Comment by reinstall** [comment] 2019-04-02 10:03
> From my test results, it seems that the first step is unnecessary.

Yes, it is necessary only when asymmetric routing.

**Comment by mritd** [comment] 2019-06-18 06:22
@reinstall 
When I use `in-cluster route reflectors` how to configure? 

I tried to forward external traffic to the rr node, but the rr node does not seem to continue forwarding to pod ip

**Comment by fengxsong** [comment] 2019-07-10 11:48
@mritd Have you solved this problem yet

**Comment by fengxsong** [comment] 2019-07-10 12:15
Currently I have some other issues.
network between pods is normal, TCP/UDP/...  services can be accessed normally.

but, traffic from outside the cluster, pods on worker (which is the route reflector) are works fine, But on other nodes, services other than TCP are available.

![image](https://user-images.githubusercontent.com/7008971/60967875-52984c00-a34e-11e9-9f80-c4cd41ac3cad.png)

![image](https://user-images.githubusercontent.com/7008971/60968319-57a9cb00-a34f-11e9-95fe-c548c3d09973.png)

**Comment by mritd** [comment] 2019-07-10 13:14
@fengxsong My problem is caused by the IPIP protocol. I have solved this problem at present; in the detailed process, I recorded the blog, the blog is Chinese.

**Comment by tony-liuliu** [comment] 2019-10-26 13:13
@fengxsong Is your problem solved? I have the same problem as you. At present, it is determined that the third packet (ACK) of TCP's three-time handshake packet has not been forwarded to other nodes after it reaches the route reflector node.The reason is unknown.

Client outside the k8s cluster，tcpdump：
![image](https://user-images.githubusercontent.com/50659754/67619985-9008e280-f834-11e9-97bd-3e21c8b9a549.png)

route reflector node tcpdump：
![image](https://user-images.githubusercontent.com/50659754/67619977-6485f800-f834-11e9-84eb-c91ef5289b92.png)

10.244.47.75 node tcpdump：
![image](https://user-images.githubusercontent.com/50659754/67619993-b62e8280-f834-11e9-8723-8b31330afe09.png)

calico v3.4.0
[root@prod-k8s-11 calico]# calicoctl get ipPool -o yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: 2019-06-13T07:39:12Z
    name: default-ipv4-ippool
    resourceVersion: "1156"
    uid: 569840d5-8dae-11e9-a62a-6c92bf2a45da
  spec:
    blockSize: 26
    cidr: 10.244.0.0/16
    ipipMode: Never
    natOutgoing: true
kind: IPPoolList
metadata:
  resourceVersion: "30031014"

All my k8s node Layer 2 networks can communicate.

**Comment by fengxsong** [comment] 2019-10-27 01:17
@tony-liuliu No, can not figure it out.

**Comment by zhangxpp** [comment] 2020-03-29 04:12
@tony-liuliu @fengxsong Have you fixed this problem?

**Comment by zhangxpp** [comment] 2020-03-29 13:51
@tony-liuliu @fengxsong 

I encountered one problem is that router reflector node is not able to forward traffic from outside k8s cluster to Pod IP&Port,  telnet pod-ip port is working, but curl http://<pod-ip>:<port> from outside the cluster. 

This problem is fixed by adding iptables forward rules as below:
iptables -I FORWARD -s 10.100.0.0/16 -j ACCEPT

10.100.0.0/16 is outside k8s cluster.

**Comment by fengxsong** [comment] 2020-03-30 02:29
@zhangxpp thanks, i'll give it a shot.🚀

**Closed** 2020-06-04 16:15 UTC
Labels: kind/support
