### ISSUE TITLE
Why calico policy is ading "default" in actual name as default.<policy_name>? (even if name space is not default)

### ISSUE THREAD

**Issue by yogeshelke** [projectcalico/calico#9642] opened 2024-12-23 19:23 UTC
### Discussed in https://github.com/orgs/projectcalico/discussions/9641

<div type='discussions-op-text'>

<sup>Originally posted by **yogeshelke** December 23, 2024</sup>
Why calico policy is adding "default" in actual name field of policy created in cluster as default.<policy_name>? (even if name space is not default, created policy not for default namespace).

Is this the bug?

**My input policy:**

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: block-traffic-from-context-ns
  namespace: ops-infrastructure
spec:
  selector: all()
  types:
    - Ingress
  ingress:
    - action: Deny
      source:
        namespaceSelector: "namespace-type == 'context'"
    - action: Allow
```

**Actual policy created by calico api:**

```
│ apiVersion: crd.projectcalico.org/v1                                                                                                                                                    
│ kind: NetworkPolicy                                                                                                                                                                     
│ metadata:                                                                                                                                                                               
│   annotations:                                                                                                                                                                          
│     projectcalico.org/metadata: '{"creationTimestamp":"2024-12-23T19:12:07Z","managedFields":[{"manager":"Terraform","operation":"Apply","apiVersion":"projectcalico.org/v3","time":"20 │
│ 24-12-23T19:12:07Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:ingress":{},"f:selector":{},"f:types":{}}}}]}'                                                                     │
│   creationTimestamp: "2024-12-23T19:12:07Z"                                                                                                                                             
│   generation: 1                                                                                                                                                                         
│   name: default.block-traffic-from-context-ns                                                                                                                                          
│   namespace: ops-ingress                                                                                                                                                                
│   resourceVersion: "633102131"                                                                                                                                                          
│   uid: 54a0ca4a-19b7-42d3-b247-a98553fb35dc                                                                                                                                             
│ spec:                                                                                                                                                                                   
│   ingress:                                                                                                                                                                              
│   - action: Deny                                                                                                                                                                        
│     destination: {}                                                                                                                                                                     
│     source:                                                                                                                                                                             
│       namespaceSelector: namespace-type == 'context'                                                                                                                                    
│   - action: Allow                                                                                                                                                                       
│     destination: {}                                                                                                                                                                     
│     source: {}                                                                                                                                                                          
│   selector: all()                                                                                                                                                                       
│   types:                                                                                                                                                                                
│   - Ingress                                                                                                                                                                             
                        
```                                                                                                                                                                 
</div>

**Comment by caseydavenport** [comment] 2024-12-30 16:32
Calico has always prepended the underlying v1 CRDs with "default" - it reprents the "tier" rather than the policy.

In v3.29.0, we unknowingly made a breaking change to the v3 API which started showing this value - it's tracked here: https://github.com/projectcalico/calico/issues/9437

We hope to fix this in the next patch release.

I'm going to close this as a duplicate of the other issue.

**Closed by caseydavenport** 2024-12-30 16:32 UTC
