### ISSUE TITLE
Garbage collector sync timeout issue after upgrading to Calico 3.26

### ISSUE THREAD

**Issue by aminvsf** [projectcalico/calico#7777] opened 2023-06-10 08:55 UTC
Hello everyone.
I have a K8s cluster operating using 4 Ubuntu 20.04 instances with sufficient CPU, Disk and RAM. I am using Kubernetes 1.25.10 and Calico 3.25 for networking. Suddenly I decided to upgrade to Calico 3.26. After doing that, I realized that by deleting deployments, their associated replicasets and pods aren't deleted. Then I checked my kube-controller-manager logs and saw the following error:
`
E0609 18:53:17.630149       1 shared_informer.go:255] unable to sync caches for garbage collector
E0609 18:53:17.630185       1 garbagecollector.go:250] timed out waiting for dependency graph builder sync during GC sync (attempt 66)
`
At first I thought there was a problem with my disk performance. I tested it and since it's a high performance SSD, there was no problem with it. Then I roll backed my Calico to 3.25 and everything started to work again and garbage collector cache also got synced.
I also created a new cluster from scratch using the same K8s version and Calico 3.26 and saw the same problem for garbage collector again.

## Expected Behavior

Calico 3.26 should not prevent garbage collector cache from syncing.

## Current Behavior

Calico 3.26 stops garbage collector cache from syncing.

## Possible Solution

Unfortunately I've got no idea about a solution for it.

## Steps to Reproduce (for bugs)

1. Create an on-premise K8s cluster using Ubuntu 20.04 instances.
2. Deploy Calico 3.26 using operator method described in the documentation.
3. Create a test deployment like Nginx or something and verify that its associated pods and replicasets are running.
4. Delete the deployment and verify that its related pods aren't deleted.
5. Check kube-controller-manager logs and verify that garbage collector cache encounters a timeout error while trying to sync.

## Context

Affected my garbage collector so I every time I wanted to delete a deployment, I had to delete its related replicasets and pods manually.

## Your Environment

* Calico version: 3.26
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.25.10
* Operating System and version: Ubuntu 20.04

**Comment by mazdakn** [comment] 2023-06-13 16:44
Closing since it's duplicate of this one: https://github.com/projectcalico/calico/issues/7598

**Closed by mazdakn** 2023-06-13 16:44 UTC
