### ISSUE TITLE
node_mesh set to enable: false by default in kubernetes  cluster on Openstack

### ISSUE THREAD

**Issue by lcnsir** [projectcalico/calico#1081] opened 2017-09-05 05:34 UTC
When I deploy calico 2.4.1 in kubernetes cluster "node_mesh" is set to false which make the calico bgp network lose efficacy, we using the yaml file from
https://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/calico.yaml
## Expected Behavior

The default value should be "{\"enabled\":true}" in etcd and node-to-mesh should be enabled by default.
## Current Behavior

The default value is "{\"enabled\":false}" in etcd and node-to-mesh is off by default.
## Possible Solution
Using calico ctl to set the node_mesh

`calicoctl config set nodeToNodeMesh on
`
Can anyone tell me when the node_mesh in etcd will be set to false by default?

## Steps to Reproduce (for bugs)

1. Set Openstack cluster
2. Deploy k8s cluster in Openstack
3. Deploy calico by https://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/calico.yaml
4. the ip route is not set, since the node_mesh is not enabled by default.

## Your Environment

* Calico version
   2.4.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
  kubernetes 2.7.3
* Operating System and version:
   ubuntu 16.04

**Comment by lcnsir** [comment] 2017-09-05 08:46
Can anyone tell me when the node_mesh in etcd will be set to false by default?

**Comment by tmjd** [comment] 2017-09-05 17:21
I am not aware of any instances where node_mesh is disabled by default, I do not think there are any flags/settings that would allow you to disable the mesh.  The only way I could see this happening is if you are using an etcd cluster where previously Calico was set up with node-to-node mesh disabled, could that be happening in your setup?

**Comment by lcnsir** [comment] 2017-09-06 01:22
@tmjd, I create a fresh etcd, which just  have k8s data in it, 
And do you know, which component in calico node will set the node_mesh value in etcd when boot calico node deamonset in k8s cluster,   felix ? libnetwork-plugin?

Thanks for your help

**Comment by lcnsir** [comment] 2017-09-06 01:25
And this commit https://github.com/projectcalico/libcalico-go/pull/468 will lead to this issue on some conditions ?

**Comment by neiljerram** [comment] 2017-09-07 08:39
@ozdanborne Think the `orchestrator/openstack` label is wrong here; IIUC, the OpenStack participation here is incidental - just as a lower level networking fabric - and Calico is not involved at that level.  (And also, Calico for OpenStack does not use calicoctl or YAMLs or nodeToNodeMesh.)

On the substance, it's not clear to me if the problem is just in the default YAML that we recommend people to use, or if there is also a coding problem somewhere.  @lcnsir @tmjd Is that clear to you?

**Comment by lcnsir** [comment] 2017-09-08 02:15
@neiljerram yes, my env is that deploy k8s cluster on Openstack VMs, and create calico with the default YAML on k8s cluster.
And find that the value "nodeToNodeMesh" is off by default. which should be "on" by default.
Can you also tell me which component in calico node will set the value in etcd when it start,  felix ? libnetwork-plugin? or confd ?

**Comment by neiljerram** [comment] 2017-09-08 08:48
@lcnsir I've been reviewing the code that I would expect to be relevant here: felix, libcalico-go and calico-node; but unfortunately I cannot see how nodeToNodeMesh is being defaulted to false.  I will need to try to reproduce your scenario, in order to understand this further.

**Comment by tmjd** [comment] 2017-09-18 14:47
@lcnsir You asked what component should be setting the nodeToNodeMesh. calico_node startup should be setting the nodeToNodeMesh default to on.  Here is where it happens https://github.com/projectcalico/calico/blob/master/calico_node/startup/startup.go#L803 using the value from https://github.com/projectcalico/libcalico-go/blob/master/lib/client/config.go#L50.

**Comment by ozdanborne** [comment] 2018-02-23 19:12
This issue's been open for quite some time, so I'm going to close it. @lcnsir please reopen if you still need assistance.

**Closed by ozdanborne** 2018-02-23 19:12 UTC
Labels: kind/support, orchestrator/openstack
