### ISSUE TITLE
Calico Node Pods in CrashLoopBackOff

### ISSUE THREAD

**Issue by brahim-slimani** [projectcalico/calico#7966] opened 2023-08-28 16:35 UTC
The calico-node pod(s) are in CrashLoopBackOff state and/or constantly restarting.

![image](https://github.com/projectcalico/calico/assets/36894964/fdb3f1ce-147b-4d84-9d33-1251523391af)

The pod log (via kubectl logs) for the calico-node pod(s) shows the following error =>

[ERROR][68] confd/discovery.go 126: Unable to get service endpoints from Kubernetes. error=endpoints "cni-endpoints" not found

**Environment**

- CentOS 7 Linux based platform
- Calico v3.26.1
- Kubernetes v1.27.1

**Comment by 8Iue** [comment] 2023-08-30 17:21
Possibly this is a duplicate of my already open issue here: https://github.com/projectcalico/calico/issues/7951

**Comment by caseydavenport** [comment] 2023-09-27 20:53
Did you make any progress on this? 

Looks like a problem trying to connect to Typha. Are you running Typha in your cluster? What is the full log output from those crashing pods?

**Closed** 2023-12-12 20:28 UTC
Labels: kind/support
