### ISSUE TITLE
calico should remove the virtual interface when failing to enter pod netns in cmdDel. 

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#7554] opened 2023-04-14 10:00 UTC
## Expected Behavior

calico should remove the virtual interface in the host side when failing to enter pod netns in cmdDel. 

## Current Behavior

```golan
diff --git a/cni-plugin/pkg/dataplane/linux/dataplane_linux.go b/cni-plugin/pkg/dataplane/linux/dataplane_linux.go
index 3f9b89655..c6c2154f3 100644
--- a/cni-plugin/pkg/dataplane/linux/dataplane_linux.go
+++ b/cni-plugin/pkg/dataplane/linux/dataplane_linux.go
@@ -17,6 +17,7 @@ package linux
 import (
        "context"
        "fmt"
+       k8sconversion "github.com/projectcalico/calico/libcalico-go/lib/backend/k8s/conversion"
        "io"
        "net"
        "os"
@@ -551,6 +552,13 @@ func (d *linuxDataplane) CleanUpNamespace(args *skel.CmdArgs) error {
                if nsErr != nil {
                        if _, ok := nsErr.(ns.NSPathNotExistErr); ok {
                                logCtx.Info("Workload's netns already gone.  Nothing to do.")
+                               hostVethName := k8sconversion.NewConverter().VethNameForWorkload(podNs,podName)
+                               link,err := netlink.LinkByName(hostVethName)
+                               if err != nil {
+                                       d.logger.WithField("virtual interface",hostVethName).Errorf("LinktByName return error: %v",err)
+                               } else {
+                                       d.logger.WithField("virtual interface",hostVethName).Infof("found interface %s exists",link.Attrs().Name)
+                               }
                                return nil
                        }
                        logCtx.WithError(nsErr).Error("Failed to enter workloads netns.")

```

```
2023-04-14 16:15:44.944 [INFO][2138204] dataplane_linux.go 504: Deleting workload's device in netns. ContainerID="75d3f57abfcc79c2985911f4426137f01a64fc89d033ef3d95fedd2dfe8b8a10" iface="eth0" netns="/proc/2137890/ns/net"
2023-04-14 16:15:44.944 [INFO][2138204] dataplane_linux.go 515: Entered netns, deleting veth. ContainerID="75d3f57abfcc79c2985911f4426137f01a64fc89d033ef3d95fedd2dfe8b8a10" iface="eth0" netns="/proc/2137890/ns/net"
2023-04-14 16:15:45.454 [INFO][2138204] dataplane_linux.go 542: Workload's veth was already gone.  Nothing to do. ContainerID="75d3f57abfcc79c2985911f4426137f01a64fc89d033ef3d95fedd2dfe8b8a10" iface="eth0" netns="/proc/2137890/ns/net"
2023-04-14 16:15:45.517 [INFO][2138204] dataplane_linux.go 558: found interface cali757eb1af9e1 exists ContainerID="75d3f57abfcc79c2985911f4426137f01a64fc89d033ef3d95fedd2dfe8b8a10" virtual interface="cali757eb1af9e1"
2023-04-14 16:15:45.832 [INFO][2138204] k8s.go 583: Releasing IP address(es) ContainerID="75d3f57abfcc79c2985911f4426137f01a64fc89d033ef3d95fedd2dfe8b8a10"
2023-04-14 16:15:46.366 [INFO][2138204] utils.go 196: Calico CNI releasing IP address ContainerID="75d3f57abfcc79c2985911f4426137f01a64fc89d033ef3d95fedd2dfe8b8a10"
```

In my local, I created a job, and the job created 50+ pods, When the status of the pod changed to Completed, I found that some virtual NICs were not recycled in time.  as shown above.

There is a case when the netns file does not exist, but the pod's netns are not deleted. I'm not sure why this happens,  A similar problem was encountered in our customer environment. It resulted in a large number of virtual NICs on the host and a very high CPU on the calico-node.

In this case, should we actively delete the virtual NIC on the host side？ 

## Steps to Reproduce (for bugs)

> container runtime is docker 

1. create a job, and set parallelism to `40`
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
  parallelism: 50
```
2. Insert debug code in calico cni-plugin to check if the virtual NIC on the host side exists when netns is inaccessible
3. Wait for state of all pods to change to Completed, Check out calico cni's log(`/var/log/calico/cni/cni.log`)

## Context

https://github.com/projectcalico/calico/pull/6356

## Your Environment

* Calico version
```
root@controller:~# calicoctl version
Client Version:    v3.23.3
Git commit:        3a3559be1
Cluster Version:   v3.23.3
Cluster Type:      k8s,kdd,kubespray,kubeadm
```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```shell
root@controller:~# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0
```
* Operating System and version:
```
root@controller:~# uname -a
Linux controller 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your project (optional):

**Comment by czybjtu** [comment] 2023-04-18 02:16
It would be better if you could provide the k8s and calico version information.

**Comment by cyclinder** [comment] 2023-04-18 06:26
We hit this issue in our product, and the version of the production is old, k8s version is 1.18, calico version is 1.16.

But I reproduced the problem on new version of k8s(1.24.7) and calico version(v3.24.5), so I opened this issue.

**Comment by cyclinder** [comment] 2023-04-18 06:28
It is worth noting that this problem does not happen if containerd is used as a container runtime, only happened in docker as container runtime

**Comment by mazdakn** [comment] 2023-04-18 16:38
@cyclinder please fill in all the details asked in the template so we can help. Cluster information and the steps for reproducing the issue are important.

**Comment by fasaxc** [comment] 2023-04-18 16:58
I thought the veth was auto-deleted when the namespace it was in was deleted.  ISTR there is a reason for deleting hte veth from within the netns: it makes sure that we delete the right veth if the pod is being restarted or something like that.

**Comment by cyclinder** [comment] 2023-04-19 02:16
@mazdakn Thanks, updated.

**Comment by cyclinder** [comment] 2023-04-19 02:28
> I thought the veth was auto-deleted when the namespace it was in was deleted.

Yes, I think so too, I don't found veth residue in my local. In a production environment, our customer creates AI pods at regular intervals of 1 minute via several cron jobs, After a period of time, a large number of veth residues were found on the node. This causes the calico node's cpu usage to reach over 90%. 

> ISTR there is a reason for deleting hte veth from within the netns: it makes sure that we delete the right veth if the pod is being restarted or something like that.

In scenarios with high concurrency, it is indeed possible to cause a large number of veth residues, and it is not clear what the root cause is. Should we remove the veth device on the host side when netns is inaccessible?

**Comment by czybjtu** [comment] 2023-04-19 02:52
> This causes the calico node's cpu usage to reach over 90%.

Why does the residual veths cause high CPU usage? 

> Should we remove the veth device on the host side when netns is inaccessible?

I think so. These veths have become dirty data when the netns was deleted.

containerd will be responsble for the lifecyle of pod's netns if your runtime is containerd.

I think it's better to use containerd instead of docker if your k8s version is higher than 1.24. Your problem may be caused by compatibility issues with Docker, I guess.

**Comment by cyclinder** [comment] 2023-04-19 06:19
> Why does the residual veths cause high CPU usage?

We found more than 1000 veth devices in the host, but in fact, only 100+ pods exist in the host.  I saw logs of calico-node and found calico-node always checking veth interface...

```
```
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali8f52b63ed52"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali33b8dac7e81"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali03b5de578f2"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali09b03079c56"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali01ada96bea7"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali40325d8945d"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="calie95891e0b77"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali3fd3f9001a9"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali3317d7aa695"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali9383850f54b"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="calib6ecd0f1940"
2023-03-15 11:15:20.826 [INFO][86] monitor-addresses/reachaddr.go 55: Checking interface CIDRs Name="cali55fd3e317d7"
```
```

When we clean these dirty veth devices manually, the cpu usage is normal

**Comment by fasaxc** [comment] 2023-04-19 09:45
FWIW, Calico v3.25.1 should fix the high CPU usage.  Then the question is: does Calico get told about the deletion of the pod?  Is kubelet issuing a CNI DEL operation to Calico?  If not, then it's a kubelet/CRI/dockershim bug.  Sicne this seems to eb fixed in containerd and dockershim is deprecated, it seems likely to be a k8s/dockershim bug, not telling Calico to clean up?

**Comment by cyclinder** [comment] 2023-04-21 02:18
> FWIW, Calico v3.25.1 should fix the high CPU usage. 

Could you tell me which one PR fixed it? 

> Then the question is: does Calico get told about the deletion of the pod? Is kubelet issuing a CNI DEL operation to Calico?

Yes, kubelet has told calico about the deletion of the pod,  but calico failed to enter pod's netns, so it failed. So the veth on the node cannot be deleted. It looks like the deletion of netns and the deletion of /proc/<sandbox pid>/net/ns files are not synchronized, causing this problem.


 I know the veth was auto-deleted when the namespace it was in was deleted, but you can't be sure when namespace is actually deleted, it could be very fast or very slow. In our production (high concurrency), the namespace deletion took longer, so it resulted in veth residuals.

So I think we should remove the veth on host side when netns  path is unreachable.

**Closed** 2023-12-12 20:09 UTC
Labels: kind/support
