### ISSUE TITLE
BGP advertising doesn't honor externalTrafficPolicy Local for LoadBalancer services

### ISSUE THREAD

**Issue by cubagabriel** [projectcalico/calico#6074] opened 2022-05-11 18:42 UTC
For service type `LoadBalancer` and `externalTrafficPolicy: Local`, Calico will advertise routes from all nodes, regardless of whether valid endpoints exist.

A calico-node running in an host which has endpoints for that service will learn the endpoint IP address:

```
ubuntu@deployer:~$ klo -n kube-system calico-node-nsjfq  | grep 'default/my-service'
2022-05-03 22:16:24.089 [DEBUG][78] confd/routes.go 171: getEndpointsForService: service for endpoint not found, passing key="default/my-service"
2022-05-03 22:16:24.135 [DEBUG][78] confd/routes.go 171: getEndpointsForService: service for endpoint not found, passing key="default/my-service"
2022-05-03 22:16:24.200 [DEBUG][78] confd/routes.go 417: Advertising local service svc="default/my-service"
2022-05-03 22:16:24.200 [DEBUG][78] confd/routes.go 206: Checking routes for service advertise=true svc="default/my-service"
2022-05-03 22:16:24.200 [DEBUG][78] confd/routes.go 294: Setting routes for key key="default/my-service" routes=[]string{"10.100.19.72/32"}
```

On the other hand, a calico-node that has no endpoints for that service will recognize it correctly, as seen in the logs:

```
ubuntu@deployer:~$ kubectl logs -n kube-system calico-node-zhl2r  | grep 'default/my-service'
2022-05-03 22:16:24.088 [DEBUG][69] confd/routes.go 171: getEndpointsForService: service for endpoint not found, passing key="default/my-service"
2022-05-03 22:16:24.122 [DEBUG][69] confd/routes.go 171: getEndpointsForService: service for endpoint not found, passing key="default/my-service"
2022-05-03 22:16:24.190 [DEBUG][69] confd/routes.go 422: Skipping service with no local endpoints svc="default/my-service"
2022-05-03 22:16:24.190 [DEBUG][69] confd/routes.go 206: Checking routes for service advertise=false svc="default/my-service"

```

However, both calico-nodes have the same bird static configuration so both of them advertise all the prefixes:

```
[root@node4 /]# cat /etc/calico/confd/config/bird_aggr.cfg 
# Generated by confd

protocol static {
   # IP blocks for this host.
   route 10.233.111.0/24 blackhole;
   # Static routes.
   route 10.100.18.237/32 blackhole;
   route 10.100.18.40/32 blackhole;
   route 10.100.19.72/32 blackhole;
}
```

Peer receives routes from all nodes:
```
10.100.19.72/32      unicast [Node_10_0_1_74 18:28:59.532 from 10.0.1.74] * (100/?) [i]
	via 10.100.16.1 on ens3
                     unicast [Node_10_0_1_130 18:36:22.534 from 10.0.1.130] (100/?) [i]
	via 10.100.16.1 on ens3
                     unicast [Node_10_0_1_254 18:28:59.883 from 10.0.1.254] (100/?) [i]
	via 10.100.16.1 on ens3
```

## Expected Behavior
Only one calico-node should advertise the route so that trafficPolicy is honored, as the [documentation](https://projectcalico.docs.tigera.io/archive/v3.21/networking/advertise-service-ips) does not state otherwise.

## Current Behavior
All calico-nodes are advertising the routes, regarding if they have a valid endpoint for the service, similar to `externalTrafficPolicy: Cluster`

## Steps to Reproduce (for bugs)
1. Setup BGP Service advertising according to documentation.
2. Create a simple 1-pod deployment.
3. Create a service of type `LoadBalancer` and externalTrafficPolicy `Local`:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  externalTrafficPolicy: Local
  selector:
    app: nginx
  ports:
    - protocol: UDP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.100.19.72
```

5. Check the received routes on the BGP peer

## Your Environment
* Calico version: 3.21.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.21.1
* Operating System and version: Ubuntu 20.04

**Comment by mgleung** [comment] 2022-05-17 16:53
Hi @cubagabriel , thanks for raising this. I was wondering if you could share your BGP peers and BGP configuration as well? This definitely seems like a bug, but I want to make sure that I completely understand your setup so I can figure out how we got here in the first place.

**Comment by cubagabriel** [comment] 2022-05-24 13:36
Hi @mgleung , I tried different configurations but for reference consider the following:

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 65001
  serviceLoadBalancerIPs:
   - cidr: 10.100.18.40/32
   - cidr: 10.100.19.72/32
   - cidr: 10.100.18.237/32

apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer-global
spec:
  keepOriginalNextHop: true
  peerIP: 10.100.18.90
  asNumber: 65002

```
I even tried setting a route reflector topology and disabling full mesh, with the same result.

**Comment by mtryfoss** [comment] 2022-06-24 10:40
I did investigate a bit around this myself. It seems to be semi-working when pods moves around.
My test case:
Daemonset running on three workers with a service using externalTrafficPolicy: Local
Routes are advertised from all three, as expected.

When doing a change causing the pod to stop on one of the workers, the route no longer advertised from that worker.
And if you're restarting the pod, it's being advertised again.

The problem seems to be when applying a new BGP configuration to an existing service, it gets advertised from all workers.

Calico: 3.21.1

**Comment by caseydavenport** [comment] 2022-06-24 16:44
I believe the problem is including `/32` addresses in the `serviceLoadBalancerIPs` section - the code doesn't account for that right now. @mtryfoss does your BGPConfiguration include `/32` addresses as well in that section?

**Comment by mtryfoss** [comment] 2022-06-24 18:28
Yes, we're also using /32. But like I mentioned, this seems to work as long as setRouteForSvc() is triggered by a change in one of the endpoints, and not in the service itself (svc nil, ep non-nil). Tried to do a custom build with a bit more verbose debug, but some step there failed.

Earlier we had troubling getting it to advertise using the full /29 we've assigned to that cluster, so ended up using /32.

I've studied that part of the code a bit. For me it almost looks like these are being "hard added" when config is applied somehow. Since it's not been advertised by setRouteForSvc(), it's not withdrawn either when it sees that there's no endpoint locally for that given services.

Will try investigating a bit more next week.

**Comment by caseydavenport** [comment] 2022-06-27 19:25
> For me it almost looks like these are being "hard added" when config is applied somehow.

This is exactly right. The semantics right now are:

- Advertise the prefixes provided in `serviceLoadbalanacerIPs` unconditionally from all nodes (this handles Cluster type svcs)
- If a service has externalTrafficPolicy=Local, advertise its address as a /32 route from nodes that have the service running.

This is correct assuming the prefixes in `serviceLoadbalancerIPs` are not fully qualified (e.g., /32 or /128), but incorrect when using a precisely specified service IP as you are in this case.

To handle /32 or /128 routes, I think the logic needs to be changed to this:

- Advertise non-fully-qualified `serviceLoadbalancerIPs` from every node (e.g., not /32 or /128)
- For fully-qualified `serviceLoadbalancerIPs` entries, advertise them from every node if the service is cluster-type, otherwise
- For local-type services, advertise a /32 from every node that hosts the address.

^ This is just a slightly different expression of https://github.com/projectcalico/calico/issues/6074#issuecomment-1137477343

**Comment by mtryfoss** [comment] 2022-06-27 19:37
Please have a look at my PR.

It should work more or less as you proposed, except that it will only announce services of type loadbalancer from nodes which do have endpoints regardless if cluster or local-type. Frankly, I don't see any reason not to behave like this for that case? Loadbalancer is most likely something that is not handled on all nodes anyway - for example an ingress controller.

I got fooled by another bug regarding /32 and larger definitions in the config section. We tried different configurations (switching between /32 and /29) for existing services, and that caused the /32 route from a specific node not to be announced until something on the service was changed. That should also be sorted out in the same patch.

**Comment by caseydavenport** [comment] 2022-06-27 19:40
> except that it will only announce services of type loadbalancer from nodes which do have endpoints regardless if cluster or local-type

This is expressly contrary to what the `externalTrafficPolicy` API is asking for with a `Cluster` service, though. Users who use `Cluster` type services want to load balance across all nodes in their cluster, and so we should be advertising those IPs from all nodes for those services. 

I'll take a look at your PR - it's already on my queue - but I don't believe the behavior you're describing for "Cluster" services is correct.

**Comment by mtryfoss** [comment] 2022-06-27 19:43
Would it be ok to announce services with externalTrafficPolicy: Cluster from all nodes as /32s then? Basically, skip check for endpoints.

At the point you're currently adding global routes we've got no clue of what type that route might belong to.

**Comment by caseydavenport** [comment] 2022-06-28 16:30
> Would it be ok to announce services with externalTrafficPolicy: Cluster from all nodes as /32s by the logic defined in router.go then

I'm curious why you would want this? Could you explain what you're thinking a bit more?

These are the scenarios I am thinking about:

1. We have a LoadBalancer CIDR in BGPconfig and several cluster-type services within that CIDR. We can cover _all_ of those serivces by advertising a single route for the entire LB CIDR.
2. We have a LoadBalancer CIDR in BGPconfig, and several cluster-type services, as well as a few local-type services. The cluster-type services are handled by a single route (the whole LB CIDR) and the local-type services advertise more specific /32 routes which override the full CIDR.
3. We have a LoadBalancer IP (not a full CIDR) in BGPconfig, and a cluster-type service that matches it. We advertise the /32 from all nodes.
4. We have a LoadBalancer IP (not a full CIDR) in BGPconfig, and a local-type service that matches it. We advertise the /32 from nodes that have the service running.

So, specifically for (1) and (2), switching to _always_ advertising a /32 route for cluster-type services would result in us advertising more routes than we need to. The tradeoff, I suppose, is that we are advertising a full range, but that should be OK given that range is by definition reserved for LB IPs anyway and should match the config given to the allocator anyway.

**Comment by mtryfoss** [comment] 2022-06-28 18:41
Maybe I'm getting this wrong since our use case is a bit limited, but my main reason was to keep things simple stupid.

Let's focus on the thing this patch is solving. Entries of single IP-adresses (/32).
We can't announce these globally, since what will break services requesting the Local type, so the simple solution here is _not_ to announce any of them globally.

In router.go we do handle changes to the service or the endpoints of the service. Here we don't know if the assigned IP-address is a /32 or part of a bigger subnet definition. We could of course extend the check against whitelisted addresses and return if it's an exact match or part of a subnet, but it kind of feels more robust to just do the more specific announcements.

I know that answer might vary depending on the environment. In our case we also do have routers in front of the k8s cluster doing aggregation, so some extra routes should not be a big issue.

**Comment by caseydavenport** [comment] 2022-06-28 21:23
I'm in favor of the simplest solution, but within the bounds set by the requirements. In this case, we _need_ to maintain the "aggregation" behavior for non-32 CIDRs. We do have some users relying on that behavior today and this would be a breaking change for them.

As you've said, that does mean we need some additional smarts within the code to determine if a cluster-type service IP belongs to some greater CIDR (i.e., already advertised) or if it matches an exact IP within the given serviceLoadbalancerIPs (i.e., we need to advertise a /32 from every node). 

However, I think this logic should be fairly straightforward to insert into the existing advertisement logic and doesn't introduce too much complexity. We can:

- Skip advertisement of any /32 CIDRs we find in serviceLoadbalancerIPs.
- When we get a cluster-type service, compare its address to serviceLoadBalancerIPs and advertise if it matches a /32.
- When we get a local-type service, maintain existing behavior (advertise from nodes that have endpoints).

The more complex part will be handling changes to serviceLoadbalancerIPs - e.g., if a /32 is removed and we need to withdraw it or a /32 is added and we now need to program it. From a code read, it looks like this might already be a gap in the existing code, so perhaps we can tackle this problem separately.

**Comment by mtryfoss** [comment] 2022-06-29 08:24
I see your point. I've updated the PR with changes that hopefully reflect the scenarios you describe.

Regarding the last part. I think this is already handled by my patch? If not, please elaborate.
I noticed the issue during testing when switching between /29 and /32 definitions.

Please have a look at this part:
![Skjermbilde 2022-06-29 kl  10 20 12](https://user-images.githubusercontent.com/7223432/176388131-4d45daf1-409e-4bb0-be27-e4687c1a4841.png)

As far as I understand. A config change basically writes all the entries from scratch, and then does c.rg.TriggerResync() to trigger iteration of services. The extra code above will make sure that all routes the route generator has added earlier also exists as static routes after the change.

**Closed** 2022-10-12 20:22 UTC
Labels: help wanted, kind/bug, good first issue, likelihood/high, impact/low
