### ISSUE TITLE
Support configuring pod annotations from Helm Chart

### ISSUE THREAD

**Issue by michelzanini** [projectcalico/calico#6101] opened 2022-05-15 21:14 UTC
Hi,

It should be possible to configure via Tigera Operator Helm chart the pod annotations for all deployed pods.

Including the tigera-operator itself but also calico-kube-controllers, calico-typha and calico-node.

This can help certain platforms that rely on custom annotations for custom features.

Possibly pod labels can useful too?

Thanks.

**Comment by caseydavenport** [comment] 2022-05-17 22:50
Closing as a duplicate of https://github.com/tigera/operator/issues/1099

**Closed by caseydavenport** 2022-05-17 22:50 UTC
Labels: kind/enhancement
