### ISSUE TITLE
Service cluster ip How to disable snat

### ISSUE THREAD

**Issue by wangycc** [projectcalico/calico#2999] opened 2019-11-18 14:09 UTC
## Expected Behavior
When I access service cluster ip, the backend pod can get source ip
## Current Behavior
SNAT all traffic sent via Service cluster IPs

## Steps to Reproduce (for bugs)

1. Advertising Kubernetes services over BGP
2. kubectl run source-ip-app --image=mirrorgooglecontainers/echoserver:1.4
3. kubectl expose deployment source-ip-app --name=clusterip --port=80 --target-port=8080
```shell
kubectl get svc clusterip
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
clusterip    ClusterIP   10.0.170.92   <none>        80/TCP    51s
```
4.  Access service cluster ip from outside the cluster
```
# curl 10.0.170.92
CLIENT VALUES:
client_address=10.106.65.3    ##Node ip instead of source IP
command=GET
...
```
## Your Environment

* Calico version : 3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.15.3
* Operating System and version:  Centos7.6 linux 4.19.8 kernel

**Comment by tmjd** [comment] 2019-11-18 21:28
I think you may want to take a look at this page https://docs.projectcalico.org/v3.10/networking/advertise-service-ips. Specifically the `Local` service type. I think that would do what you want.

**Comment by wangycc** [comment] 2019-11-19 02:51
@tm
Hi,I know that setting Local for the NodePort type can get the source ip,
but it's not what I want because I have already advertising kubernetes services over BGP to the outside of the cluster.I want to use cluster service ip as a load balancer.But the backend pod can't get the source ip.

**Comment by tmjd** [comment] 2019-11-19 16:04
Using the `Local` type is way to do what you want. Using NodePort still will allow the cluster service IP to be advertised over BGP, it should still work.

**Comment by ralfonso** [comment] 2019-12-09 17:31
I'm seeing an issue that sounds very similar with the `echoserver` image and a `NodePort` service with `externalTrafficPolicy: Local`

In my bare metal lab:

```
➜ k get pods source-ip-app-5b6654565f-xpjmd -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP             NODE             NOMINATED NODE   READINESS GATES
source-ip-app-5b6654565f-xpjmd   1/1     Running   0          9d    10.10.35.199   worker03-k8s01   <none>           <none>
```

```
➜ k get svc nodeport -o wide
NAME       TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE   SELECTOR
nodeport   NodePort   10.32.0.37   <none>        80:31933/TCP   9d    run=source-ip-app
```

The service ip, `10.32.0.73` is properly advertised to my router via BGP, but if I curl it from outside the Kubernetes network, it appears to get SNAT'd.

`192.168.42.217` is the IP of the Node hosting the Pod. I expect to see a `client_address` from a different network here. 

```
➜ curl http://10.32.0.37
CLIENT VALUES:
client_address=192.168.42.217
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.32.0.37:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
host=10.32.0.37
user-agent=curl/7.67.0
BODY:
-no body in request-
```

I have `nodeToNodeMesh: false` but a hint may be that doing the same curl from any Node in the cluster shows the correct `client_address`. I'm not sure why.

pod cidr: `10.10.0.0/16`
cluster cidr: `10.32.0.0/24`

Here are the associated iptables rules.

```
-A KUBE-NODEPORTS -s 127.0.0.0/8 -p tcp -m comment --comment "default/nodeport:" -m tcp --dport 31933 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nodeport:" -m tcp --dport 31933 -j KUBE-XLB-XP7QDA4CRQ2QA33W
-A KUBE-SERVICES ! -s 10.10.0.0/16 -d 10.32.0.37/32 -p tcp -m comment --comment "default/nodeport: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.32.0.37/32 -p tcp -m comment --comment "default/nodeport: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XP7QDA4CRQ2QA33W
-A KUBE-XLB-XP7QDA4CRQ2QA33W -s 10.10.0.0/16 -m comment --comment "Redirect pods trying to reach external loadbalancer VIP to clusterIP" -j KUBE-SVC-XP7QDA4CRQ2QA33W
-A KUBE-SVC-XP7QDA4CRQ2QA33W -j KUBE-SEP-KPSZ3UZSZLCCZ7OB
-A KUBE-SEP-KPSZ3UZSZLCCZ7OB -s 10.10.35.199/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-KPSZ3UZSZLCCZ7OB -p tcp -m tcp -j DNAT --to-destination 10.10.35.199:8080
```

**Comment by tmjd** [comment] 2019-12-10 20:39
What kube-proxy mode are you using iptables or ipvs?

**Comment by ralfonso** [comment] 2019-12-10 20:52
@tmjd I'm using `iptables`

**Comment by benceszikora** [comment] 2019-12-19 11:21
We have the same issue, but we are running kube-proxy in `ipvs` mode.

**Comment by wrigtim** [comment] 2019-12-19 13:24
+1

**Comment by neiljerram** [comment] 2019-12-19 19:16
A common cause for unwanted SNAT is when the Kubernetes cluster CIDR is not the same as Calico's IP Pool.  kube-proxy will SNAT traffic to a cluster IP from any source IP that is outside its `clusterCIDR` config.  Can the reporters please check if that might be their problem?

**Comment by ralfonso** [comment] 2019-12-19 21:41
@neiljerram Yes, that is my configuration. My Calico IP pool is set to the same as the `podCIDR` rather than the `clusterCIDR`. I used this guide to help make that determination https://docs.projectcalico.org/v3.10/getting-started/kubernetes/installation/calico

specifically: 
> If you are using pod CIDR 192.168.0.0/16, skip to the next step. If you are using a different pod CIDR, use the following commands to set an environment variable called POD_CIDR containing your pod CIDR and replace 192.168.0.0/16 in the manifest with your pod CIDR.

Is this incorrect or should have two pools, one for pod and one for services?

**Comment by neiljerram** [comment] 2019-12-20 10:52
@ralfonso I'm sorry, the terminology is unfortunately confusing here.  I believe that all of these things are the same concept, and should be configured the same:
- the Calico IP Pool
- `--cluster-cidr` passed to kube-controller-manager and kube-proxy
- what our doc at https://docs.projectcalico.org/v3.10/getting-started/kubernetes/installation/calico refers to as "pod CIDR" or POD_CIDR.

Then there is the service IP CIDR (`--service-cluster-ip-range` passed to kube-api-server), and it is important that the service IP CIDR **does not overlap** with the pod CIDR.

With that in mind, some comments on what you wrote:

> My Calico IP pool is set to the same as the `podCIDR` rather than the `clusterCIDR`

Do you mean "My Calico IP pool is set to the same as the `podCIDR` rather than the service IP CIDR"?  If so, that is correct.

> should I have two pools, one for pod and one for services?

No, you do not need an IP pool to match the service IP CIDR.

**Comment by ralfonso** [comment] 2019-12-20 16:30
@neiljerram Thanks! Apologies for mixing up some terms. My `--cluster-cidr` encompasses my Calico IP Pool. My `--service-cluster-ip-range` is outside of both. 

```
# --cluster-cidr=10.10.0.0/16
# --service-cluster-ip-range=10.32.0.0/24

$ calicoctl get ipPool -o yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: 2019-11-29T23:57:42Z
    name: default-ipv4-ippool
    resourceVersion: "86741667"
    uid: 7514e902-2e31-4e14-a835-86dbec996a23
  spec:
    blockSize: 26
    cidr: 10.10.32.0/20
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
```

**Comment by neiljerram** [comment] 2019-12-20 16:33
@ralfonso OK, so that's fine.  I'll just re-review the rest of the report here..

**Comment by ralfonso** [comment] 2019-12-31 03:14
I believe I've resolved this issue in my cluster by dropping the `--cluster-cidr` flag from `kube-proxy`. After removing this flag, my nodes no longer have iptables rules such as:

```
-A KUBE-SERVICES ! -s 10.10.0.0/16 -d 10.32.0.37/32 -p tcp -m comment --comment "default/nodeport: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
```

This prevents packets from outside of the Pod CIDR from being marked for masquerade/snat. I'm not yet positive that there are no detrimental side effects from this change. I'm slightly suspicious since it is not mentioned anywhere in the Calico docs, but so far the `echoserver` image displays the expected client source IP from outside the cluster and from other pods within the cluster. This is for requests through the `NodePort` service advertised via BGP and with `externalTrafficPolicy: Local`

**Comment by neiljerram** [comment] 2020-01-02 16:06
Hi everyone, just reviewing this again.  I think there may be several different issues here.  Also I think my previous two comments about unwanted SNAT were irrelevant - sorry about that.  (I thought we were talking about access from a client within the cluster, but I now see that we're mostly talking about access from outside the cluster.)

So I think there may be 3 different issues here:

1. @wangycc Wanting the behaviour of `externalTrafficPolicy: Local` with a `ClusterIP` service, which the Kubernetes API doesn't support.  Workaround should be to use a `NodePort` service instead with `externalTrafficPolicy: Local`.

2. @ralfonso You are using a `NodePort` service and kube-proxy in iptables mode, but you haven't yet said if you also have `externalTrafficPolicy: Local`.  If you don't, please try adding that.

3. @benceszikora @wrigtim You are using a `NodePort` service with `externalTrafficPolicy: Local`, but also kube-proxy in IPVS mode.  I'm not sure if we've fully tested service IP advertisement with IPVS, so it's possible that IPVS is the problematic ingredient here.

Does that all sound right?

**Comment by neiljerram** [comment] 2020-01-02 16:09
Update: sorry @ralfonso I have not yet taken into account your update from 3 days ago.  Will think about that now.

**Comment by benceszikora** [comment] 2020-01-08 11:11
@neiljerram We tried switching to iptables too, but that didn't resolve the issue. @ralfonso's suggestion seems to solve the issue for ClusterIPs, I believe because of this logic in kube-proxy: https://github.com/kubernetes/kubernetes/blob/db1990f48b92d603f469c1c89e2ad36da1b74846/pkg/proxy/iptables/proxier.go#L1008-L1015

Sadly that doesn't seem work for ExternalPs (we use that for our ingress VIP) as those are masqueraded regardless: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1074

**Comment by tsutsarin** [comment] 2020-02-20 09:30
Any update on this?
I have tried both `NodePort` and `LoadBalancer` with `externalTrafficPolicy: Local` and my traffic is SNAted regardless.
I'm using `kube-proxy` in `ipvs` mode with default `clusterCIDR` config. I have also tried to remove `clusterCIDR` setting completely, but then traffic was dropped somehow half of times. It was `Service` with two replicas behind.

**Comment by spikecurtis** [comment] 2020-03-18 16:45
@tsutsarin with clusterCIDR set, `kube-proxy` is designed to SNAT traffic from outside that range.

The fact that traffic is getting dropped when you remove that range is nominally a different issue. It sounds a lot like some of the traffic is being forwarded to a pod that is not local to the node, and being dropped because there was not SNAT.  Can you double check that you're only using services with `externalTrafficPolicy: local` in that configuration?

**Comment by spikecurtis** [comment] 2020-03-18 16:47
One other thing to point out to everyone on this issue is that Calico just shipped a tech preview of a new dataplane based on eBPF that replaces `kube-proxy` for services and always preserves the original source IP (no SNAT).  Try it out and let us know whether it works for you! https://docs.projectcalico.org/getting-started/kubernetes/trying-ebpf

**Comment by neiljerram** [comment] 2020-03-18 22:32
Thanks @spikecurtis .

It feels like we've established now that this isn't a Calico bug, but kube-proxy working as designed. Perhaps a good kube-proxy enhancement would be for it to skip the MASQUERADE when it ends up forwarding to a pod on the same node? But that would obviously be something to raise with kube-proxy. (FYI the kube-proxy issue that introduced this is https://github.com/kubernetes/kubernetes/issues/24224.)

I'll close this now, but please do follow up if you think that's wrong.

**Closed** 2020-03-18 22:32 UTC
Labels: kind/support

**Comment by arianvp** [comment] 2020-06-20 00:44
it would at least be helpful to mention the `clusterCIDR` setting of `kube-proxy` in the calico docs. Can never hurt.
I just hit my head against this.

Luckily all of this will become a lof nicer with the new eBPF dataplane =)

**Comment by arianvp** [comment] 2020-06-21 15:18
I'm not sure if it's fair to say this isn't a Calico bug; as Calico documentation surrounding networkpolicies relies on the behaviour to act as described by OP. Namely that using `externalTrafficPolicy: Local` skips the SNAT for external traffic that hits the box. 

https://docs.projectcalico.org/security/services-cluster-ips

So we should at least fix the documentation in this regard.

I've  also observed that removing `clusterCIDR` from kube-proxy is not desired. For me it leads to services with `externalTrafficPolicy: Cluster`  to misbehave (as kube-proxy doesn't know anymore when to and when not to SNAT; it seems)

**Comment by arianvp** [comment] 2020-09-07 08:51
Just checking in again here if there is anything we can do about improving the docs on this?

As far as I can see (from the PR that @neiljerram linked from 2016) kube-proxy simply _always_ SNATs  traffic originating from outside of the ClusterCIDR   (https://github.com/kubernetes/kubernetes/blob/v1.17.0/pkg/proxy/iptables/proxier.go#L965-L970) so the calico docs are wrong (or at least they are when using kube-proxy).  Would a PR with some changes be appreciated?

**Comment by arianvp** [comment] 2020-09-08 00:50
Interestingly  I found out that source ip _is_ preserved if you set `externalIPs` field on your `NodePort` service with `externalTrafficPolicy: Local` and use that instead of the `clusterIP` to reach it.   I hope this helps anybody who stumbles upon this issue too :)

**Comment by Anil-YadavK8s** [comment] 2020-12-11 13:28
We facing the same issue.  When accessing a service from its own POD --> SNAT is happening (Service is type LoadBalancer with ExternalTrafficPolicy=Local)

admin@control-plane-2~> kubectl exec pod-1 -it -- curl 10.217.100.70:80 -----> This is LoadBalancer service ip of Pod-1
 CLIENT VALUES:
client_address=10.0.10.105 ===============> This is Node IP .....It should be POD-1 IP 
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.217.100.70:8080/

**Comment by MalikaML** [comment] 2023-10-27 14:49
@Anil-YadavK8s Hi, Im facing the exact same issue, I have tried `externalTrafficPolicy: Local` in the service spec (type: LoadBalancer), but when accessing that service from its own pod and executing `curl http://ipinfo.io/ip
` to check the external ip address I get the one of the master node instead of the external ip address of the pod. As I mentioned in the beginning, I have the same issue you had before, so I was wondering what is the solution to this issue ? thank you
