### ISSUE TITLE
BlockAffinities in pending state should not be advertised

### ISSUE THREAD

**Issue by eugene-eeo** [projectcalico/calico#6867] opened 2022-10-19 12:56 UTC
We currently have:

```
$ etcdctl get /calico/ipam/v2/host/node1/ipv4/block/x.y.z.0-24
{"state":"pending","deleted":false}
$ etcdctl get /calico/ipam/v2/host/node2/ipv4/block/x.y.z.0-24
{"state":"confirmed","deleted":false}
```

_Side note:_ For some reason `node1`'s pending BlockAffinity wasn't cleaned up. We ran into this state because when the confirmed BlockAffinity was created, (we _think_, based on the ETCD revision numbers) the AssignmentBlock wasn't in ETCD, which caused the AutoAssign logic to think everything was ok. not 100% sure of the root cause yet, but the cluster has been running for quite some time and has seen its fair share of network issues.

## Expected Behavior

As `node1`'s block affinity is in a pending state, `node1` should **not** advertise that packets should be routed to it (nor should it blackhole the CIDR).

## Current Behavior

currently the block is blackholed on `node1`:

```
# on node1
$ ip route show
blackhole x.y.z.0/24 proto bird
```

other nodes route traffic to the host as well:

```
# on another node
$ ip route show
x.y.z.0/24 proto bird
        nexthop via node1 dev eth0 weight 1
        nexthop via node2 dev eth0 weight 1
```

this is because in `node1`s bird_aggr config:

```cfg
# Generated by confd

protocol static {
   # IP blocks for this host.
   route x.y.z.0/24 blackhole;
}

# Aggregation of routes on this host; export the block, nothing beneath it.
function calico_aggr ()
{
      # Block x.y.z.0/24 is pending
}
```

## Possible Solution

A quick fix would be to add a check for the affinity's `state` in the [`bird_aggr.cfg.template`](https://github.com/projectcalico/calico/blob/master/confd/etc/calico/confd/templates/bird_aggr.cfg.template#L9) file, and only add the blackhole route if `state == "confirmed"`.

Perhaps periodically cleaning up the BlockAffinities would be good as well.

## Steps to Reproduce (for bugs)

I guess you can create a pending BlockAffinity manually in ETCD.

## Context

Packets were routed to the wrong node (which dropped all the packets due to `blackhole`).

## Your Environment

* Calico version `v3.17.4`
* Orchestrator version (e.g. kubernetes, mesos, rkt): `K8s v1.20.7`
* Operating System and version: `RHEL 8.3`

**Comment by caseydavenport** [comment] 2022-10-19 17:10
I think this is a duplicate of https://github.com/projectcalico/calico/issues/6001

Which was actually already fixed in https://github.com/projectcalico/calico/pull/6003 - first in Calico v3.24.0

**Closed by caseydavenport** 2022-10-19 17:10 UTC

**Comment by eugene-eeo** [comment] 2022-10-19 17:57
ah ok sorry I missed it 😅
yep looking at the tests in that MR, looks like it's fixed there.

thanks again!
