### ISSUE TITLE
Need working config/best practice for deploying k8s on OpenStack

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#274] opened 2016-11-28 09:03 UTC
User reached out after having difficulty getting connectivity up; what OpenStack configuration is needed to make this work?  Some equivalent to disabling RPF check?

**Comment by caseydavenport** [comment] 2018-03-01 19:21
Closing this as a dupe of https://github.com/projectcalico/calico/issues/1235 since that one has a bit more detail.

**Closed by caseydavenport** 2018-03-01 19:21 UTC
Labels: area/docs/content, content/needed, priority/P2, size/M
