### ISSUE TITLE
Add public-cloud guide for each supported provider

### ISSUE THREAD

**Issue by lxpollitt** [projectcalico/calico#264] opened 2016-11-24 17:01 UTC
Currently it just says "coming soon".
As a minimum first increment we could add links to the several different getting started on AWS, GCE, etc docs we have for the different orchestrators.
But some serious restructuring to remove the duplication from those sections and put it all well structured in one places here is also needed (as we had planned).

**Comment by caseydavenport** [comment] 2016-11-24 17:39
@djosborne is working on this.

I think this overlaps with #219

**Comment by lxpollitt** [comment] 2016-11-24 18:17
Cool.  I think if there are trivial increments we can deliver to improve a doc then we should not hold that up behind other more significant work we are doing.  Hence suggestion for the minimum first increment.  Happy for @djosborne to use his own judgement on whether that is worth while or just push on and get #219 done and dusted.

**Comment by djosborne** [comment] 2016-11-25 16:47
Adding an AWS guide at #258

**Comment by djosborne** [comment] 2016-11-29 23:18
This seems like an exact dupe of [#220](https://github.com/projectcalico/calico/issues/220). Was I wrong to change the title here? I think we should tackle 220 and close this.

**Closed** 2016-12-01 01:23 UTC
Labels: area/docs, content/needed, priority/P1, size/L
