### ISSUE TITLE
when use multus-cni to add calico-cni as undefault interface, routes(0.0.0.0/0) conflict with default one  

### ISSUE THREAD

**Issue by jinglina** [projectcalico/calico#5962] opened 2022-04-25 02:55 UTC
## Expected Behavior
when use multus-cni to add calico as second interface using crd(network-attachment-definitions.k8s.cni.cncf.io), calico ipam is **calico-ipam** instead of **host-local**, calico will add defaultRoute(0.0.0.0/0) as route, which may conflict with default cni route(kube-ovn. eg).
I hope when multus-cni sending request of adding cni to calico, calico should deal with related parameters like ipam type is **host-local** to avoid route conflict.

## Current Behavior
when use multus-cni to add calico-cni as undefault interface, routes(0.0.0.0/0) conflict with default one  

## Steps to Reproduce (for bugs)

1.  default cni is kube-ovn
2. add multus-cni to add calico as second cni to support multus cni
3. add calico to system
4. add crd to add calico as second cni to specific pod
5. pod cannot be created for routes conflict

## Your Environment

* Calico version v3.21.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s version : 0.20.10
* Operating System and version: 
* Link to your project (optional):

**Comment by caseydavenport** [comment] 2022-05-02 20:41
Closing this as a duplicate of this enhancement request: https://github.com/projectcalico/calico/issues/5199

Currently, Calico doesn't support multiple networks where Calico is not the primary (default) network.

**Closed by caseydavenport** 2022-05-02 20:41 UTC
