### ISSUE TITLE
tunnel interfaces created by Calico are not being removed upon node deletion on sles15 machines

### ISSUE THREAD

**Issue by riyazhakki** [projectcalico/calico#8662] opened 2024-03-28 08:28 UTC
## Expected Behavior

clean up tunnel interface created by Calico network plugin on node deletion on SLES15 machine

## Current Behavior

tunnel interfaces created by Calico are not being removed upon node deletion on sles15 machines
## Steps to Reproduce (for bugs)

1. create a worker node using 
`sudo $(kubeadm token create --print-join-command)`
2. submit a pod
```
tee redis.yaml << EOF
apiVersion: v1
kind: Pod
metadata:
  name: redis1
spec:
  schedulerName:
  containers:
  - name: redis
    image: redis:latest
    resources:
      requests:
        cpu: "2m"
        memory: "100Mi"
      limits:
        cpu: "2m"
        memory: "100Mi"
EOF

kubectl apply -f redis.yaml
```

3. delete the pod
`kubectl delete pod redis1`

4. delete the node
`kubectl delete node`

## Your Environment

* Calico version docker.io/calico/node:v3.26.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.29
* Operating System and version: centos15
* Link to your project (optional):

**Comment by riyazhakki** [comment] 2024-03-28 08:48
tried to enable cleanup feature with following yaml, recived error message 
error: resource mapping not found for name: "default" namespace: "" from "calico.yaml": no matches for kind "FelixConfiguration" in version "projectcalico.org/v3"


# calico.yaml

apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  cleanup:
    enabled: true

**Comment by coutinhop** [comment] 2024-04-02 19:57
@riyazhakki could you please fill in the issue template? And also give a bit more details on the commands you used to execute the steps you mentioned?

> error: resource mapping not found for name: "default" namespace: "" from "calico.yaml": no matches for kind "FelixConfiguration" in version "projectcalico.org/v3"

This is caused by the apiserver not being deployed (please see https://docs.tigera.io/calico/latest/operations/install-apiserver#install-the-api-server). BUT, this manifest looks completely wrong, so even after you deploy the apiserver you're going to see further errors. There is no `cleanup` or `configuration` present in the spec for FelixConfiguration: https://docs.tigera.io/calico/latest/reference/resources/felixconfig#spec

May I ask where did you get that manifest from?

**Comment by riyazhakki** [comment] 2024-04-15 14:51
> @riyazhakki could you please fill in the issue template? And also give a bit more details on the commands you used to execute the steps you mentioned?
> 
> > error: resource mapping not found for name: "default" namespace: "" from "calico.yaml": no matches for kind "FelixConfiguration" in version "projectcalico.org/v3"
> 
> This is caused by the apiserver not being deployed (please see https://docs.tigera.io/calico/latest/operations/install-apiserver#install-the-api-server). BUT, this manifest looks completely wrong, so even after you deploy the apiserver you're going to see further errors. There is no `cleanup` or `configuration` present in the spec for FelixConfiguration: https://docs.tigera.io/calico/latest/reference/resources/felixconfig#spec
> 
> May I ask where did you get that manifest from?

@coutinhop, Thank you for looking into this issue. As you suggested, I have completed the template and included the commands used to reproduce the issue.

The manifest I mentioned is obtained from the path `/etc/cni/net.d/10-calico.conflist`.

**Comment by mazdakn** [comment] 2024-07-30 16:49
@riyazhakki there is no such clean up process in Calico. The main reason is that in most cases shutting down Calico nodes is due to a restart (this happens for many reasons) or upgrade. In theses cases, we want to keep the dataplane state there and cleaning up is not an option.

What is the use case you are trying to achieve? If you want to remove Calico and clean up routes, you can just reboot the node to clean up all dataplane states, or maybe change tunnel device state to down.

**Comment by sridhartigera** [comment] 2024-08-13 16:30
@riyazhakki Closing this issue. Feel free to reach out if you have more information.

**Closed by sridhartigera** 2024-08-13 16:30 UTC
Labels: kind/support
