### ISSUE TITLE
Calico Daemonset Iptables Issue in RHEL 8

### ISSUE THREAD

**Issue by HenryXie1** [projectcalico/calico#7393] opened 2023-02-24 11:49 UTC
We have upgrade the worker node to RHEL 8. it has iptables-nft enabled
iptables -V --> iptables-nft in the OS

We are currently using the Calico daemonset version 3.24, and according to the documentation, it should automatically detect the version of iptables on RHEL 8. We have verified this information through the following links:  https://github.com/projectcalico/calico/issues/2322, and https://github.com/projectcalico/calico/pull/4322.

However, when we run the command "kubectl exec -it calico-nodes-*** -- iptables -V," it shows that the version being used is iptables v1.8.4 (legacy). Even when we added the environment variable FELIX_IPTABLESBACKEND with the value "Auto" and rolled the pods, the legacy version of iptables was still being used.

. We are confused because despite this information, when we run the "iptables -V" command on the Calico node, it still shows the legacy version of iptables. Could you please provide clarification on this matter?

Meanwhile I found https://github.com/projectcalico/calico/pull/7111 is still open (not merged)
seems the issue is not fixed,so I wonder how Calico implemented  iptables automatic detection feature. or did I miss sth?
Thank you

@caseydavenport  Thank you
## Expected Behavior
When work nodes upgrade to RHEL 8,
kubectl exec -it calico-nodes-*** -- iptables -V   --> iptables-nft

## Current Behavior

with calico 3.24 and RHEL 8
we run the command "kubectl exec -it calico-nodes-*** -- iptables -V," it shows that the version being used is iptables v1.8.4 (legacy)
## Possible Solution

no
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  3.24
* Orchestrator version kubernetes
* Operating System and version: RHEL 8 kernel 4.18 with iptables-nft
* Link to your project (optional):

**Comment by yankay** [comment] 2023-02-27 02:24
We have the same issue :-)
Welcome to help to review the https://github.com/projectcalico/calico/pull/7111 :-)

**Comment by MichalFupso** [comment] 2023-03-21 16:58
Hi @HenryXie1, #7110 has been merged into Calico v3.25, which fixes this issue

**Comment by yankay** [comment] 2023-03-22 05:12
> Hi @HenryXie1, #7111 has been merged into Calico v3.25, which fixes this issue

HI  @MichalFupso , 
The https://github.com/projectcalico/calico/pull/7111 is merged into the Calico v3.26.
And the Cherry-Pick https://github.com/projectcalico/calico/pull/7460 is for the  Calico v3.25.

**Comment by HenryXie1** [comment] 2023-03-23 05:28
Hi, @yankay   Thanks for your input
I happen to notice this PR https://github.com/projectcalico/calico/pull/4322
https://www.tigera.io/blog/whats-new-in-calico-v3-12/
It seems it was included in 3.12,  
not sure how that works with your PR https://github.com/projectcalico/calico/pull/7460

**Comment by yankay** [comment] 2023-03-24 05:27
> 

HI @HenryXie1

Follow the description of the issue, The issue is the same as the: https://github.com/projectcalico/calico/issues/2322. The auto-detect logic in the RHEL/Centos 8 is to detect auto as a legacy instead of NFT. So that causes the issue.

There is a blog article about the issue: https://mihail-milev.medium.com/no-pod-to-pod-communication-on-centos-8-kubernetes-with-calico-56d694d2a6f4

The https://github.com/projectcalico/calico/pull/7111 and https://github.com/projectcalico/calico/pull/7460 are to fix the issue.

**Comment by HenryXie1** [comment] 2023-03-24 06:31
Thanks @yankay 
I read a blog and implement Calico version 3.24 with RHEL 8 iptables-nft. I discovered that the issue mentioned in https://github.com/projectcalico/calico/issues/2322 had been resolved, as new iptables nft rules were created. However, when I checked the calico-node by running the command iptables -V, it still showed iptables legacy.

I am not sure how this works in version 3.24 without the PRs mentioned in https://github.com/projectcalico/calico/pull/7111 and https://github.com/projectcalico/calico/pull/7460.

**Comment by tangkelu** [comment] 2024-11-28 03:34
env: RHEL 8.10, iptables v1.8.5 (nf_tables), Calico v3.25.2, calico-node daemonset env added FELIX_IPTABLESBACKEND value to Auto
if i run command [ kubectl exec -it calico-node-xxx -- iptables -V  ] still shows [ iptables v1.8.4 (legacy) ]

**Comment by caseydavenport** [comment] 2024-12-03 00:09
> Hi @HenryXie1, https://github.com/projectcalico/calico/pull/7111 has been merged into Calico v3.25, which fixes this issue

Closing this one as fixed. 

> However, when I checked the calico-node by running the command iptables -V, it still showed iptables legacy.

This makes sense - Calico doesn't update the symlinks within the container, it just calls the binary that it needs directly.

**Closed by caseydavenport** 2024-12-03 00:09 UTC
Labels: kind/bug
