### ISSUE TITLE
Flannel to Calico migrator can't find kube-flannel daemonsets

### ISSUE THREAD

**Issue by abhinand5** [projectcalico/calico#7261] opened 2023-02-01 07:10 UTC
The flannel to calico migrator is looking for the flannel daemon set `kube-flannel-ds` in `kube-system` namespace, but it has been long since flannel changed to running their daemon sets in a separate namespace names `kube-flannel`. Because of this flannel to calico migration jobs does nothing, it states that there is not migration needed as the kube-flannel daemonsets are nowhere to be found. 

## Expected Behavior
The flannel to calico migrator should find the kube-flannel daemonset and perform the migration to calico.

## Current Behavior
The migrator is unable to find the kube-flannel daemonset in the expected namespace and reports that no migration is needed.

## Possible Solution
The solution would be to update the migrator to look for the kube-flannel daemonset in the correct namespace kube-flannel instead of kube-system.

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
N/A

**Comment by nisc-acooper** [comment] 2023-04-10 17:55
This is a duplicate of (https://github.com/projectcalico/calico/issues/6745)

**Closed** 2023-04-14 19:45 UTC
Labels: help wanted, kind/bug, likelihood/low, impact/high

**Comment by caseydavenport** [comment] 2023-04-14 19:53
PR in progress here: https://github.com/projectcalico/calico/pull/7557
