### ISSUE TITLE
Feature request: Support advertising IPv6 Service/Cluster IPs

### ISSUE THREAD

**Issue by DennisGlindhart** [projectcalico/calico#2731] opened 2019-07-17 13:37 UTC
Feature described here, does not seem to support IPv6
https://docs.projectcalico.org/v3.8/networking/service-advertisement

In the config reference https://docs.projectcalico.org/v3.8/reference/node/configuration it states that CALICO_ADVERTISE_CLUSTER_IPS expects a IPv4 CIDR.

(For the sake of curiosity, putting an IPv6 range into the variable makes nodes failed with: `bird: /etc/calico/confd/config/bird_aggr.cfg, line 5: This is an IPv4 router, therefore IPv6 addresses are not supported`)

## Your Environment
* Calico version: 3.8
* Orchestrator version: Kubernetes 1.15
* Operating System and version: CentOS 7.5

**Comment by rafaelvanoni** [comment] 2019-07-22 20:09
@lwr20 Lance, could you please take a look at this and see if it's a documentation problem or a bug?

**Comment by lwr20** [comment] 2019-07-23 08:20
Since the docs clearly state that its expecting an IPv4 CIDR and OP has tried putting an IPv6 CIDR in (and it didn't work), this is clearly a feature request, no?

What's happening is that the value in this variable is being copied into the ipv4 bird config.  There's a separate bird config for IPv6.  

Speculating now, but for dual-stack operation, it might be required to have both IPv4 and IPv6 CIDRs - so the enhancement would probably be to add an additional env var for IPv6 and have that value make its way into the IPv6 bird config.  @neiljerram would likely know more.

**Comment by neiljerram** [comment] 2019-07-23 09:02
@DennisGlindhart @lwr20 @rafaelvanoni Yes, I can confirm that service cluster IP advertisement is currently for IPv4 only.  It shouldn't be hard to extend to IPv6, so long as all the other ingredients play ball.  For example, does k8s `svc.Spec.ClusterIP` now allow an IPv6 address instead of IPv4?

**Comment by tmjd** [comment] 2019-07-23 15:46
@lwr20 yes it is a feature request, but I knew you had done some IPv6 testing and wanted to make sure that we really didn't support it yet (I couldn't remember who had added service advertisement).
@neiljerram Thanks for confirming.

**Comment by lmm** [comment] 2020-01-27 22:33
This is fixed by https://github.com/projectcalico/confd/pull/310

**Closed by lmm** 2020-01-27 22:33 UTC
Labels: kind/enhancement, priority/P2
