### ISSUE TITLE
systemd-udevd failed to generate MAC address

### ISSUE THREAD

**Issue by weiwei04** [projectcalico/calico#763] opened 2017-05-09 02:12 UTC
I setup a k8s with calico cni cluster, occasionally run into failed to setup container network problem.

I have a pod started on a k8s node with `container: 524e77f4db72，container ip: 172.20.124.234`, on the host node, I run `ip route`, the result is

0.34.44.0/24 dev bond0 proto kernel scope link src 10.34.44.26
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.20.67.0/26 via 10.34.42.51 dev tunl0 proto bird onlink
172.20.92.64/26 via 10.34.42.53 dev tunl0 proto bird onlink
blackhole 172.20.124.192/26 proto bird
172.20.124.202 dev cali917ff036459 scope link
172.20.124.230 dev cali1821f35aab0 scope link
172.20.124.232 dev cali217b63e6517 scope link
172.20.124.233 dev cali0153dbe41dd scope link
172.20.124.235 dev cali9563f8e1bae scope link
172.20.124.236 dev cali28364da5246 scope link
172.20.250.0/26 via 10.34.42.52 dev tunl0 proto bird onlink

there's no route for container ip: 172.20.124.234

and I found a error log for systemd-udevd failed to setup mac address

`systemd-udevd[28731]: Could not generate persistent MAC address for cali0bbf7ac8759`

some system version info:
OS: Linux xs315 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Systemd: systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
kubelet: Kubernetes v1.6.1
calico images: quay.io/calico/node:v1.1.0, quay.io/calico/cni:v1.6.1, quay.io/calico/kube-policy-controller:v0.5.4

need some help to fix this problem, thanks.

**Comment by tmjd** [comment] 2017-05-09 03:40
Sounds like maybe you're hitting this. https://github.com/systemd/systemd/issues/3374
If it is reproducible you could try the work around suggested in https://github.com/systemd/systemd/issues/3374#issuecomment-288882355 to see if it fixes it for you.  Though I'm not sure if there are any negative side effects of the work around.

**Comment by tmjd** [comment] 2017-05-30 20:50
As you have found this seems to be a systemd-udev issue so I am going to close this for now.  If you can test with the above linked work around that would be nice to know if it fixes the issue.  If you are still having this issue with the work around please try to create a 'short' set of steps to reproduce it and that may help with identifying the root issue.  Thanks

**Closed by tmjd** 2017-05-30 20:50 UTC
Labels: kind/support
