### ISSUE TITLE
pod cant setup with ippool blocksize 32

### ISSUE THREAD

**Issue by halfcrazy** [projectcalico/calico#3635] opened 2020-06-05 10:39 UTC
pod cant setup with ippool blocksize 32
![image](https://user-images.githubusercontent.com/4113173/83867229-ad534700-a75b-11ea-9f26-55d2d9bbdc93.png)
![image](https://user-images.githubusercontent.com/4113173/83867408-f73c2d00-a75b-11ea-90a9-89a8a53c99ae.png)

## Expected Behavior

Pod running
## Current Behavior

Pod sucks at containercreating
## Possible Solution

Don't write a blackhole route for /32 block
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.14.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s
* Operating System and version:
* Link to your project (optional):

**Comment by halfcrazy** [comment] 2020-06-09 05:47
One question is the blackhole router necessary or in which scenario we can disable programming blackhole router?

**Comment by caseydavenport** [comment] 2020-06-10 22:50
Going to close this as a duplicate of https://github.com/projectcalico/calico/issues/2624

**Closed by caseydavenport** 2020-06-10 22:50 UTC
