### ISSUE TITLE
Calico v3.0.5 unit test failures for s390x 

### ISSUE THREAD

**Issue by chakravarthy392** [projectcalico/calico#1970] opened 2018-05-10 09:51 UTC
Observed 13 TC failures on s390x compared to on X86_64 when I execute Calico-3.0.5 unit test cases. 

     [fail] 3.86% tests.st.bgp.test_ipip.TestIPIP.test_gce_rr_0: 122.3938s
     [fail] 3.79% tests.st.bgp.test_ipip.TestIPIP.test_gce_rr_1: 120.0795s
     [fail] 3.54% tests.st.calicoctl.test_autodetection.TestAutodetection.test_autodetection: 112.1616s
     [fail] 3.38% tests.st.bgp.test_ipip.TestIPIP.test_issue_1584_0_bird: 107.2228s
     [fail] 3.34% tests.st.bgp.test_ipip.TestIPIP.test_gce_1: 105.8414s
     [fail] 3.05% tests.st.bgp.test_ipip.TestIPIP.test_gce_0: 96.9071s
     [fail] 2.34% tests.st.bgp.test_single_route_reflector.TestSingleRouteReflector.test_bird_single_route_reflector_default_as: 74.2440s
     [fail] 2.12% tests.st.bgp.test_single_route_reflector.TestSingleRouteReflector.test_bird_single_route_reflector: 67.2836s
     [fail] 2.05% tests.st.bgp.test_ipip.TestIPIP.test_ipip_0_bird: 65.1266s
     [fail] 1.49% tests.st.bgp.test_node_peers.TestNodePeers.test_bird_node_peers: 47.3489s
     [fail] 1.38% tests.st.bgp.test_global_peers.TestGlobalPeers.test_bird_node_peers: 43.6822s
     [fail] 1.32% tests.st.bgp.test_update_ip_addr.TestUpdateIPAddress.test_update_ip_address: 41.7428s
     [fail] 1.15% tests.st.bgp.test_global_config.TestBGP.test_bird_as_num: 36.5907s

Out of these 13 failures, 12 are related to bgp module. These failures also include the TC failures mentioned in the https://github.com/projectcalico/calico/issues/1677 .

I have observed these failures on SLES distributions only.

## Steps to Reproduce (for bugs)
``` ARCH=s390x  ST_TO_RUN=tests/st/bgp/test_single_route_reflector.py:TestSingleRouteReflector.test_bird_single_route_reflector make st```

## Context
I have started debugging the failures by comparing behavior on both the X86 & S390x, but not able to understand what exactly leads to these failures and these failures were not observed on Ubuntu and RHEL7.x (s390x). 

What/which module I need to check exactly to find the reason of failure.

## Your Environment

* Calico version:v3.0.5
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version: S390x-SLES
* Link to your project (optional):

**Comment by chakravarthy392** [comment] 2018-05-11 05:25
@ozdanborne Please check below details and let me know if some more details are required.

Below logs were produced by running an individual test case `test_bird_single_route_reflector` on both architectures with same docker version.

[S390X_test_bird.log.log](https://github.com/projectcalico/calico/files/1994014/S390X_test_bird.log.log)
[X86_test_bird.log.txt](https://github.com/projectcalico/calico/files/1994015/X86_test_bird.log.txt)

## Some more details: 

I have run Calico-3.0.5 TCs on SLES 12 SP2/SP3 multiple times and some times I have observed iptables issue which is addressed in https://github.com/projectcalico/calico/issues/1676 on s390x arch (all TCs are passing on x86) .

**iptables version on both x86 & s390x : v1.4.21**

### docker version: 
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Tue May 30 21:46:10 2017
 OS/Arch:      linux/s390x

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Tue May 30 21:46:10 2017
 OS/Arch:      linux/s390x
 Experimental: true

### docker info:

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 117
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-0:35-97214336-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 161.1GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.916GB
 Data Space Total: 107.4GB
 Data Space Available: 102.5GB
 Metadata Space Used: 7.041MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.14GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /scratch/ecos0031/docker_7may/devicemapper/devicemapper/data
 Metadata loop file: /scratch/ecos0031/docker_7may/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2015-05-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary:
containerd version:  (expected: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73)
runc version: N/A (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
Kernel Version: 4.4.126-94.22-default
Operating System: SUSE Linux Enterprise Server 12 SP3
OSType: linux
Architecture: s390x
CPUs: 8
Total Memory: 15.62GiB
Name: ecos0031
ID: JMFB:BOAK:E6M6:7MTF:BDAY:N65X:4Z4A:3H5I:6RUN:CHTL:BTEC:PNX2
Docker Root Dir: /scratch/ecos0031/docker_7may
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
WARNING: No kernel memory limit support

**Comment by fasaxc** [comment] 2018-05-11 08:44
I've taken a quick look at the logs.  The issue is that `iptables-restore` is failing at the "COMMIT" stage.  That can happen if another application is modifying iptables concurrently, or it may be that the s390x kernel has a bug or different behaviour vs amd64.

**Comment by chakravarthy392** [comment] 2018-05-11 10:53
@fasaxc I have executed Calico job only on the re-imaged SLES VM and kernel versions I am using are `4.4.126-94.22-default` (s390x) and `4.4.120-94.17-default` (x86).

**Comment by fasaxc** [comment] 2018-05-21 09:31
@chakravarthy392 Please can you try with v3.1 of all components?

**Comment by chakravarthy392** [comment] 2018-05-22 05:48
@fasaxc I have verified the Calico-3.0.5 TC behavior with Felix-3.1.2 which is released recently.
iptables-restore issue is resolved and all TCs are passing on SLES 12 SP3, checking the same on SLES 12 SP2.

**Comment by chakravarthy392** [comment] 2018-05-25 05:45
Hi @fasaxc , all TCs of Calico-3.0.5 (s390x) are passing on SLES 12 SP2 and SP3 with Felix-3.1.2. 
TCs are passing on x86 with both Felix-3.0.4 & 3.1.2.

**Comment by fasaxc** [comment] 2018-05-25 08:30
@chakravarthy392 OK, so it was a SLES issue and it's resolved by SP2?  If so, let's close this out.

**Comment by chakravarthy392** [comment] 2018-05-25 10:00
@fasaxc The issue is solved by using Felix-3.1.2. Even though all TCs are passing , I am wondering if any functionality would get affected due to this.

**Comment by fasaxc** [comment] 2018-05-25 14:43
@chakravarthy392 The FV tests do run Felix for real so if it's failing then it's likely that real-world scenarios will fail too.  Can you try a real-world test (I'm afraid my team don't have access to s390x infrastructure to try it out).

**Comment by chakravarthy392** [comment] 2018-05-28 07:03
@fasaxc , I was not talking about FV tests, all unit tests (make st) of Calico-3.0.5 are passing with Felix-3.1.2.

**Comment by fasaxc** [comment] 2018-05-30 16:29
@chakravarthy392 `make st` runs system tests, not unit tests.  Our system tests spin up real copies of calico/node (and felix) and test with real traffic.

**Closed** 2018-11-30 02:07 UTC
Labels: kind/support
