### ISSUE TITLE
Crash PODs added multiple interfaces (Free5GC, UERANSIM, Calico, Multus)

### ISSUE THREAD

**Issue by pinoOgni** [projectcalico/calico#6896] opened 2022-10-24 14:05 UTC
Hi everybody!

## Expected Behavior

I'm using the [towards5gs-helm](https://github.com/Orange-OpenSource/towards5gs-helm) project that provide helm charts in order deploy Free5GC and UERASIM. I'm using Calico with Multus. 

## Current Behavior

In brief: there seem to be problems adding multiple (MACVLAN) interfaces in some PODs in some circumstances.

[Here](https://github.com/Orange-OpenSource/towards5gs-helm/issues/55) is the detailed description of the problem 

I opened the same issue on [Multus](https://github.com/k8snetworkplumbingwg/multus-cni/issues/938).

Do you have any suggestions? Thanks in advance

Giuseppe

**Comment by caseydavenport** [comment] 2022-11-02 22:26
Calico doesn't support multiple interfaces in general, and MACVLAN specifically, so that is likely the root of the problem. 

This is the catch-all issue for that: https://github.com/projectcalico/calico/issues/5199

I'm going to close this as a duplicate of that one in order to keep multi-interface discussion in one place.

**Closed by caseydavenport** 2022-11-02 22:26 UTC
