### ISSUE TITLE
Calico-node cannot access kube-apiserver via 10.96.0.1, node with multi ip addresses

### ISSUE THREAD

**Issue by BedivereZero** [projectcalico/calico#3938] opened 2020-08-26 13:06 UTC
One of calico-node pods is CrashLoopBackOff.

Log of the pod:

```log
2020-08-26 08:42:51.858 [INFO][79] felix/watchercache.go 206: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/ippools" error=Get https://10.96.0.1:443/apis/crd.projectcalico.org/v1/ippools: dial tcp 10.96.0.1:443: connect: connection refused
2020-08-26 08:42:51.859 [INFO][79] felix/networkpolicy.go 245: Unable to list Calico CRD-backed Network Policy resources error=Get https://10.96.0.1:443/apis/crd.projectcalico.org/v1/networkpolicies: dial tcp 10.96.0.1:443: connect: connection refused
2020-08-26 08:42:51.859 [INFO][79] felix/watchercache.go 206: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/clusterinformations" error=Get https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations: dial tcp 10.96.0.1:443: connect: connection refused
2020-08-26 08:42:51.859 [INFO][79] felix/watchercache.go 206: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/networkpolicies" error=Get https://10.96.0.1:443/apis/crd.projectcalico.org/v1/networkpolicies: dial tcp 10.96.0.1:443: connect: connection refused
```

This Kubernetes consists of three nodes, deployed by `kubeadm`.

|              | node-139-157    | node-139-158 (Master) |
| :----------- | :-------------- | :-------------------- |
| IP Address A | 192.168.139.157 | 192.168.139.158       |
| IP Address B | 10.10.139.157   | 10.10.139.158         |

```console
$ kubectl get node -owide
NAME           STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
node-139-157   Ready    <none>   34h   v1.18.5   10.10.139.157   <none>        CentOS Linux 7 (Core)   3.10.0-1127.18.2.el7.x86_64   docker://19.3.12
node-139-158   Ready    master   34h   v1.18.5   10.10.139.158   <none>        CentOS Linux 7 (Core)   3.10.0-1127.18.2.el7.x86_64   docker://19.3.12
```

I try to tcpdump:

```tcpdump
19:59:40.285570 IP 192.168.139.157.30026 > 10.10.139.158.6443: Flags [.], ack 11643, win 2126, options [nop,nop,TS val 37720327 ecr 37427719], length 0
19:59:40.285610 IP 192.168.139.157.30026 > 10.10.139.158.6443: Flags [.], ack 13227, win 2126, options [nop,nop,TS val 37720327 ecr 37427719], length 0
19:59:40.285757 IP 192.168.139.157.30026 > 10.10.139.158.6443: Flags [P.], seq 38:73, ack 13227, win 2126, options [nop,nop,TS val 37720327 ecr 37427719], length 35
19:59:40.285795 IP 192.168.139.157.30026 > 10.10.139.158.6443: Flags [P.], seq 73:108, ack 13227, win 2126, options [nop,nop,TS val 37720327 ecr 37427719], length 35
```

## Expected Behavior

Calico-node accesses kube-apiserver successfully.

pod/calico-node-xxxxx are running and Ready.

Calico-node access 10.96.0.1 from 10.10.139.157.

## Current Behavior

Calico-node access 10.96.0.1 from 192.168.139.157.

## Possible Solution

Is there a parameter or environment variable to control the source IP used by the calico-node, similar to --interface for curl.

## Your Environment

* Calico version: v3.15.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: CentOS 7.7.1908

**Comment by caseydavenport** [comment] 2020-08-31 21:12
Yeah, the problem is that Kubernetes services aren't real IP addresses, so the kernel picks a source address for accessing them prior to the DNAT, and thus it's possible that it picks wrong.

A workaround might be to trick the hosts into thinking that they should use the `10.10.x.x` addresses for talking to Kubernetes services by adding a route to the host for the service range? But that could very well have other unintended consequences.

I believe in Calico we have a similar issue when using encapsulation and we solved it by adding an additional SNAT rule after the DNAT occurs. Maybe kube-proxy needs to do a similar thing for services?

**Comment by lmm** [comment] 2020-11-12 17:14
Closing this issue - @BedivereZero if you want to continue this discussion please feel free to reopen or open a new issue, thanks!

**Comment by aasraoui** [comment] 2021-03-30 02:45
what was the conclusion for this ? thanks!

**Comment by chenliu1993** [comment] 2022-06-25 14:04
Any help on this issue? I met the same problem. On a different VPC, one worker node is showing the same error as this issue

**Comment by caseydavenport** [comment] 2022-06-27 18:56
Actually, @chenliu1993 this one is pretty old - would you mind opening a new issue describing your symptoms and scenario?

**Closed by caseydavenport** 2022-06-27 18:56 UTC
Labels: kind/support

**Comment by chenliu1993** [comment] 2022-06-28 05:51
> d opening a new issue describ

Just saw this, done opening a new one!

**Comment by jiangxiaoqiang** [comment] 2023-11-13 10:33
> > d opening a new issue describ
> 
> Just saw this, done opening a new one!

did you fixed this issue? I am facing the same error. with kuberetes 1.28.3 and centos 7.9
