### ISSUE TITLE
"bad certificate" in etcd (v3.4.9-1) with Calico v3.16.0 on K8s (v1.19.0)

### ISSUE THREAD

**Issue by Apentacon** [projectcalico/calico#3969] opened 2020-09-03 17:55 UTC
After upgrading Calico from v3.15.2 to v.3.16.0 etcd (v3.4.9-1) in pod on Kubernetes (v1.19.0) no longer accepts same certificate. Kubernetes cluster on RHEL7.8, kernel: 3.10.0-1127.13.1.el7.x86_64

## Expected Behavior
After upgrading Calico from v3.15.2 to v3.16.0 it should work with same certificates.

## Current Behavior
When using calico-etcd.yaml to upgrade from Calico v3.15.2 to v3.16.0 and using same etcd/ca certificates and same etcd endpoints upgrade happens successfully, however, after restarting any application pods on worked nodes, like CoreDNS, it gets stuck on CreatingContainer. After doing describe on the pods, the error is :

  Warning  FailedCreatePodSandBox  34s    kubelet, <host> Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox <pod>: netplugin failed with no error message

During this time, etcd pod logs constantly throw this error in relation to worker nodes:

I | embed: rejected connection from "<workernodeIP>:<random port>" (error "remote error: tls: bad certificate", ServerName "")

I have doublechecked the certificates and done diff on both v3.15.2 calico-etcd.yaml file and v3.16.0 yaml file, and both contain same certificates for etcd pods. 

## Possible Solution
Roll-backing to v3.15.2 seems to immediately fix the issue and containers on worker nodes start immediately when calico pod restarts with older version. 

## Steps to Reproduce (for bugs)
1. Upgrade Kubernetes cluster to latest v1.19 version with etcd in pods.
2. Upgrade Calico from v3.15.2 to v3.16.0
3. Restart any application pod on worked node. 

## Context
Due to this issue, cannot upgrade to latest Kubernetes+Calico vxlan versions. Not sure however, if this issue is present with older Kubernetes version such as v1.18, however, will try to reproduce it soon with older Kubernetes version.

Things changed in calico-etcd.yaml when building/upgrading:
added certs for etcd-cert,key,ca
etcd_endpoints: "https://etcdIP:2379,https://etcdIP:2379,https://etcdIP:2379"
calico_backend: "vxlan"
mtu 1450

            - name: CALICO_IPV4POOL_IPIP
              value: "Never"
            - name: CALICO_IPV4POOL_VXLAN
              value: "Always"

bird probes commented out.

## Your Environment
3 ControlPlane nodes, 10 worker nodes, 3 etcd member cluster running in pods - each on every controlplane node. Calico running in VXLAN mode.

* Calico version without issue:
Client Version:    v3.16.0
Git commit:        741a6ee0
Cluster Version:   v3.15.2
Cluster Type:      k8s,bgp,kubeadm

* Calico version with issue:
Client Version:    v3.16.0
Git commit:        741a6ee0
Cluster Version:   v3.16.0
Cluster Type:      k8s,bgp,kubeadm

* Orchestrator version (e.g. kubernetes, mesos, rkt):
etcd                         3.4.9-1             d4ca8726196cb       255MB
kubelet-1.19.0-0.x86_64
kubeadm-1.19.0-0.x86_64
kubectl-1.19.0-0.x86_64
cri-o-1.18.1-2.2.el7.x86_64

* Operating System and version:
Red Hat Enterprise Linux Server release 7.8 (Maipo)
Kernel: 3.10.0-1127.13.1.el7.x86_64

**Comment by caseydavenport** [comment] 2020-09-04 17:27
https://github.com/projectcalico/cni-plugin/issues/944

I believe there is a known issue where Calico v3.16 fails to populate the right etcd certs. To confirm this is the same thing, can you check what the contents of `/etc/cni/net.d/10-calico.conflist` are on the host?

**Comment by Apentacon** [comment] 2020-09-04 17:50
Hi Casey,

With v3.15.2:
      "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
      "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
      "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",

After running upgrade to v3.16.0:
      "etcd_key_file": "",
      "etcd_cert_file": "",
      "etcd_ca_cert_file": "",


Looks indeed like the same issue!
I assume it would be enough to just populate these lines and restart calico-node pods to resolve this issue after upgrade for now?

**Comment by caseydavenport** [comment] 2020-09-04 18:09
@Apentacon great, glad to hear it's the same issue.

I have this PR in progress that should fix it: https://github.com/projectcalico/cni-plugin/pull/948

Intending to cut a patch release early next week.

**Comment by caseydavenport** [comment] 2020-09-04 18:10
I'm going to close this issue as a duplicate of the other one for now. Thanks for the help!

**Closed by caseydavenport** 2020-09-04 18:10 UTC
Labels: impact/high, kind/bug, likelihood/high
