### ISSUE TITLE
enable bfd for calico node's  BGP peer

### ISSUE THREAD

**Issue by jackygam2001** [projectcalico/calico#7728] opened 2023-06-01 06:23 UTC
Since BFD is fast link failure checking protocol, when set up calico as full mesh BGP mode, it may make sense for calico fast checking the node's link down in the cluster 

## Expected Behavior
 can calico's node BGP to provide a configuration item enable bfd? 

## Current Behavior
 calico's node BGP does not support configure bfd

**Comment by caseydavenport** [comment] 2023-06-01 16:12
Closing this as a duplicate of https://github.com/projectcalico/calico/issues/4607

**Closed by caseydavenport** 2023-06-01 16:12 UTC
