### ISSUE TITLE
Does calico support to configure the advised subnet len of node?

### ISSUE THREAD

**Issue by cumirror** [projectcalico/calico#1608] opened 2018-01-16 12:17 UTC
There are no configurations to set the advised subnet len. When configured ippool, i just  found the advised subnet is like xxx.xxx.xxx.xxx/26 (255.255.255.192). 
How could i modify these subnet len, and why just fix it to 26?

ippool as following:
# calicoctl get ippool -o yaml
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 192.168.0.0/16
  spec:
    ipip:
      enabled: true
      mode: cross-subnet
    nat-outgoing: true

# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.14.7.1       0.0.0.0         UG    0      0        0 ens3
10.14.7.0       0.0.0.0         255.255.255.0   U     0      0        0 ens3
192.168.12.64   0.0.0.0         255.255.255.224 U     0      0        0 docker0
192.168.133.192 10.14.132.18    255.255.255.192 UG    0      0        0 tunl0
192.168.166.128 10.14.7.150     255.255.255.192 UG    0      0        0 ens3
192.168.177.192 0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.177.200 0.0.0.0         255.255.255.255 UH    0      0        0 calib917f7255b6
192.168.177.203 0.0.0.0         255.255.255.255 UH    0      0        0 cali4b8ad452371
192.168.177.204 0.0.0.0         255.255.255.255 UH    0      0        0 cali68b193302dc

## Expected Behavior
i want to assign the advised subnet len.

## Current Behavior
can't set the advised subnet len

## Possible Solution
Maybe we could set  the advised subnet len when configure ippool.

## Context
our private ippool is 192.168.0.0./16, and the number of k8s nodes will be more than 1500, but if subnetlen is 26, then we could only have 2^10 = 1024 nodes. If we can set subnetlen to 27 or smaller, then there is no problem. 

## Environment
* calico-node               v2.6.3 
* calico-kube-controllers   v1.0.1 
* calico-cni                v1.11.1
* k8s 1.8

**Comment by caseydavenport** [comment] 2018-01-16 19:29
@cumirror it's not possible to change that value right now since it's currently hard-coded. It should be possible to adjust the code to make it configurable, but there are complications around changing it on an already running system that would need more thought.

If possible, you could also add additional IP pools, or use something larger than a /16, for more address space, though I understand that's not always possible.

Also note that you can still have more than 1024 nodes today, just that nodes beyond 1024 won't have their routes aggregated.

**Comment by cumirror** [comment] 2018-01-17 03:51
@caseydavenport i found this: `https://github.com/projectcalico/calico/issues/1568`.
Change libcalico-go/lib/ipam/ipam_block.go, and is it possible to solve this promble?
steps like this:

1. change ipam_block.go, modify blocksize, BlockPrefixLength and BlockPrefixMask.

```
const (
	blockSize = 64
)

type ipVersion struct {
	Number            int
	TotalBits         int
	BlockPrefixLength int
	BlockPrefixMask   net.IPMask
}

var ipv4 ipVersion = ipVersion{
	Number:            4,
	TotalBits:         32,
	BlockPrefixLength: 26,
	BlockPrefixMask:   net.CIDRMask(26, 32),
}
```

2.checkout cni-plugin, and rebuild calico-cni  image.

In addition to ipam_block.go, should i change other codes? and is it necessary to rebuild calico-node and calico-kube-controllers images?

**Comment by cumirror** [comment] 2018-01-17 06:49
> Also note that you can still have more than 1024 nodes today, just that nodes beyond 1024 won't have their routes aggregated.

@caseydavenport if the number exceed 1024, how to assign pod's ip on that nodes, and what's the policy of route?

**Comment by caseydavenport** [comment] 2018-01-17 18:43
@cumirror I'm not sure I understand your question. 

If all blocks are assigned to a node, then new nodes will assign IPs to pods from a block that is already assigned to another node.

The original node will still advertise the entire `/26`, but the new node will assign a `/32` for the pod running on that node.

**Comment by ozdanborne** [comment] 2018-03-09 00:30
Closing this issue as a duplicate of the feature request for "configurable block sizes" here: https://github.com/projectcalico/libcalico-go/issues/761

**Closed by ozdanborne** 2018-03-09 00:30 UTC
Labels: kind/support

**Comment by jbrisko** [comment] 2018-07-23 22:15
Any update on this one? I am working on a project now that could really use this change. Thanks!
