### ISSUE TITLE
Manual MTU size configuration 

### ISSUE THREAD

**Issue by granttigera** [projectcalico/calico#794] opened 2017-05-16 00:29 UTC
Provide directions for manual MTU size configuration 

Examples:
Change container MTU Size
 "mtu":xxxx in the ipam section in /etc/cni/net.d/10-calico.conf 

Change IPIP tunl0 MTU Size  
tunl0 MTU you need to set `FELIX_IPINIPMTU`

**Comment by ozdanborne** [comment] 2017-05-16 00:55
Closing as dupe of #659

**Closed by ozdanborne** 2017-05-16 00:55 UTC
