### ISSUE TITLE
install_cni script doesn't honour sigterm

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1294] opened 2017-11-01 17:38 UTC
k8s v1.8 makes the daemonset scheduler honour the termination grace period, which imposes a delay (default 30s) between kubelet sending our pod a SIGTERM and then a SIGKILL.  I noticed that runit, bird and felix all shut down quickly on sigterm but install_cni seems to ignore it, I believe the problem is a known feature of alpine's shell.

## Expected Behavior

install_cni should die quickly on SIGTERM 

## Current Behavior

install_cni blocks shutdown

## Possible Solution

- Convert install_cni to an init container
- Add a trap to the script
- Switch to bash, which does honour SIGTERM
- Move the script under the runit container.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Note: I have a PR up to disable the grace period on calico/node in order to solve a different problem.  However, not everyone uses our manifests so it'd still be good to clean this up.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by ketkulka** [comment] 2018-03-05 23:14
I have some free cycle. I would be willing to help with this. Would like some guidance though if its ok with you.

Few questions/confusions:
0. assumption: install-cni.sh is run as daemonset in k8s in one of the containers of calico pod. 
1. install-cni.sh to init container: init container are run to completion but the script continuously monitor the  k8s certificates
2. TRAP can be added to the script just like  calico-felix-wrapper script
3. install-cni.sh seems to be based on ash (as calico/cni Dockerfile is from busybox). So the signal handling should be available.
4. what is expected behavior when the signal is caught? just terminate/exit or cleanup and exit?

Let me know if i am on right track.

Thanks
Ketan

**Comment by fasaxc** [comment] 2018-03-06 10:54
@ketkulka thanks for the offer to help.  I think that @caseydavenport said that switching to an init container is not easy because we need to keep monitoring the secrets.  However, adding the TRAP handler should do the trick. When the script gets a SIGTERM it should exit, I don't think there's any cleanup to do for this script (and it will only be sent a SIGTERM if the pod is being shut down).

**Comment by ketkulka** [comment] 2018-03-07 00:37
@fasaxc Thanks for the quick info.
I have opened the PR on cni-plugin to fix this issue.

https://github.com/projectcalico/cni-plugin/pull/482

Testing details are included in the PR. Let me know if the PR is sufficient. Any further work; feel free to suggest.

Thanks
Ketan

**Comment by ketkulka** [comment] 2018-03-08 18:50
Thanks @fasaxc for merging! Feel free to close this issue if nothing else is needed.

**Closed** 2018-03-08 18:57 UTC
Labels: help wanted, priority/P3
