### ISSUE TITLE
plugin type="calico" name="Calico" failed (add): timeout acquiring mutex [Windows]

### ISSUE THREAD

**Issue by joelandersen89** [projectcalico/calico#7823] opened 2023-06-28 16:44 UTC
## Expected Behavior
Pods are able to create without issue regardless of cluster size, HNS Endpoints, etc

## Current Behavior
Pods are failing to create on Windows nodes. This is seen when there are multiple pods scheduled on the same Windows node at one time. Once this behavior is experienced the node become unusable and requires a restart to recover. The current size of our cluster is ~500 nodes with ~665 endpoints causing a large amount of HNS endpoints. 

## Possible Solution
No suggestions as of yet. Working with MS and they are not seeing any issues with HNS or other Windows resources. 

## Steps to Reproduce (for bugs)
1. Schedule 8+ Pods on the same node at one time. 
2. First 5 or so will schedule after about 9 minutes
3. Remainder of the pods will not schedule and throw an error similar to the one in the title. 
4. Codon node and clean up failed pods.
5. Reboot to recover and repeat. 

## Context
We are currently unable to run a large number of Windows workloads as this issue takes a large amount of babysitting and requires constant cleanup. 

## Your Environment

* Calico version  v3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Windows Server 2019 OS build 17763.3650
* Cluster Size: ~500 nodes
* HNS Endpoints: 1404
* Link to your project (optional):

**Comment by coutinhop** [comment] 2023-09-19 16:28
@joelandersen89 it's a bit hard to reproduce this issue on our end due to the scale. Could you send Calico logs (you'll need ssh/RDP access to the windows nodes, then they should be under `C:/CalicoWindows/logs`), preferably after enabling debug logging with `kubectl patch felixconfiguration default --type merge --patch='{"spec":{"logSeverityScreen":"Debug"}}'`?

**Comment by sridhartigera** [comment] 2023-10-03 16:27
@joelandersen89 Were you able to reproduce this issue? If so, can you share the logs?

**Comment by joelandersen89** [comment] 2023-10-03 20:43
Yes, this issue is reproducible. We are working with MS but since Win Server 2019 is going into EOL in January they are hesitant to provide a fix as this is due to an issue with HNS. When updating to Win Server 2022 we do not see this issue.

**Comment by coutinhop** [comment] 2023-11-21 18:07
@joelandersen89 thanks for the info on root cause (win server 2019 HNS) and workaround (upgrade to win server 2022)! Will close this issue and leave the info here if anyone needs it.

**Closed by coutinhop** 2023-11-21 18:07 UTC
Labels: area/windows
