### ISSUE TITLE
Update default MTU for Ip-in-Ip as 1430

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/calico#988] opened 2017-08-01 20:37 UTC
Based on https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_openstack_platform/7/html/networking_guide/sec-mtu, in Openstack with vxlan environment, the default MTU is 1450 which is even less than GCE 1460, so the default MTU for the IP-in-IP should be update to 1430.

The proposal is adding a new line for `OpenStack VXLAN` and set the default MTU for Ip-in-Ip as 1430.

**Comment by ozdanborne** [comment] 2017-08-01 20:40
@gyliu513 a lot of the calico openstack maintainers are out of office the next few days so it may be a bit before the right pereson gets to this

**Comment by gyliu513** [comment] 2017-08-01 20:47
@ozdanborne no problem and thanks.

**Comment by caseydavenport** [comment] 2019-04-05 18:46
Closing as a duplicate of https://github.com/projectcalico/felix/issues/1532

**Closed by caseydavenport** 2019-04-05 18:46 UTC
Labels: kind/feature, orchestrator/openstack, priority/P3
