### ISSUE TITLE
System Tests (st) execution get stuck on SLES 12 sp1 distro

### ISSUE THREAD

**Issue by guirish** [projectcalico/calico#1729] opened 2018-03-06 09:33 UTC
## Expected Behavior
All ST test cases should pass on running make st on SLES 12 SP1 distro.

## Current Behavior

On Ubuntu 16.04 I am able to execute the entire system test suite, where as on SLES 12 sp1 the  test case execution gets stuck while executing below step. Kindly also find attached logs for reference.
[testlog.log](https://github.com/projectcalico/calico/files/1784270/testlog.log)

``` 
Final command: docker exec -it host1 sh -c 'head -100 /var/log/calico/felix/current'
```

## Steps to Reproduce (for bugs)
1. cd $GOPATH/src/github.com/projectcalico/calico/calico_node
2. make st

## Context
As I was observing similar issue on s390x for only SLES distro, I did verification for reproducing it on x86_64.

## Your Environment
ARCH=x86_64
kernel=3.12.74-60.64.40-default
Distribution: SLES 12-sp1
Calico version : 3.0.3

## Docker info:
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 54
Server Version: 17.04.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.18.2+20150430
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary:
containerd version:  (expected: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73)
runc version: N/A (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
Kernel Version: 3.12.74-60.64.40-default
Operating System: SUSE Linux Enterprise Server 12 SP1
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.459GiB
Name: suse-server2
ID: HNS6:ZD7X:CR53:HM7O:UNVG:D4AI:UGVO:ZEXA:NMQ7:BPX3:MOHT:KS7F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: abc
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support

## Docker version

Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Tue May 30 18:21:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Tue May 30 18:21:18 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by tmjd** [comment] 2018-03-07 16:09
This could be related to or a duplicate of #1676.

**Comment by tmjd** [comment] 2018-03-27 20:13
Could you try updating to the latest master and see if this problem still persists?  This change https://github.com/projectcalico/calico/pull/1756 went in to address some test flake failures seen and I am wondering if it helped this issue too.

**Comment by guirish** [comment] 2018-03-28 13:07
@tmjd thanks for above updates. The latest master code seams to address hung up issue on SLES distro.

**Closed** 2018-03-28 13:19 UTC
Labels: kind/support
