### ISSUE TITLE
Wireguard support doesn’t configure private IPv6 networks

### ISSUE THREAD

**Issue by koehn** [projectcalico/calico#5727] opened 2022-03-09 11:43 UTC
## Expected Behavior
On a dual-stack cluster, Calico should configure Wireguard to route both private ipv4 and private IPv6 pod networks. 

```
# wg
interface: wireguard.cali
  public key: 0KeiHgNL4punETL4D5kYXkNmmNVfBsKOF5JjpEDvrWY=
  private key: (hidden)
  listening port: 51820
  fwmark: 0x100000

peer: BsTgMHF4mMDMf1YXbopyDIF9lbLDn1FKLK+XKJxD2Q0=
  endpoint: 1.2.3.4:51820
  allowed ips: 10.42.138.128/26, 10.42.138.128/32, 10.42.138.129/32
  latest handshake: 25 minutes, 45 seconds ago
  transfer: 54.29 KiB received, 164.14 KiB sent
```

## Current Behavior
Calico configures wireguard to route only private ipv4 pod networks.

## Possible Solution
Given that wireguard can route IPv6 over IPv4, this should be as simple as duplicating the code that configures the IPv4 network to also configure the private IPv6 one to point to the same IPv4 endpoint. 

## Steps to Reproduce (for bugs)

1. Create dual-stack cluster (I used k3s/Ubuntu) with private IPv4 and IPv6 networks
2. Enable wireguard `calicoctl patch felixconfiguration default --type='merge' -p '{"spec":{"wireguardEnabled":true}}'`
3. Run wg to examine wireguard configuration

## Context
This makes dual-stack fairly difficult to use with Wireguard. While pods can still route outbound IPv6 with NAT, they can’t communicate with one another. 

## Your Environment 
* Calico 3.22.1
* Orchestrator version: k3s v1.22.7+k3s1
* Operating System and version: Ubuntu 20.04
* Wireguard v1.0.20200513

**Comment by caseydavenport** [comment] 2022-03-11 18:29
Yep, this is a known gap and is on the roadmap.

**Comment by unixfox** [comment] 2022-03-23 22:56
Duplicate of https://github.com/projectcalico/calico/issues/4492

**Closed** 2022-03-24 18:57 UTC
Labels: kind/enhancement
