### ISSUE TITLE
Calico node spikes with memory usage after upgrading to 3.20

### ISSUE THREAD

**Issue by invidian** [projectcalico/calico#4810] opened 2021-08-05 11:28 UTC
## Expected Behavior
Memory usage of DaemonSet remains stable.

## Current Behavior
Memory usage is now spiky, occasionally triggering OOM on small nodes. This graph shows memory usage after updating from 3.19.1 to 3.20.0.
![Selection_444](https://user-images.githubusercontent.com/16539896/128342304-0aab1dd5-7da1-40ad-8399-418f0cbe9e87.png)

## Steps to Reproduce (for bugs)

1. `helm repo add flexkube https://flexkube.github.io/charts/`
2. `helm upgrade --install --wait -n kube-system calico flexkube/calico`
3. Wait.

## Your Environment

* Calico version
```
    Image:          docker.io/calico/kube-controllers:v3.20.0
    Image:         docker.io/calico/cni:v3.20.0
    Image:         docker.io/calico/cni:v3.20.0
    Image:          docker.io/calico/pod2daemon-flexvol:v3.20.0
    Image:          docker.io/calico/node:v3.20.0
```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version:
```
Flatcar Container Linux by Kinvolk 2905.2.1 (Oklo)   5.10.55-flatcar
```

My config:
```yaml
data:
  calico_backend: bird
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "nodename_file_optional": true,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
  typha_service_name: none
  veth_mtu: "1430"
```

**Comment by invidian** [comment] 2021-08-11 23:03
@caseydavenport thanks for having a look. I'll try to collect some information next week. It seems GitHub didn't send any notifications about your comments to me, perhaps because of the outage yesterday.

**Comment by george-angel** [comment] 2021-08-23 10:46
Hello, we are seeing the same behaviour:

![2021-08-23-104809_2560x1368_scrot](https://user-images.githubusercontent.com/1801067/130432978-3565bbb1-4057-4ccc-b0dd-5da117d85bf0.png)

Calico: `v3.20.0` - using Wireguard, `container_memory_working_set_bytes` metric.

Will work on getting your pprof :+1:

**Comment by george-angel** [comment] 2021-08-23 14:33
![2021-08-23-153024_2528x632_scrot](https://user-images.githubusercontent.com/1801067/130465214-09e04849-98fb-4228-9d86-7a6343a5d186.png)

Only has been running for 3h - but you can see the gradual increase

[felix-mem.pb.gz](https://github.com/projectcalico/calico/files/7032713/felix-mem.pb.gz)

tyvm to Shaun for helping me get the pprof.

**Comment by george-angel** [comment] 2021-08-24 07:51
![2021-08-24-083041_2528x631_scrot](https://user-images.githubusercontent.com/1801067/130575482-dac75050-1e95-4a73-8a8b-eb4bd91f5c86.png)
[felix-mem-2021-08-24.pb.gz](https://github.com/projectcalico/calico/files/7037484/felix-mem-2021-08-24.pb.gz)
18 hours

**Comment by fasaxc** [comment] 2021-11-09 14:17
Cracking the profiles yields the attached memory diff.  Since most of the memory is leaked from `startm()`, which is the runtime function that starts system threads, I think this is likely to be a duplicate of https://github.com/projectcalico/calico/issues/5018, which has already been fixed in v3.21.0

[Memory profile diff](https://github.com/projectcalico/calico/files/7505334/profile001.pdf)

**Comment by fasaxc** [comment] 2021-11-09 14:19
@george-angel @invidian Please try v3.21.0 and let us know if that resolves the issue.

**Comment by fasaxc** [comment] 2021-11-09 14:33
Great, thanks for letting us know.

**Closed by fasaxc** 2021-11-09 14:33 UTC
Labels: kind/bug, likelihood/high, impact/high
