### ISSUE TITLE
k8s cluster, calico-node pick a vip on worker node,  pick host ip on master node!

### ISSUE THREAD

**Issue by Lzhang-hub** [projectcalico/calico#5346] opened 2021-12-31 08:20 UTC
On k8s cluster with four node(three master,one node), we add a VIP for HA.
After we deploy calico on cluster, k8s master node pick node ip,but k8s worker node pick VIP.  
And three master node can communicate with each other, but worker node communication failure.

VIP config: 
> DEVICE=lo:1
IPADDR=xxx.xxx.xxx.xxx
NETMASK=255.255.255.255
ONBOOT=yes
NAME=loopback1

This VIP was added on all node

We conf the calico with:
![image](https://user-images.githubusercontent.com/57925599/147812040-871444de-9d77-4a4a-acc9-61f149108974.png)

**Comment by caseydavenport** [comment] 2022-01-07 22:13
You probably need to configure a different autodetection mode. Or put your VIP on a different interface (e.g., loopback). 

Otherwise, this is a duplicate of another similar issue that will be fixed in v3.22, documented here: https://github.com/projectcalico/calico/pull/5212

**Closed by caseydavenport** 2022-01-07 22:13 UTC
