### ISSUE TITLE
Large RAM consumption

### ISSUE THREAD

**Issue by proskehy** [projectcalico/calico#2703] opened 2019-07-04 12:21 UTC
Calico pods consume a surprisingly large amount of RAM. I'm pretty sure this shouldn't be the case, but I don't know why it could be happening. I do not use any special networking rules in Kubernetes, just deployed Calico and didn't poke it further.

## Expected Behavior
I would expect Calico to consume a relatively small amount of RAM.

## Current Behavior
```
NAME                                          CPU(cores)   MEMORY(bytes)
calico-kube-controllers-5cbcccc885-qmhzp      2m           1132Mi
calico-node-dqr4f                             17m          116Mi
calico-node-vgn4l                             17m          566Mi
calico-node-zfr2m                             18m          368Mi
```

## Steps to Reproduce (for bugs)
I'm not sure how to reproduce. Previous verisons of Calico have been quite memory-hungry as well, but with 3.6 and introduction of the calico-kube-controllers pod, it's the first time I saw it break the 1k mark.

## Context
Excessive resources usage.

## Your Environment
* Calico version 3.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.14.1
* Operating System and version: Centos 7

**Comment by fasaxc** [comment] 2019-07-05 13:45
Please can you examine the memory usage of the processes inside the pod?  Might just be file system caches and the like that can be reclaimed by the OS if needed.  I.e. we might no be _using_ that much ram, but we may have written that much to the log file over time and then had the log file cached.

**Comment by fasaxc** [comment] 2019-07-05 14:34
Please can you give more information about your set-up?  Which networking mode are you using?  etcd or kubernetes datastore driver?  How big is your lcuster?  How many pods?  Is that the memory usage after startup or does it grow to that level over time?  How long?

**Comment by proskehy** [comment] 2019-07-08 06:19
Memory usage of processes in the `calico-kube-controllers` pod:
```
ps -o rss
RSS
 17m
 600
 252
```
Calico is setup using instructions here for the Kubernetes API datastore: https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/calico

The cluster has 1 master node, 2 slave nodes. There is ~38 pods running, including all the kube-system stuff like core components and Calico. There isn't a large amount of traffic going at the cluster.

I haven't been checking the usage right after startup, but the amounts I wrote in the OP were after ~20 days.

**Comment by fasaxc** [comment] 2019-07-09 12:40
OK, so the actual processes inside the pod aren't using very much at all, should we close this, then?

**Comment by fasaxc** [comment] 2019-07-09 12:45
Note: v3.6.3 does have a fix for a (fairly slow) memory leak, you should definitely upgrade to that if you haven't already.

**Comment by proskehy** [comment] 2019-07-18 11:27
I'm not sure if we should close this to be honest, I'd still like to know where did the 1GB of memory go. Do you have any idea which logfile would you write this much data into (as per your initial reply)? I might understand that with the `calico-node` pods, but the `calico-kube-controllers` container logged about 8 lines since the time it was started, so I'm curious as to where that would come from.

**Comment by fasaxc** [comment] 2019-07-18 12:32
Let's first check if I'm reading that `ps` output correctly.  On my system, `ps` reports in KB but your output is showing `17m` for one of the processes.  Please can you confirm the memory usage of the processes inside the container?

Beyond that, it's a bit tricky to find out where that number comes from; if you can find the cgroup for the container then you can look in the cgroup accounting stats files: https://fabiokung.com/2014/03/13/memory-inside-linux-containers/

Also worth making sure your docker is up to date, there were bugs in the memory reporting in some versions.

**Comment by proskehy** [comment] 2019-07-19 11:39
I'm not too familiar with finding this kind of information, so I looked in `/proc/1/status`, where the `17m` seems to check out?
```
/proc/1 # cat status
Name:   kube-controller
Umask:  0022
State:  S (sleeping)
Tgid:   1
Ngid:   0
Pid:    1
PPid:   0
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 64
Groups: 0 1 2 3 4 6 10 11 20 26 27
VmPeak:   134520 kB
VmSize:   134520 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     18464 kB
VmRSS:     17888 kB
RssAnon:            7164 kB
RssFile:           10724 kB
RssShmem:              0 kB
VmData:   103016 kB
VmStk:       132 kB
VmExe:     14056 kB
VmLib:         0 kB
VmPTE:       100 kB
VmSwap:        0 kB
Threads:        8
SigQ:   12/47436
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000000000
SigCgt: fffffffe7fc1feff
CapInh: 00000000a80425fb
CapPrm: 00000000a80425fb
CapEff: 00000000a80425fb
CapBnd: 00000000a80425fb
CapAmb: 0000000000000000
Seccomp:        0
Cpus_allowed:   00000000,00000003
Cpus_allowed_list:      0-1
Mems_allowed:   00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:      0
voluntary_ctxt_switches:        1332060
nonvoluntary_ctxt_switches:     251456
```

Then I looked at `/sys/fs/cgroup/memory.stat`:
```
/sys/fs/cgroup/memory # cat memory.stat
cache 24576
rss 8650752
rss_huge 0
mapped_file 0
swap 0
pgpgin 86102783
pgpgout 86100665
pgfault 355263384
pgmajfault 0
inactive_anon 0
active_anon 8613888
inactive_file 8192
active_file 16384
unevictable 0
hierarchical_memory_limit 12456550400
hierarchical_memsw_limit 9223372036854771712
total_cache 24576
total_rss 8650752
total_rss_huge 0
total_mapped_file 0
total_swap 0
total_pgpgin 86102783
total_pgpgout 86100665
total_pgfault 355263384
total_pgmajfault 0
total_inactive_anon 0
total_active_anon 8613888
total_inactive_file 8192
total_active_file 16384
total_unevictable 0
```

Docker version is `18.09`:
```
docker --version
Docker version 18.09.0, build 4d60db4
```

Also, running `docker stats` shows ~1GB memory consumption as well.

**Comment by proskehy** [comment] 2019-07-31 06:36
Update: upgraded Calico to `3.8` and the memory consumption is now in the expected 10s of MBs. I think we can close this, thank you for the support.

**Comment by zionwu** [comment] 2020-07-15 09:44
I have the same issue using calico 3.6.5 in a k8s cluster with 500+ nodes:
![image](https://user-images.githubusercontent.com/1213386/87530269-b1f80d00-c6c2-11ea-817a-5f1c4ffe000a.png)

**Comment by fasaxc** [comment] 2020-07-16 09:04
@zionwu Please upgrade to a a supported version, we believe this issue has already been fixed.

**Comment by zionwu** [comment] 2020-07-16 11:40
@fasaxc which version should I use?  the latest one 3.15? or 3.8?

**Comment by fasaxc** [comment] 2020-07-16 13:58
Only the most recent two releases are supported, I recommend upgrading to one of those.

**Comment by zionwu** [comment] 2020-07-17 01:58
@fasaxc Thank you!

**Comment by zionwu** [comment] 2020-07-21 07:48
@fasaxc I tried to deploy calico 3.15.1 on k8s 1.14.3, but have the following error:
```
unable to recognize "calico-typha.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```
It is because `apiextensions.k8s.io/v1` is not supported yet in k8s 1.14.3.

I wonder can I change the apiVersion in calico.yaml from `apiextensions.k8s.io/v1` to `apiextensions.k8s.io/v1beta`?

**Comment by fasaxc** [comment] 2020-07-21 08:08
The last release that supported v1.14 was Calico v3.12.  Maybe upgrade to that and then upgrade your k8s to v1.16.

**Comment by zionwu** [comment] 2020-10-13 09:41
It turns out calico v3.6.5 does not have memory leak issue. The large memory stats is caused by kmem issue https://github.com/kubernetes/kubernetes/issues/70324. 

Cadvisor is using the value of `/sys/fs/cgroup/memory/memory.usage_in_bytes`  as container memory usage and this value contains the value of `/sys/fs/cgroup/memory/memory.kmem.usage_in_bytes`. 

 With kmem issue,  value in  /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes is wrong and very large:
```bash
# kubectl exec -it calico-node-zng2w  -n kube-system sh
/ # cat /sys/fs/cgroup/memory/memory.usage_in_bytes
17915895808
/ # cat  /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes
17763127296

```

With kmem disabled, value in  /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes is 0 and the memory usage for calico container is normal:
```bash
# kubectl exec -it  calico-node-q9vz4    -n kube-system sh
/ #  cat /sys/fs/cgroup/memory/memory.usage_in_bytes
151412736
/ # cat  /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes
0


```

**Closed** 2020-10-15 18:32 UTC
Labels: kind/support
