### ISSUE TITLE
Add badges, or similar, to show what our supported platforms are

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/calico#7] opened 2016-08-18 15:23 UTC
It would be great to have something a little flashy on the front page with badges highlighting our support platforms (e.g. OpenStack Mitaka, Kubernetes XXX).  Not quite sure, though, how easy it will be to provide something concise (e.g. for OpenStack, technically we support icehouse, Kilo, Liberty and Mitaka).

**Comment by djosborne** [comment] 2016-11-03 23:01
Related to #124

**Comment by caseydavenport** [comment] 2017-02-14 21:30
We have badges like this on projectcalico.org, and a supported platforms page for the user docs.

Closing this as a duplicate of #124

**Closed by caseydavenport** 2017-02-14 21:30 UTC
Labels: area/organization, priority/P1, size/M
