### ISSUE TITLE
kube-controllers: Increased memory usage after update

### ISSUE THREAD

**Issue by fbsb** [projectcalico/calico#5037] opened 2021-10-28 13:26 UTC
After updating calico from version v3.19.1 to v3.20.2 we noticed the calico-kube-controller memory usage increased 
quite dramatically in our kubernetes clusters. 

small clusters (red, ~10 nodes): ~24MiB -> ~73MiB
medium clusters (blue, ~60 nodes): ~32MiB -> ~132MiB (peak 163MiB)
big clusters (yellow, ~300 nodes): ~64MiB -> ~800MiB (peak >1.2GiB)

![Screenshot from 2021-10-28 15-15-01](https://user-images.githubusercontent.com/8526438/139264481-4e6bacb0-d654-4e66-aea1-584f46079e72.png)
3

Also calico-node pods seem to have increased memory usage aswell but regardless of the cluster size ~200MiB -> ~600MiB

![Screenshot from 2021-10-28 15-26-08](https://user-images.githubusercontent.com/8526438/139264935-0152ff3e-1bbf-462e-af70-cb79c98a860a.png)

## Your Environment

* Calico version v3.20.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.20.11
* Operating System and version: Flatcar Container Linux by Kinvolk 2905.2.

**Comment by lmm** [comment] 2021-11-02 16:26
A possibly related issue that was reported recently: https://github.com/projectcalico/kube-controllers/issues/850

Could you please provide your kube-controllers logs if possible? (cc @caseydavenport since you were looking at that other issue)

**Comment by DockToFuture** [comment] 2021-11-09 13:16
Any updates on the issue? This looks exactly like the same issue we experience after updating our calico version from v3.19.1 to v3.20.2.

**Comment by caseydavenport** [comment] 2021-11-09 22:21
> Also calico-node pods seem to have increased memory usage aswell but regardless of the cluster size ~200MiB -> ~600MiB

This is likely the same leak that was recently fixed in v3.21, and will be fixed in the next v3.20 patch release. Reference: https://github.com/projectcalico/calico/issues/5018


There is a known leak in kube-controllers in v3.20, tracked here: https://github.com/projectcalico/kube-controllers/issues/850

@DockToFuture @fbsb can you confirm whether or not you see similar logs in your kube-controllers pod? Something like this would indicate it is likely the same issue as the one linked above:

```
2021-09-07 16:48:38.989 [ERROR][1] ipam.go 930: Failed to release block affinities for node calicoNode="ip-x-x-36-15.us-west-2.compute.internal" error=block '100.80.22.128/26' is not empty
2021-09-07 16:48:38.989 [WARNING][1] ipam.go 874: Error cleaning up node error=block '100.80.22.128/26' is not empty node="ip-x-x-36-15.us-west-2.compute.internal"
2021-09-07 16:50:00.909 [INFO][1] ipam.go 871: Cleaning up IPAM resources for deleted node node="ip-x-x-32-224.us-west-2.compute.internal"
2021-09-07 16:50:00.928 [INFO][1] ipam_block_reader_writer.go 300: Block must be empty but is not empty, refusing to remove affinity. host="ip-x-x-32-224.us-west-2.compute.internal" subnet="100.87.50.128/26"
2021-09-07 16:50:00.938 [ERROR][1] ipam.go 930: Failed to release block affinities for node calicoNode="ip-x-x-32-224.us-west-2.compute.internal" error=block '100.87.50.128/26' is not empty
2021-09-07 16:50:00.938 [WARNING][1] ipam.go 874: Error cleaning up node error=block '100.87.50.128/26' is not empty node="ip-x-x-32-224.us-west-2.compute.internal"
2021-09-07 16:50:00.938 [WARNING][1] ipam.go 252: error syncing IPAM data error=block '100.87.50.128/26' is not empty
```

**Comment by fbsb** [comment] 2021-11-12 10:25
Hi @caseydavenport, sorry for the delay. 

We see some errors in the logs of the kube-controllers similar to the ones mentioned. Also we see a lot of `Candidate IP leak` and `Confirmed IP leak after`. 

See [gist](https://gist.github.com/fbsb/4d948bd35dd9caf64efe26c41caa3fb5) for full logs.

Hope this helps.

**Comment by caseydavenport** [comment] 2021-11-16 00:03
@fbsb thanks for that gist - I don't see any ERROR level logs there, which might suggest something slightly different or a different trigger for the leak at least.

Can you confirm whether or not the IPs in the log are actually leaked, or if they are still in use by pods in the cluster? It's possible that the controller is doing the right thing, and cleaning up lots of IPs which have silently leaked over time.

**Comment by fbsb** [comment] 2021-11-16 13:59
Sorry, the gist seems to be truncated for some reasone. 

There are a lot more logs which contain errors like the ones mentioned above

```
2021-11-16 11:19:05.631 [WARNING][1] ipam_allocation.go 89: Confirmed IP leak handle="ipip-tunnel-addr-<redacted>" ip="100.71.56.0" node="<redacted>"
2021-11-16 11:30:18.646 [ERROR][1] ipam.go 931: Failed to release block affinities for node calicoNode="<redacted>" error=block '100.71.56.0/24' is not empty
2021-11-16 11:30:18.646 [WARNING][1] ipam.go 875: Error cleaning up node error=block '100.71.56.0/24' is not empty node="<redacted>"
2021-11-16 11:30:18.646 [WARNING][1] ipam.go 252: error syncing IPAM data error=block '100.71.56.0/24' is not empty
```

The handles seem to eventually get cleaned up and IPs freed, at least for the ones I checked.

**Comment by caseydavenport** [comment] 2021-12-16 20:04
@jwholme2 it looks like memory usage increases but stabilizes in your cluster? Or does it continue to grow?

Increases usage might be expected (although would be nice to trim it down, we added some new features that rely on more memory usage) - however continued growth is not expected.

**Comment by isugimpy** [comment] 2021-12-20 20:46
Memory usage over time below.  I'm experiencing the same issue.  Those spots where it falls off are when OOM kills happened.  The cluster this is from has ~400 nodes, not unreasonably large.  Seems a bit over the top to be using 90+GB of RAM.

![image](https://user-images.githubusercontent.com/14954499/146830358-2171feff-1338-4641-bd3f-1b3688e6e9e5.png)

**Comment by caseydavenport** [comment] 2021-12-21 17:12
@isugimpy yep agreed, that looks like a bug. 

Do you see any [ERROR] logs in your kube-controllers pods, like the ones mentioned above?

> 2021-11-16 11:30:18.646 [ERROR][1] ipam.go 931: Failed to release block affinities for node calicoNode="<redacted>" error=block '100.71.56.0/24' is not empty

**Comment by isugimpy** [comment] 2021-12-21 17:19
Sure do.  Looks like I've got around 5 or so an hour, with occasional bursts where we'll get 50-100 in an hour.

**Comment by caseydavenport** [comment] 2021-12-21 17:21
Awesome, thanks for the quick response. I am investigating this now and will report back with what I find.

**Comment by isugimpy** [comment] 2021-12-21 17:21
If you want, I've got the output of `calicoctl ipam check` handy, not sure if that'd help with diagnostics.  Though, I did run it with a slightly mismatched version, because I grabbed the 3.21 binary by accident.

**Comment by caseydavenport** [comment] 2021-12-21 17:23
@isugimpy that would be great actually. Would also be nice if possible to see if you could grab `kubectl get ipamblock -o yaml <name of block in error log>`. Appreciate the help.

**Comment by isugimpy** [comment] 2021-12-21 17:27
https://gist.github.com/isugimpy/10b25c03870ddcc90e7ba7cedb25c444  I've redacted a couple values (namespace and pod name) in the IPAMBlock, but otherwise these should be complete.

**Comment by caseydavenport** [comment] 2021-12-21 17:44
Does `kubectl get ipamhandle k8s-pod-network.ac8a318ba1dba17eb0a7ec6f863954464a7fadf7220d691a458c8209b1d1721f` return any results? 

Also, does the pod referenced by the IPAM block (redacted in the gist) actually exist or has it since been deleted?

**Comment by isugimpy** [comment] 2021-12-21 17:46
No results for the command, and the pod no longer exists.  In fact, the entire namespace no longer exists for that one.  I think it was deleted entirely around that time, though I would have to check our audit logs to confirm.

**Comment by caseydavenport** [comment] 2021-12-21 17:57
Gotcha, so that's definitely one problem - the IPAM handle is needed as a breadcrumb to clean up the actual allocation, and they seem to be inconsistent with each other (the handle is deleted, but the allocation is still there). That's probably confusing the GC. 

Still need to figure out why we're leaking memory when this happens, but that is most likely what is triggering this scenario. I will think about ways to recover from that.

**Comment by caseydavenport** [comment] 2021-12-21 20:20
So far I've been unable to reproduce this on my cluster but I will keep working at it. I'm also working on adding capability to generate pprof reports from kube-controllers so that we can dig into exactly where the memory usage is: https://github.com/projectcalico/calico/pull/5316/

**Comment by caseydavenport** [comment] 2021-12-23 17:22
I've pushed a kube-controllers image with pprof profiling support to `caseydavenport/kube-controllers:pprof` if anyone is interested in attempting to grab a profile from one of their clusters experiencing this issue.

In my image, profiling is enabled by default on port 8484. So you will need to:

1. Gain access to the port from your local machine, e.g., 
```
kubectl -n calico-system port-forward calico-kube-controllers-ABCD 8484:8484
```
2. Use curl to download the report:
```
curl http://localhost:8484/debug/pprof/heap > kube-ctrl.pprof
```

In the meantime, I'll keep seeing what I can do about reproducing this locally. Appreciate your help and patience :pray:

**Comment by caseydavenport** [comment] 2022-01-27 22:26
@isugimpy @fbsb @DockToFuture checking in on this one - did any of you guys managed to either resolve this or try the image with pprof enabled?

Also wondering if anyone has tried upgrading to v3.21.1+ - there were a pair of IPAM GC related fixes that went into that release:

- https://github.com/projectcalico/kube-controllers/pull/911
- https://github.com/projectcalico/kube-controllers/pull/901

The first was specifically to fix a memory leak scenario.

**Comment by isugimpy** [comment] 2022-01-27 22:28
Haven't been able to test with pprof.  I did just yesterday deploy 3.20.3 specifically for the second fix you mentioned though, still giving it some soak time to see if it solves one of our issues.  I'll keep an eye on memory too as we monitor this.

**Comment by caseydavenport** [comment] 2022-02-28 17:52
I'm going to close this due to inactivity and because a few fixes in this area have gone in recently. I will gladly re-open if someone shouts that this is still broken on the latest release (v3.22)

**Closed by caseydavenport** 2022-02-28 17:52 UTC
Labels: kind/bug, likelihood/high, impact/high
