### ISSUE TITLE
Documentation for running Calico+k8s on GCE without ipip

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#414] opened 2016-12-20 17:09 UTC
I was trying to figure out how to configure my kubernetes rig to run in GCE using calico and without ipip. 

I'm told that: "Calico policy works on top of GCE /24 of course and is a recommended way of real users running k8s with Calico on GCE. "  

But I'm not sure the current docs explain how to do this?

**Comment by djosborne** [comment] 2016-12-21 14:54
@caseydavenport or @lwr20 can you elaborate further? As an outsider I'm not sure what you mean.

**Comment by lwr20** [comment] 2016-12-21 15:11
I'm afraid I can't - all I know is that there's apparently a recommended way to run calico in GCE *without* IPinIP - but the docs don't talk about it.

**Comment by djosborne** [comment] 2016-12-21 16:33
Found this in a slack conversation:

>"Just install Kubernetes with the GCE cloud provider, and then self-hosted Calico with calico_backend=none"

**Comment by caseydavenport** [comment] 2017-01-03 21:32
You'll need:

#### Configure Kubernetes to program GCE cloud routes.
- Enable GCE cloud provider integration within k8s.
- Configure Kubernetes controller manager to assign pod CIDRs to nodes.

#### Configure Calico to do policy on top the GCE cloud routes.
- Use calico_backend=none to disable BIRD.
- Configure CNI config to use host-local IPAM with `subnet: usePodCidr`

**Comment by djosborne** [comment] 2017-04-03 23:20
I think this is essentially a dupe of #500

**Comment by caseydavenport** [comment] 2017-09-15 17:47
> I think this is essentially a dupe of #500

I think #500 is a dupe of this one, given the issue numbers :)

**Closed** 2020-05-13 17:54 UTC
Labels: area/documentation, orchestrator/k8s, priority/P2
