### ISSUE TITLE
Calico in eBPF mode interrupts node port traffic with external traffic policy of "Local" after a short delay

### ISSUE THREAD

**Issue by seh** [projectcalico/calico#4310] opened 2021-01-12 22:43 UTC
## Motivating Scenario

We have a server that runs in a Kubernetes pod, sitting behind a _Service_ of type "LoadBalancer" with an external traffic policy of "Local," using an AWS Network Load Balancer (NLB). This server uses an application-specific protocol over TCP that involves long-lived connections. Calico is using its eBPF dataplane with the VXLAN backend enabled.

Clients outside of the AWS VPC containing this Kubernetes cluster connect to the NLB and converse with the server for what we expect would be a very long time—on the order of several days.

## Expected Behavior
Clients should be able to connect to the server and continue exchanging packets over the same TCP connection until either party decides to shut the connection down gracefully by exchanging _FIN_-flagged packets.

## Current Behavior
Clients are able to connect to the server, but approximately nine or ten seconds after connecting, the client stops responding. After the client hasn't heard from the server for approximately ten seconds, the server attempts to close the connection.

The server accepts the connection and begins conversing with the client. Shortly afterward, though, the client's _PSH_-flagged TCP packets stop flowing, and the server retransmits these packets many times. Since the client hasn't heard from the server for a while, the client sends a _FIN_-flagged packet, but the server never acknowledges that packet, so the client continues retransmitting it for a while, trying to close the connection gracefully.

## Steps to Reproduce (for bugs)
1. Start a container running in a pod that can serve long-lived connections.
1. Create a _Service_ of type "LoadBalancer" using an external traffic policy of "Local."
1. Wait for the NLB's target group to settle on at least one target machine (one hosting a pod) to become healthy.
1. Connect to the server from a client.
1. Have them communicate for at least ten seconds, looking for signs of the connection hanging after around ten seconds.
1. Use _tcpdump_ on the machine hosting the target pod to monitor packet flow on both the _Service_ node port and on the pod's network interface (using the container port targeted by the _Service_ node port).
1. Observe a sequence of TCP retransmissions from the server after around ten seconds.
1. A few seconds later, observe a sequence of TCP retransmissions from the client.
1. Edit the _Service_ to change its external traffic policy to "Cluster."  
  Optionally constrain the set of registered target machines to only those hosting target pods via the "service.beta.kubernetes.io/aws-load-balancer-target-node-labels" annotation.
1. Repeat the client/server communication.
1. Observe that connections now stay healthy, and the client and server can communicate over a given TCP connection for as long as they choose.

## Findings
Consider the following scenario.
- Our client has IP address _147.75.66.3_.
- The machine hosting the target pod has IP address _10.2.5.46_.  
  This machine receives connections from the client on _Service_ node port 30270.
- The target pod has IP address _100.106.36.178_.  
  Its server container receives connections from the _Service_ node port on port 26658.

[Attached please find two _tcpdump_ PCAP files packed in a ZIP archive](https://github.com/projectcalico/calico/files/5805190/pcap.zip):
- _eth0-port-30270.pcap_  
  This is the machine hosting the target pod's primary network interface "eth0" on the node port 30270.
- _cali-port-26658.pcap_  
  This is "cali*" container-level interface used by the target pod, discovered via _ip route get \<pod IP address\>_.

If you use _Wireshark_'s "Merge" feature, you can look at these two files together and see the relationship between the TCP streams on the two network interfaces. I found it convenient to find a bunch of _PSH_-flagged TCP retransmissions from the server on port 26558, noting both the source port (e.g. 43452) and the duration from when the connection was established (again, usually around 9-10 seconds), and then finding the related TCP stream from the client to the node port (with a filter like `ip.src == 10.2.5.46 and tcp.port == 43452`). There you should find a bunch of _FIN_-flagged TCP retransmissions around ten seconds later, though in a few cases the delay is much shorter.

## Context
We have some servers that choose to use the "Local" external traffic policy in order to eliminate network hops when receiving node port traffic. Due to this defect, these servers can't carry on the conversations they're supposed to support.

This problem came up for discussion [in the "kubernetes" channel of the "Calico Users" Slack workspace](https://calicousers.slack.com/archives/C0BCA117T/p1610403052080400).

## Your Environment
 **Cloud Provider:** AWS EC2 ("us-east-2" region, VPC networking)
* **Calico version:** 3.17.1 (as deployed by _kops_ 1.19.0-beta.3)  
* **Orchestrator version:** Kubernetes 1.19.5
* **Operating System and version:** Flatcar Container Linux  
<details>
<summary>/etc/os-release</summary>

```
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2705.1.0
VERSION_ID=2705.1.0
BUILD_ID=2020-11-30-1851
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2705.1.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```

**Comment by seh** [comment] 2021-01-12 22:48
Note that despite trying as hard as I could, I could not reproduce this problem using a common NGINX "echo" container as the server. I tried using [the _bombardier_ HTTP client](https://github.com/codesenberg/bombardier) to use a single TCP connection for as long as 30 seconds, inducing traffic to flow back and forth the whole time. That client and server pair worked flawlessly, as far as I could tell: _tcpdump_ recorded no retransmitted packets, at least per _Wireshark_'s subsequent interpretation.

**Comment by seh** [comment] 2021-01-13 01:29
It occurred to me after writing about _bombardier_ that NGINX was closing these connections after five or six seconds, such that a thirty-second-long test actually wound up using five or six separate connections. I could only see that in Wireshark afterward, as _bombardier_ never complained about needing to open a replacement connection.

If that's true, then this test lacks sufficient fidelity. These connections would need to be open for a few more seconds to meet that [ten-second conntrack cleanup period](https://sourcegraph.com/github.com/projectcalico/felix/-/blob/bpf/conntrack/cleanup.go#L40-L50) that we learned of in #2589 (pursuing the similar-sounding #4146).

**Comment by song-jiang** [comment] 2021-01-14 17:52
Ping @shaun for labelling this one.

**Comment by caseydavenport** [comment] 2021-02-25 17:20
@song-jiang I think you meant to ping @fasaxc.

**Comment by song-jiang** [comment] 2021-02-25 17:43
ping @fasaxc to label this issue.

**Comment by fasaxc** [comment] 2021-02-26 10:35
@seh I've lost track of this one, are you still seeing it after the other fixes we made?

**Comment by seh** [comment] 2021-02-26 13:27
Fortunately, I haven't been able to reproduce this problem since this original investigation. Let's close this, and if the problem comes back, I'll reopen it with new detail.

**Comment by fasaxc** [comment] 2021-02-26 14:03
FWIW, we have improved handling of pre-existing connections in v3.18.  They shouldn't be broken by turning on BPF mode.

**Comment by seh** [comment] 2021-04-09 18:18
We've been running into this problem again lately using Calico version 3.17.3. We intend to test it with Calico version 3.18.1 within the next few days.

**Comment by fasaxc** [comment] 2021-04-12 09:02
@seh any more insight into what scenario causes this?

**Comment by seh** [comment] 2021-04-12 12:13
What I've noticed this again time is that the connections succeed, but then get cut off after around 10 seconds, the EC2 load balancer is an NLB, and that switching the _Service_'s external traffic policy from "Local" to "Cluster" fixes the problem immediately. It's a different container image and protocol from my last encounter with this back in January, so I can't blame the server program, unless these two different programs happen to be doing something similarly odd.

**Comment by tomastigera** [comment] 2021-04-12 17:48
@fasaxc I wonder if this is realted to the issue with RPF check, local forwarding and multiple ENIs

**Comment by fasaxc** [comment] 2021-04-16 14:39
@seh Do you use multiple ENIs on your hosts (e.g. by using Amazon VPC CNI)?

**Comment by seh** [comment] 2021-04-16 14:40
No, we don't. Each of these machines has only one ENI.

**Comment by seh** [comment] 2021-05-26 14:46
This is occurring for us again, with a _Service_ that works fine with an external traffic policy of "Cluster," but that suffers these same interruptions with a policy of "Local." As before, these machines have only one ENI.

**Comment by salanki** [comment] 2021-07-19 22:41
This seems somewhat similar to https://github.com/projectcalico/calico/issues/4431

**Comment by tomastigera** [comment] 2021-09-23 18:08
@seh I finally got to the bottom of this issue. I am closing this issue as a duplicate of #4431.

**Closed by tomastigera** 2021-09-23 18:08 UTC
Labels: kind/bug, likelihood/high, impact/high
