### ISSUE TITLE
Unable to upgrade  tigera operator from 3.23.1 to 3.26.3

### ISSUE THREAD

**Issue by mukulgit123** [projectcalico/calico#8202] opened 2023-11-10 20:18 UTC
## Expected Behavior
Expected the tigera operator to be upgraded seemlessly from 3.23.1 to 3.26.3 by following the upgrade steps at https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#all-other-upgrades

## Current Behavior

Following error is encountered while trying to upgrade the operator:

Commands used:

```
kubectl apply --server-side --force-conflicts -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/operator-crds.yaml

helm upgrade calico-operator projectcalico/tigera-operator -n kube-system
```
Error encountered:
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "tigera-operator" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

## Possible Solution
No possible solution or work around available.  However, below solutions have been tried so far.

1. Delete calico helm release. However, it doesn't help as it has a finalizer related to installation custom resource and deleting installation custom resource might remove our additional ippool as well.
2. Created a new cluster and reproduced the exact scenario on a fresh cluster as well performing the same steps. 

## Steps to Reproduce (for bugs)

1. Install Calico 3.23.1 on EKS version 1.24
3. Upgrade EKS cluster to version 1.26
4. Try running below commands to upgrade tigera operator.

```
kubectl apply --server-side --force-conflicts -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/operator-crds.yaml

helm upgrade calico-operator projectcalico/tigera-operator -n kube-system
```

5. Observe the error below:

```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "tigera-operator" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

## Context
Many of our non prod and prod clusters are already upgraded to 1.26 . All these clusters have atleast one additional ippool. Hence deleting everything doesn't seem like a viable solution at this point. 

## Your Environment

* Calico version - 3.23.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.26
* Operating System and version: EKS with Ubuntu Nodes and version 1.26

**Comment by caseydavenport** [comment] 2023-11-13 19:45
After some googling, I've found a few issues that seem to suggest the issue is helm itself not being smart enough to know that the API has been removed:

- https://community.okteto.com/t/upgrade-failed-with-no-matches-for-kind-podsecuritypolicy-in-version-policy-v1beta1/802/2
- https://access.redhat.com/solutions/7021913
- https://docs.microfocus.com/doc/OMT/2022.11/PSPErrors

helm caches resources for each release in a secret in the cluster, and that secret still references the PSP. I think that leave us with a few options to explore:

- When performing the upgrade, make sure to install the new version of the tigera-operator helm chart prior to upgrading EKS. This way, the PSP will be removed prior to the API being removed.
- Manually edit the helm secret for your release to remove the PSP, since we know it is no longer present in the cluster.
- Delete the secret for your release entirely and run helm install with the exact same name again

**Comment by caseydavenport** [comment] 2023-11-13 20:03
As expected, this turned out to be a helm bug where the helm tooling is expecting a PSP to exist due to the contents of the Secret it creates for each release.

It can be resolved by deleting the secret for the Calico helm release installed on the cluster, and then re-running `helm install` with the same parameters. **Note: Do not run helm uninstall, just delete the secret by hand**.

1. Delete the secret (replacing name/namespace as needed and the --dry-run flag when ready)
   ```
   kubectl delete secret -n tigera-operator -l name=calico,owner=helm --dry-run
   ```
2. `helm install` using the original name

**Closed by caseydavenport** 2023-11-13 20:03 UTC
Labels: kind/support
