### ISSUE TITLE
After adding new nodes, the network between pods does not work correctly

### ISSUE THREAD

**Issue by VA-PLE** [projectcalico/calico#6575] opened 2022-08-18 09:01 UTC
## Expected Behavior

Pod-to-pod communication should work and pods should be able to reach external networks such as hosts on the Internet

## Current Behavior

pods can only reach pods on the same node, and not pods on other nodes or external networks (connections are dropped after timeout)

## Context

After adding new nodes, the network between pods does not work correctly (on new nodes), very high latency, connections are dropped after timeout:
BAD nodes:
```
bash-5.1# curl http://api-gateway.bm-us-was-prod.svc.cluster.local:9000
curl: (6) Could not resolve host: api-gateway.bm-us-was-prod.svc.cluster.local

bash-5.1# curl google.com
curl: (6) Could not resolve host: google.com

bash-5.1# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=14.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=14.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=14.5 ms
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 14.445/14.450/14.453/0.003 ms

bash-5.1# ping 10.233.62.213
PING 10.233.62.213 (10.233.62.213) 56(84) bytes of data.
64 bytes from 10.233.62.213: icmp_seq=1 ttl=64 time=0.041 ms
64 bytes from 10.233.62.213: icmp_seq=2 ttl=64 time=0.031 ms
64 bytes from 10.233.62.213: icmp_seq=3 ttl=64 time=0.029 ms
--- 10.233.62.213 ping statistics ---
4 packets transmitted, 3 received, 0% packet loss, time 3078ms
rtt min/avg/max/mdev = 0.024/0.031/0.041/0.006 ms

bash-5.1# dig api-gateway.bm-us-was-prod.svc.cluster.local
; <<>> DiG 9.16.20 <<>> api-gateway.bm-us-was-prod.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached

bash-5.1# dig google.com
; <<>> DiG 9.16.20 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17346
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A
;; ANSWER SECTION:
google.com.             30      IN      A       142.251.39.110
;; Query time: 0 msec
;; SERVER: 169.254.25.10#53(169.254.25.10)
;; WHEN: Wed Aug 17 10:37:12 UTC 2022
;; MSG SIZE  rcvd: 65

bash-5.1# curl google.com
curl: (6) Could not resolve host: google.com

bash-5.1# cat /etc/resolv.conf
search bm-us-was-prod.svc.cluster.local svc.cluster.local cluster.local default.svc.cluster.local
nameserver 169.254.25.10
options ndots:5

bash-5.1# nslookup kubernetes.default
;; connection timed out; no servers could be reached

bash-5.1# nmap 10.233.0.3 -p53 -sT -sU
Starting Nmap 7.91 ( https://nmap.org ) at 2022-08-18 08:53 UTC
Nmap scan report for 10.233.0.3
Host is up (0.00012s latency).

PORT   STATE SERVICE
53/tcp open  domain
53/udp open  domain

Nmap done: 1 IP address (1 host up) scanned in 13.18 seconds
```

Nodelocaldns logs BAD nodes:
```
2022/08/17 10:55:04 [INFO] Starting node-cache image: 1.21.1
2022/08/17 10:55:04 [INFO] Using Corefile /etc/coredns/Corefile
2022/08/17 10:55:04 [INFO] Using Pidfile 
2022/08/17 10:55:04 [ERROR] Failed to read node-cache coreFile /etc/coredns/Corefile.base - open /etc/coredns/Corefile.base: no such file or directory
2022/08/17 10:55:04 [INFO] Skipping kube-dns configmap sync as no directory was specified
2022/08/17 10:55:04 [INFO] Added interface - nodelocaldns
cluster.local.:53 on 169.254.25.10
in-addr.arpa.:53 on 169.254.25.10
ip6.arpa.:53 on 169.254.25.10
.:53 on 169.254.25.10
[INFO] plugin/reload: Running configuration MD5 = adf97d6b4504ff12113ebb35f0c6413e
CoreDNS-1.7.0
linux/amd64, go1.16.8, 
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 6135315722116011608.611466303435741516.ip6.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 5304487033949309265.7264781733226064609.cluster.local. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 2270136763483407723.5767495469467330511.in-addr.arpa. HINFO: dial tcp 10.233.0.3:53: i/o timeout
[INFO] Added back nodelocaldns rule - {raw PREROUTING [-p tcp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw PREROUTING [-p udp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {filter INPUT [-p tcp -d 169.254.25.10 --dport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {filter INPUT [-p udp -d 169.254.25.10 --dport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -s 169.254.25.10 --sport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p udp -s 169.254.25.10 --sport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {filter OUTPUT [-p tcp -s 169.254.25.10 --sport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {filter OUTPUT [-p udp -s 169.254.25.10 --sport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p udp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -d 169.254.25.10 --dport 8080 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -s 169.254.25.10 --sport 8080 -j NOTRACK]}
[ERROR] plugin/errors: 2 api-gateway.bm-us-was-prod.svc.cluster.local. A: dial tcp 10.233.0.3:53: i/o timeout
```

## Your Environment

* Calico version 3.22.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.23.7
* Operating System and version: Ubuntu 20.04.4
* Link to your project (optional):

I checked the network on the servers, everything works correctly, I tried to disable the firewall, reinstall the nodes, but nothing helps. Please tell me how I can solve this problem

**Comment by mgleung** [comment] 2022-08-23 16:54
Hey @VA-PLE , usually these sorts of issues seem to be caused by firewall rules (like you've already investigated) and IP auto detection issues. Can I ask you if you're configured to use IP autodetection (usually it's on by default) and if so, can you check your logs to see which interface was selected? What could be happening is that IP autodetection is finding the wrong network interface on the new node and that interface doesn't have connection to your network, which is why the pods who would use that interface cannot access other nodes or the internet.

**Comment by mgleung** [comment] 2022-09-06 16:10
Hey @VA-PLE , I'm going to close this issue since we haven't had any movement on it for a couple weeks. Please shout out if your issue persists and I'll reopen the issue.

**Closed by mgleung** 2022-09-06 16:10 UTC
