### ISSUE TITLE
Support multiple IP addresses for "cni.projectcalico.org/ipAddrs" 

### ISSUE THREAD

**Issue by zionwu** [projectcalico/calico#4219] opened 2020-11-25 03:03 UTC
Currently, we can use "cni.projectcalico.org/ipAddrs" to specify a fixed IP for a pod. 
In our use case, We would like to have fixed IPs for a deployment with replica more than 1. Could Calico support multiple IP addresses for "cni.projectcalico.org/ipAddrs" in the future?

**Comment by caseydavenport** [comment] 2020-11-25 17:44
Closing as a duplicate of https://github.com/projectcalico/cni-plugin/issues/771

**Closed by caseydavenport** 2020-11-25 17:44 UTC
