### ISSUE TITLE
Large packet loss percentage using Calico

### ISSUE THREAD

**Issue by wsbondie** [projectcalico/calico#3043] opened 2019-12-04 22:24 UTC
## Expected Behavior

Packet loss percentage is not significantly larger when using Calico on the k8s cluster.

## Current Behavior

When running iperf over a k8s cluster(>50 nodes), and testing node to node, I am seeing a ~3-8% packet loss. Without Calico (across node instances) the loss percentage is ~0.02-0.07%.

I am testing using iperf transmitting 100k TCP packets with an MTU of 40 bytes.

## Your Environment

* Calico version: 3.8.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: CentOS Linux 7 (Core)

**Comment by wsbondie** [comment] 2019-12-04 22:30
Testing this on a cluster with only 5 nodes yielded ~3-6% packet loss.

**Comment by fasaxc** [comment] 2019-12-06 14:35
Is network-manager interfering with Calico? https://docs.projectcalico.org/v3.10/maintenance/troubleshooting#configure-networkmanager

**Comment by matthias50** [comment] 2019-12-06 16:06
@fasaxc, I am on the same team as @wsbondi. We are not using network manager.

```
# systemctl status NetworkManager.service
Unit NetworkManager.service could not be found.
```

**Comment by fasaxc** [comment] 2019-12-06 16:30
Unless 100k packets/s is the absolute limit of your host-to-host link (so that the slight overhead of veths causes it to tip over into dropping traffic), that sounds like a problem.

Please can you share the details of your set up?  Where are you doing this testing?  On prem?

**Comment by matthias50** [comment] 2019-12-06 16:37
We are testing in the AWS region eu-west-1 using r4.8xlarge instance types.

**Comment by fasaxc** [comment] 2019-12-09 09:18
Please can you provide the details of how you've configured Calico?  IP pools, networking mode (IPIP VXLAN, cross-subnet mode or not), etc. v3.10.x is the current stable release, does it still occur with that?

**Comment by fasaxc** [comment] 2019-12-09 09:26
If you do `ip monitor` on the hosts while doing your iperf test, do the iperf outages correlate with `ip monitor` output?

**Comment by wsbondie** [comment] 2019-12-13 16:19
@fasaxc 
We are using one IP Pool with an IPIP mode of Always. natOutgoing set to true.
Here is a log of "ip monitor" on the host of the iperf test.

10.121.5.81 dev eth0 lladdr 06:f5:55:60:f7:e4 REACHABLE
10.121.5.91 dev eth0 lladdr 06:d4:27:3e:7d:2e STALE
10.121.5.91 dev eth0 lladdr 06:d4:27:3e:7d:2e PROBE
10.121.5.91 dev eth0 lladdr 06:d4:27:3e:7d:2e REACHABLE
10.121.5.107 dev eth0 lladdr 06:1b:26:c1:66:bc STALE
100.123.134.66 dev calicb251b0404d lladdr 12:fd:b0:95:43:7c PROBE
100.123.134.66 dev calicb251b0404d lladdr 12:fd:b0:95:43:7c REACHABLE
ipv4 dev cali9c864386110 forwarding on rp_filter strict mc_forwarding off proxy_neigh off ignore_routes_with_linkdown off
ipv6 dev cali9c864386110 forwarding off mc_forwarding off proxy_neigh off ignore_routes_with_linkdown off
nsid 6
22: cali9c864386110@if4: <BROADCAST,MULTICAST> mtu 1440 qdisc noop state DOWN group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 6
ipv4 dev cali9c864386110 proxy_neigh on
22: cali9c864386110@if4: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state LOWERLAYERDOWN group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 6
100.123.134.72 dev cali9c864386110 scope link
22: cali9c864386110@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 6
10.121.5.96 dev eth0 lladdr 06:82:6b:41:58:02 STALE
100.123.134.68 dev cali65b57749537 lladdr a6:53:8b:b4:79:49 STALE
10.121.5.107 dev eth0 lladdr 06:1b:26:c1:66:bc PROBE
10.121.5.107 dev eth0 lladdr 06:1b:26:c1:66:bc REACHABLE
100.123.134.72 dev cali9c864386110 lladdr 7e:69:56:4e:23:29 REACHABLE
100.123.134.67 dev calid34ce5defa9 lladdr f6:a1:36:6e:e3:de STALE
100.123.134.67 dev calid34ce5defa9 lladdr f6:a1:36:6e:e3:de PROBE
10.121.5.96 dev eth0 lladdr 06:82:6b:41:58:02 PROBE
100.123.134.67 dev calid34ce5defa9 lladdr f6:a1:36:6e:e3:de REACHABLE
10.121.5.96 dev eth0 lladdr 06:82:6b:41:58:02 REACHABLE
10.121.5.119 dev eth0 lladdr 06:21:af:38:cd:90 STALE
10.121.5.81 dev eth0 lladdr 06:f5:55:60:f7:e4 STALE
100.123.134.68 dev cali65b57749537 lladdr a6:53:8b:b4:79:49 PROBE
100.123.134.68 dev cali65b57749537 lladdr a6:53:8b:b4:79:49 REACHABLE
10.121.5.119 dev eth0 lladdr 06:21:af:38:cd:90 PROBE
10.121.5.119 dev eth0 lladdr 06:21:af:38:cd:90 REACHABLE
100.123.134.66 dev calicb251b0404d lladdr 12:fd:b0:95:43:7c STALE
22: cali9c864386110@NONE: <BROADCAST,MULTICAST> mtu 1440 qdisc noqueue state DOWN group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff
Deleted 100.123.134.72 dev cali9c864386110 lladdr 7e:69:56:4e:23:29 REACHABLE
Unknown message: type=0x00000051(81) flags=0x00000000(0)len=0x0000001c(28)
Unknown message: type=0x00000051(81) flags=0x00000000(0)len=0x0000001c(28)
Deleted 22: cali9c864386110@NONE: <BROADCAST,MULTICAST> mtu 1440 qdisc noop state DOWN group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff
Deleted nsid 6

**Comment by caseydavenport** [comment] 2020-02-19 18:13
Any updates on this one?

Also as @fasaxc pointed out, v3.8 is a bit long in the tooth now. Have you tried reproducing on a newer version of Calico?

**Comment by fasaxc** [comment] 2020-03-03 09:18
I don't see any route flaps in the `ip monitor` trace; which was one guess for what could have been causing connectivity blips.  Are there other firewall tools running?  For example `firewalld`?

**Comment by tmjd** [comment] 2020-04-27 20:21
Closing since we don't have any new information on this. If you can provide new information please do and we can reopen. Thanks.

**Closed by tmjd** 2020-04-27 20:21 UTC
