### ISSUE TITLE
Unable to match pods in a calico network policy, when they have host networking enabled

### ISSUE THREAD

**Issue by DavidDarville** [projectcalico/calico#4667] opened 2021-06-10 12:41 UTC
When trying to write a calico network policy, I am unable to get the selector to work, if the pod has host networking enabled.

## Expected Behavior

I am trying to create an egress rule, to allow a pod to contact the apiserver, I expected this policy to work:

    apiVersion: projectcalico.org/v3
    kind: NetworkPolicy
    metadata:
      name: sealed-secrets
      namespace: sealed-secrets
    spec:
      selector:
        app.kubernetes.io/name == 'sealed-secrets'  - action: Allow
      protocol: TCP
      egress:
        destination:
          selector: k8s-app == 'kube-apiserver'
          namespaceSelector: projectcalico.org/name == 'kube-system'
          ports:
          - 443

## Current Behavior

When I apply the network policy listed above, it does not work, and I see that the iptables match, is using an empty ipset.

## Possible Solution

I have found a possible workaround, by enabling automatic host endpoints, and then matching on the master node instead, using this config snippet:

    - action: Allow
      protocol: TCP
      destination:
        selector: kubernetes.io/role == 'master'
        namespaceSelector: global()
        ports:
        - 443

## Context

But using the work around is counter-intuitive.
So I propose that Calico will be updated, to enable first policy to work.

## Your Environment

* Calico version
    % calicoctl version
    Client Version:    3.19.1
    Git commit:        6fc0db96
    Cluster Version:   v3.19.1
    Cluster Type:      kops,bgp,kdd,k8s
* Operating System and version:
Ubuntu 20.04

**Comment by lwr20** [comment] 2021-06-15 16:20
When a pod is running host-networked, its running in the host's network namespace.  i.e. it is a process running on the host and no longer a pod-networked pod.  So is it not intuitive that you would need to use a host policy to control that case?

As it says in the warning here: https://docs.okd.io/latest/networking/network_policy/about-network-policy.html 
> Network policy does not apply to the host network namespace. Pods with host networking enabled are unaffected by network policy rules.

**Comment by lwr20** [comment] 2021-06-15 16:26
Regardless, this is an enhancement request, and looks like a dupe of https://github.com/projectcalico/calico/issues/1987

I'm going to close this in favour of 1987

**Closed by lwr20** 2021-06-15 16:26 UTC
