### ISSUE TITLE
Error when Calico cni plugin create container network: Get "https://10.96.0.1:443/apis/crd.projectcalico.o rg/v1/clusterinformations/default": Tunnel Connection Failed

### ISSUE THREAD

**Issue by wangjianwen** [projectcalico/calico#8426] opened 2024-01-22 11:27 UTC
## Expected Behavior
After created the  crd by command
`kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml`, 

each pod in calico-system has the STATUS of Running.

## Current Behavior
The pod controlled by DaemonSet csi-node-driver is always containerCreating.

```
NAME                                       READY   STATUS              RESTARTS   AGE
calico-kube-controllers-5bc86ff475-lrpbv   0/1     Pending             0          7h34m
calico-node-k4fnn                          1/1     Running             0          7h34m
calico-typha-6dd64f667c-v8xjc              1/1     Running             0          7h34m
csi-node-driver-72tts                      0/2     ContainerCreating   0          7h34m
```

View the log of cni （`/var/log/calico/cni/cni.log`）:

```
2024-01-21 09:33:41.440 [ERROR][18061] plugin.go 163: Final result of CNI ADD was an error. error=error getting ClusterInformation: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": Tunnel Connection Failed
... ...
```

`systemctl restart containerd
journalctl -f -u containerd
`

```
Jan 23 07:03:18 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:18.773098083+08:00" level=error msg="StopPodSandbox for \"43cae72852fc955d5806e04a2c81375b6f458ab2997334a5be9b663419147ae1\" failed" error="failed to destroy network for sandbox \"43cae72852fc955d5806e04a2c81375b6f458ab2997334a5be9b663419147ae1\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": Tunnel Connection Failed"
Jan 23 07:03:19 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:19.448089387+08:00" level=error msg="StopPodSandbox for \"1c127a78925da67c3920511d3f99bf4b27681cc7434a042667bac9a13f02a36d\" failed" error="failed to destroy network for sandbox \"1c127a78925da67c3920511d3f99bf4b27681cc7434a042667bac9a13f02a36d\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": Tunnel Connection Failed"
Jan 23 07:03:20 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:20.443735594+08:00" level=info msg="StopPodSandbox for \"1c127a78925da67c3920511d3f99bf4b27681cc7434a042667bac9a13f02a36d\""
Jan 23 07:03:25 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:25.737827376+08:00" level=error msg="StopPodSandbox for \"7e3ecd2ba7203a7410789d04fa4ec09ace7b9d3bd70b95ac0ba58b629a3fd1c1\" failed" error="failed to destroy network for sandbox \"7e3ecd2ba7203a7410789d04fa4ec09ace7b9d3bd70b95ac0ba58b629a3fd1c1\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": Tunnel Connection Failed"
Jan 23 07:03:27 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:27.778740691+08:00" level=error msg="StopPodSandbox for \"d19f0db4c2a7269f9347ed45836b12c85831402b94aade6bb556edd5b6d30d5d\" failed" error="failed to destroy network for sandbox \"d19f0db4c2a7269f9347ed45836b12c85831402b94aade6bb556edd5b6d30d5d\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": Tunnel Connection Failed"
Jan 23 07:03:30 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:30.703463200+08:00" level=info msg="StopPodSandbox for \"43cae72852fc955d5806e04a2c81375b6f458ab2997334a5be9b663419147ae1\""
Jan 23 07:03:30 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:30.960458142+08:00" level=info msg="StopPodSandbox for \"41465fd6abcb7fdda25ff24ea712e52fdf9ddc64fad69d5339a2c83730a54909\""
Jan 23 07:03:35 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:35.510111217+08:00" level=error msg="StopPodSandbox for \"1c127a78925da67c3920511d3f99bf4b27681cc7434a042667bac9a13f02a36d\" failed" error="failed to destroy network for sandbox \"1c127a78925da67c3920511d3f99bf4b27681cc7434a042667bac9a13f02a36d\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": Tunnel Connection Failed"
Jan 23 07:03:36 chuangyiyuan-10-17-8-82 containerd[15400]: time="2024-01-23T07:03:36.490207345+08:00" level=info msg="StopPodSandbox for \"1c127a78925da67c3920511d3f99bf4b27681cc7434a042667bac9a13f02a36d\""
```

## Possible Solution

`cat /etc/cni/net.d/10-calico.conflist`

```json
{
                          "name": "k8s-pod-network",
                          "cniVersion": "0.3.1",
                          "plugins": [{"container_settings":{"allow_ip_forwarding":false},"datastore_type":"kubernetes","ipam":{"assign_ipv4":"true","assign_ipv6":"false","type":"calico-ipam"},"kubernetes":{"k8s_api_root":"https://10.96.0.1:443","kubeconfig":"/etc/cni/net.d/calico-kubeconfig"},"log_file_max_age":30,"log_file_max_count":10,"log_file_max_size":100,"log_file_path":"/var/log/calico/cni/cni.log","log_level":"Info","mtu":0,"nodename_file_optional":false,"policy":{"type":"k8s"},"type":"calico"},{"capabilities":{"bandwidth":true},"type":"bandwidth"},{"capabilities":{"portMappings":true},"snat":true,"type":"portmap"}]
}
```

cat /etc/cni/net.d/calico-kubeconfig

```yaml
# Kubeconfig file for Calico CNI plugin. Installed by calico/node.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://10.96.0.1:443
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQjh3N2tLWUswOWt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1qSXdOalU0TURsYUZ3MHpOREF4TVRrd056QXpNRGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN3dytQN2R6RGVDc205RCtSc1JrN2xaLy9LWWRKTG1KcXdCbC9HN1Vac0VsNGcxMEM2dllieHlpQ2gKd1pFUTVyS3FnSVFra3RtcHlTbjZOclBPRkFCcEFvZXVNamJUWHZuUndtQnRBUzBjUWZGcXdqQmQ3VGpxN2VVbQpFVWFDYVR3bisxaHB6MXRZeG02MUFLKzJGeVJuazVtYW9FRU13aUZhdllHUkU5Qm9KbmgwN0NkUjdoVWs0eTFHCk5WcUczY3ltRW91VnNWS0ZOdEZvaXJXK2ZHMlZMSmhXTkxQcXd4anFIUXpRZ09oSlNRZlZ4SkhrQjQ4ckNMc2QKS1FvZ0s3SXkvSlhyNjR2emRTRE1YSFJKOFlBY2o1dGZXOHlISFd1aDVpQUZwQldZd3JCOC9tNzNWS3BFRHFHdAp0UFczdFVPdUpJc2R1NDJXSjBER3plSGdwU3RCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSV0hlZDFKck4wZytjQmFRbnM1L1NQWVp6b1BqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1Jvd0F1K1FjeAovM1E0QVJKbDRKM1FBL3BjMTQ1S205SUNwdTZXV0FPcGpwMk51TmRmQktSUnhnUXQ4TS96NkxGbURlYW1jOG5UCnhBRW5kY3hzZ3kyZVU1TWplWDBiMTZ6ZWtLSlUrd3AwNlR5aFJGY1BPdWpZR0tnRlA2VlYrMElmTkQwakYzeUkKMUdacStMMzVwcy9NSUMzMjBxT3htN2lLeVdOMVY4Q1lucWs5eFBJd0JKMEI0NDVscnFyVUphVDFoeVZSUWJuVwpyT0JIS1hnYTQySU1XZjFpNjlWalJRc1UwSWxPcDI4WUszSHFxU3JReUJXMTdVdVJlbjAySkVzeGpPSmtmK1E1CkZkK0lSMnd6VDVrbUtBRTNndWR6QmhUMi8xM054OEJwZHJhNDhtc2drZTQyMVNoclpXUldWc3JWTzQ5WmhZSkEKWmM2enBsaHFZbjFGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
users:
- name: calico
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImdMTXdaZUh1TUhHRFdTRUtNY3Zyb1RUcURMRzczbnRyRXRldjJpOXQ4S3MifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzA1OTkzNDkzLCJpYXQiOjE3MDU5MDcwOTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJjYWxpY28tc3lzdGVtIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImNhbGljby1jbmktcGx1Z2luIiwidWlkIjoiMDY2ODJmZmEtMWI2ZC00MDQ1LTljNjktNjM3NDU5ZGZjYzEyIn19LCJuYmYiOjE3MDU5MDcwOTMsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYWxpY28tc3lzdGVtOmNhbGljby1jbmktcGx1Z2luIn0.dGwVA7hIKv5zoxQS3gfbTaISUQ43q9_S09U2oDyrBuvC6Eaei2xBrW73QT2RsVo0guX_hDUYn3v8wATOcl2Z6RqW9eKE41m2tdMTeHtnYfekBQ4oAChdCSNFxqC11XUIGSp-454Wq2ALyOoOgQM3Yv88SaeiaNkA6oFXu-wKCkfCVM-EILIrY_u5lMN-rO2r6AF40b72fcbahoRlZdeTNgHViySL89e5ivMlcrBOvOnpLdcz0uYQaD_LSehlTL_sCBOqNUUSkKlYmEQmMJzH0Nz_PeRqr6mL6CXJu9fZMIdxXMGwKfKcdMZRcoUwI2_PSYiFgeIpXdFAOztKDONpMQ
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
```

If I modified the  file `/etc/cni/net.d/10-calico.conflist` after changed 10.96.10.1:443 to 10.17.8.82:6443 (the advertiseAddress)，the problem is solved

## Steps to Reproduce (for bugs)

1.  kubeadm int --pod-network-cidr=10.243.0.0/16
2.  kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
3. kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml
4. kubectl get pods -n calico-system

```
NAME                                       READY   STATUS              RESTARTS   AGE
calico-kube-controllers-5bc86ff475-lrpbv   0/1     Pending             0          7h34m
calico-node-k4fnn                          1/1     Running             0          7h34m
calico-typha-6dd64f667c-v8xjc              1/1     Running             0          7h34m
csi-node-driver-72tts                      0/2     ContainerCreating   0          7h34m
```

## Your Environment

* Calico version : 3.27
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.28.2， containerd 1.6.24
* Operating System and version: CentOS Linux release 7.5.1804 (Core)

**Comment by sridhartigera** [comment] 2024-01-23 17:35
@wangjianwen Looks like the pods cannot reach the apiserver via the service. Can you confirm if kube-proxy is running?

**Comment by wangjianwen** [comment] 2024-01-24 06:05
> @wangjianwen Looks like the pods cannot reach the apiserver via the service. Can you confirm if kube-proxy is running?
Thanks for your reply.  The kube-proxy is running.

`kubectl logs -n kube-system kube-proxy-7m6h6`

```
I0123 02:58:03.348377       1 server_others.go:69] "Using iptables proxy"
I0123 02:58:03.357100       1 node.go:141] Successfully retrieved node IP: 10.17.8.82
I0123 02:58:03.360360       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=393216
I0123 02:58:03.379299       1 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
I0123 02:58:03.381007       1 server_others.go:152] "Using iptables Proxier"
I0123 02:58:03.381032       1 server_others.go:421] "Detect-local-mode set to ClusterCIDR, but no cluster CIDR for family" ipFamily="IPv6"
I0123 02:58:03.381041       1 server_others.go:438] "Defaulting to no-op detect-local"
I0123 02:58:03.381063       1 proxier.go:251] "Setting route_localnet=1 to allow node-ports on localhost; to change this either disable iptables.localhostNodePorts (--iptables-localhost-nodeports) or set nodePortAddresses (--nodeport-addresses) to filter loopback addresses"
I0123 02:58:03.381229       1 server.go:846] "Version info" version="v1.28.0"
I0123 02:58:03.381238       1 server.go:848] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0123 02:58:03.381695       1 config.go:97] "Starting endpoint slice config controller"
I0123 02:58:03.381714       1 shared_informer.go:311] Waiting for caches to sync for endpoint slice config
I0123 02:58:03.381742       1 config.go:315] "Starting node config controller"
I0123 02:58:03.381752       1 config.go:188] "Starting service config controller"
I0123 02:58:03.381766       1 shared_informer.go:311] Waiting for caches to sync for service config
I0123 02:58:03.381758       1 shared_informer.go:311] Waiting for caches to sync for node config
I0123 02:58:03.482816       1 shared_informer.go:318] Caches are synced for endpoint slice config
I0123 02:58:03.483056       1 shared_informer.go:318] Caches are synced for service config
I0123 02:58:03.483576       1 shared_informer.go:318] Caches are synced for node config
```

**Comment by wangjianwen** [comment] 2024-01-30 08:39
I found the reason for the error "Tunnel Connection Failed" , that's because I set the proxy for containerd.

```
 cat /etc/systemd/system/containerd.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=forward.proxy.*.cn:3128"
Environment="HTTPS_PROXY=forward.proxy.*.cn:3128"
Environment="NO_PROXY=dev.docker.*.cn"
```

The problem be solved by removed http-proxy.conf and restarted the containerd

**Comment by mazdakn** [comment] 2024-01-30 17:26
@wangjianwen thanks for the update. Great to hear you could solve it.

**Comment by mazdakn** [comment] 2024-01-30 17:26
Closing since the issue is solved. Feel free to re-open if something changed.

**Closed by mazdakn** 2024-01-30 17:26 UTC
Labels: kind/support
