### ISSUE TITLE
image calico/apiserver do not support arm64

### ISSUE THREAD

**Issue by zhangkepi** [projectcalico/calico#5347] opened 2022-01-01 06:28 UTC
I do not found calico/apiserver image for arm at docker hub, so that I can not install calico in k8s

**Comment by piwi3910** [comment] 2022-01-05 15:14
agree, same issue here, i read calico now supported arm64, but when deploying, ErrImagePull as there is no arm64 image for the api-server

**Comment by neocode24** [comment] 2022-01-07 14:36
I've a same issue. Here is error message.

`Failed to pull image "docker.io/calico/apiserver:v3.21.2": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by caseydavenport** [comment] 2022-01-07 21:32
This looks like a duplicate of https://github.com/projectcalico/calico/issues/5148

Most other images are compatible with arm64, but apiserver seems to be missed. We'll need to update the build.

**Closed by caseydavenport** 2022-01-07 21:32 UTC
