### ISSUE TITLE
Calico-node randomly fails with "Error executing command: read unix @->/var/run/calico/bird.ctl: i/o timeout"

### ISSUE THREAD

**Issue by strangeman** [projectcalico/calico#2992] opened 2019-11-14 07:45 UTC
We use Kubernetes v1.15.3 on bare metal (installed via kubespray on CentOS 7 and Docker 19.03.3) and Calico v3.10. Unfortunately, we have a problem with calico and can't figure out what happening.

After node reboot, calico-nodes works correctly for some time (couple days or so) but then they suddenly fail with `Error executing command: read unix @->/var/run/calico/bird.ctl: i/o timeout`. The same thing with `calicoctl node status`, from 10 calls 7-8 will be failed with this error and others will be executed correctly.

I can't see anything criminal in logs, except this error and have no idea what happening and how I can troubleshoot it. The server I/O is near zero, network connectivity is ok.

**Comment by fasaxc** [comment] 2019-11-18 10:02
@strangeman did you recently upgrade to v3.10?  If so, did you experience any problems before upgrade?

Looks like we upgraded the version of BIRD in v3.10; it's possible that that's introduced a bug.

**Comment by strangeman** [comment] 2019-11-18 23:09
Yeah, we experienced the same problem in the previous version and it was the main reason why we tried to upgrade. :) 
After the upgrade (and full reboot the cluster) all was ok for about a week and then started failing again.

**Comment by fasaxc** [comment] 2019-11-19 10:37
@strangeman Can you describe your set-up in detail?  How many nodes?  How many pods? How are you using your cluster (do you churn a lot of pods, for example)?  How is BGP configured, are you using the default full-mesh configuration?

**Comment by strangeman** [comment] 2019-11-19 11:07
We have 3 masters (with allowed pod allocation) + 2 workers. 

```
kubectl get po --all-namespaces | wc -l
280
```

The configuration is almost default for kubespray, we just enabled Helm installation. Also, we use Istio as a service mesh, which also installed with default settings.

Cluster mostly used as the developer's playground, so the typical workload is deploying about 30 different pods in a separate namespace, using them for day or two (with small traffic) and then destroying them. Also, we use the cluster for API and integration testing, so one of the playgrounds launching and destroying almost every hour.

**Comment by fasaxc** [comment] 2019-11-19 11:10
Nothing unusual there, all pretty mainline.  What does `ip route` should on your nodes?

**Comment by strangeman** [comment] 2019-11-19 11:26
```
default via GATEWAY dev eno1 proto static 
10.233.105.0/24 via NODE2_IP dev tunl0 proto bird onlink 
10.233.115.0/24 via NODE5_IP dev tunl0 proto bird onlink 
blackhole 10.233.116.0/24 proto bird 
10.233.116.4 dev cali93b05770730 scope link 
10.233.116.6 dev cali9d646c18bf7 scope link 
10.233.116.11 dev calidb4bd3d3979 scope link 
10.233.116.13 dev calif76d6947d67 scope link 
10.233.116.14 dev calieb9b20a7581 scope link 
10.233.116.17 dev cali65af7d57bf9 scope link 
10.233.116.19 dev calid909c51d165 scope link 
10.233.116.20 dev cali6fa0fc0ee2c scope link 
10.233.116.24 dev cali012fd08a243 scope link 
10.233.116.34 dev cali3561ec6dc7b scope link 
10.233.116.35 dev calic32cf8c2470 scope link 
10.233.116.36 dev calia6c1fada5e2 scope link 
10.233.116.37 dev cali6b32e7b0390 scope link 
10.233.116.39 dev cali7aafb6804b3 scope link 
10.233.116.45 dev cali242a41cc1c0 scope link 
10.233.116.58 dev califb884d183dc scope link 
10.233.116.60 dev calie560c385b23 scope link 
10.233.116.73 dev cali56602c27e48 scope link 
10.233.116.81 dev cali62d43afb4b7 scope link 
10.233.116.82 dev cali406eb38e1c5 scope link 
10.233.116.92 dev cali9f23c1110c7 scope link 
10.233.116.101 dev cali69fa3e81c5a scope link 
10.233.116.102 dev cali3682dba5aa0 scope link 
10.233.116.108 dev calia7584ba3d37 scope link 
10.233.116.114 dev calif230c13c58c scope link 
10.233.116.118 dev cali9d3b9ad75af scope link 
10.233.116.119 dev cali2b229b1fbbd scope link 
10.233.116.120 dev calid6ce8e4204b scope link 
10.233.116.125 dev cali9bcdc259e9d scope link 
10.233.116.130 dev cali3c82222f0fd scope link 
10.233.116.142 dev cali17bdd047f37 scope link 
10.233.116.146 dev calibfa9a8ecf9c scope link 
10.233.116.155 dev calied2443b8b3d scope link 
10.233.116.165 dev cali657f013a890 scope link 
10.233.116.171 dev calica215955b10 scope link 
10.233.116.175 dev cali8f04a3b195f scope link 
10.233.116.179 dev cali71b9050cfa2 scope link 
10.233.116.189 dev calieec1660328f scope link 
10.233.116.202 dev caliab8ec9e7f4d scope link 
10.233.116.207 dev califc929a955e4 scope link 
10.233.116.212 dev cali204ba36f9a3 scope link 
10.233.116.241 dev cali838f1d734e9 scope link 
10.233.116.244 dev calic4523d24778 scope link 
10.233.116.252 dev cali0d04c68d036 scope link 
10.233.117.0/24 via NODE3_IP dev tunl0 proto bird onlink 
10.233.121.0/24 via NODE4_IP dev tunl0 proto bird onlink 
GATEWAY dev eno1 proto kernel scope link src NODE1_IP 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
```
route table from node1

```
ls -l1 /var/run/calico/bird.ctl
srw-rw----. 1 root root 0 Nov 14 10:23 /var/run/calico/bird.ctl
```
socket exists for some days, but I still get `i/o timeout` from calicoctl

**Comment by fasaxc** [comment] 2019-11-19 11:45
That all looks normal.  One route for each local pod and some bird routes for the remotes.

**Comment by fasaxc** [comment] 2019-11-19 11:46
Suggest you crank the BGP log level up to debug and wait for a repro.  Maybe that'll give a clue as to what has happened to BIRD: https://docs.projectcalico.org/v3.10/reference/resources/bgpconfig

**Comment by strangeman** [comment] 2019-11-21 04:15
Another interesting thing: I can easily connect to bird6 socket, but cannot connect to bird4 (via nc or birdcl)
```
$ nc -U /var/run/calico/bird.ctl
Ncat: Invalid argument.
$ nc -U /var/run/calico/bird6.ctl
0001 BIRD v0.3.3+birdv1.6.7 ready.
^C
```

**Comment by strangeman** [comment] 2019-11-21 04:52
Increased log level to debug - nothing interesting about `bird`, as I see:
```
bird: device1: Connected to table master
bird: device1: State changed to feed
bird: direct1: Starting
bird: direct1: Connected to table master
bird: direct1: State changed to feed
bird: Mesh_XXX_217: Starting
bird: Mesh_XXX_217: State changed to start
bird: Mesh_XXX_33: Starting
bird: Mesh_XXX_33: State changed to start
bird: Mesh_XXX_76: Starting
bird: Mesh_XXX_76: State changed to start
bird: Mesh_XXX_242: Starting
bird: Mesh_XXX_242: State changed to start
bird: Graceful restart started
bird: Started
bird: device1: State changed to up
bird: direct1 < interface lo goes up
bird: direct1 < primary address 127.0.0.0/8 on interface lo added
bird: direct1 < interface eno1 goes up
bird: direct1 < primary address .193/32 on interface eno1 added
bird: direct1 > added [best] .193/32 dev eno1
bird: direct1 < interface docker0 goes up
bird: direct1 < primary address 172.17.0.0/16 on interface docker0 added
bird: direct1 > added [best] 172.17.0.0/16 dev docker0
bird: direct1 < interface dummy0 created
bird: direct1 < interface kube-ipvs0 created
bird: direct1 < interface cali4ab1f388749 created
bird: direct1 < interface nodelocaldns created
bird: direct1 < interface tunl0 goes up
bird: direct1 < primary address 10.233.105.0/32 on interface tunl0 added
bird: direct1 > added [best] 10.233.105.0/32 dev tunl0
bird: direct1 < interface cali76415473f9f created
<...>
bird: direct1 < interface cali8302cb40c74 created
bird: direct1: State changed to up
bird: Mesh_XXX_242: Started
bird: Mesh_XXX_76: Started
bird: Mesh_XXX_33: Started
bird: Mesh_XXX_217: Started
bird: Mesh_XXX_217: Connect delayed by 2 seconds
bird: device1: Scanning interfaces
bird: device1: Scanning interfaces
bird: device1: Scanning interfaces
bird: Mesh_XXX_217: Connecting to .217 from local address .242
bird: Mesh_XXX_217: Connecting to .217 from local address .242
bird: device1: Scanning interfaces
bird: device1: Scanning interfaces
```
and then just many log entries about `Scanning interfaces` and `Mesh_XXX_217: Connecting to`

**Comment by halfcrazy** [comment] 2019-12-25 06:57
We meet same problem here with calico 3.9.0
```bash
[root@master01 ~]# kubectl get po --all-namespaces |wc -l
9937
[root@master01 ~]# ll /var/run/calico/bird.ctl
srw-rw---- 1 root root 0 Dec 25 14:47 /var/run/calico/bird.ctl
[root@master01 ~]# nc -U /var/run/calico/bird.ctl
hang
[root@master01 ~]# nc -U /var/run/calico/bird6.ctl
0001 BIRD v0.3.3+birdv1.6.3 ready.

[root@master01 ~]# ./calicoctl node status
Calico process is running.

IPv4 BGP status
Error executing command: read unix @->/var/run/calico/bird.ctl: i/o timeout
```
Describe calico-node pod event shows
```
  Warning  Unhealthy  3m28s (x3 over 3m48s)  kubelet, node10    Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
  Warning  Unhealthy  106s (x10 over 3m16s)  kubelet, node10    Readiness probe failed: calico/node is not ready: BIRD is not ready: Error executing command: read unix @->/var/run/calico/bird.ctl: i/o timeout
```

Bird logs no errors
```
# tail -f current
2019-12-25_06:51:53.49748 bird: I/O loop cycle took 27143 ms for 29 events
2019-12-25_06:52:08.16220 bird: I/O loop cycle took 13661 ms for 12 events
2019-12-25_06:52:55.13662 bird: I/O loop cycle took 45973 ms for 46 events
2019-12-25_06:53:04.14442 bird: I/O loop cycle took 8006 ms for 7 events
2019-12-25_06:53:16.03153 bird: I/O loop cycle took 10885 ms for 10 events
2019-12-25_06:54:17.17453 bird: I/O loop cycle took 60141 ms for 62 events
2019-12-25_06:55:03.21284 bird: I/O loop cycle took 45745 ms for 44 events
2019-12-25_06:55:09.03732 bird: I/O loop cycle took 5542 ms for 11 events
2019-12-25_06:55:31.20280 bird: I/O loop cycle took 21164 ms for 25 events
2019-12-25_06:56:14.22668 bird: I/O loop cycle took 42021 ms for 40 events
2019-12-25_06:56:41.97087 bird: I/O loop cycle took 26741 ms for 27 events
2019-12-25_06:56:49.99376 bird: I/O loop cycle took 7019 ms for 7 events
^C
# netstat -anlp|grep 179
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      125/bird
tcp        0      0 192.168.16.220:51722    192.168.16.218:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:51348    192.168.16.180:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:43089    192.168.16.216:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:39526    192.168.16.208:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:56982    192.168.16.181:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:48423    192.168.16.219:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:50045    192.168.16.212:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:58861    192.168.16.209:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:58790    192.168.16.217:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:40605    192.168.16.215:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:50695    192.168.16.213:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:48805    192.168.16.207:179      ESTABLISHED 125/bird
tcp        0      0 192.168.16.220:45965    192.168.16.214:179      ESTABLISHED 125/bird
tcp       19      0 192.168.16.220:52176    192.168.16.211:179      ESTABLISHED 125/bird
```

**Comment by caseydavenport** [comment] 2020-01-02 23:36
Just to check, is there actually a problem with networking on these clusters when in this state? It sounds like routes are being programmed correctly, just that the Calico readiness checks start failing with this error message?

**Comment by strangeman** [comment] 2020-01-03 01:24
No, network interactions seem running correctly.

**Comment by halfcrazy** [comment] 2020-01-11 05:21
We meet this issue again, this time some nodes lost route, and some calico-node in crashbackoff status.
descibre and shows felix status check failed.
```log
2020-01-10 15:18:29.699 [DEBUG][48] route_table.go 435: Syncing interface routes ifaceName="calif1997c03da4" ipVersion=0x4
2020-01-10 15:18:29.700 [DEBUG][48] route_table.go 452: Have updated targets. ifaceName="calif1997c03da4" ipVersion=0x4
2020-01-10 15:18:29.990 [DEBUG][48] health.go 159: GET /liveness
2020-01-10 15:18:29.990 [DEBUG][48] health.go 182: Checking state of reporter reporter=&health.reporterState{name:"felix-startup", reports:health.HealthReport{Live:true, Ready:true}, timeout:0, latest:health.HealthReport{Live:true, Ready:true}, timestamp:time.Time{wall:0xbf7e433a478ea2f3, ext:128190219, loc:(*time.Location)(0x2bbb9e0)}}
2020-01-10 15:18:29.990 [DEBUG][48] health.go 182: Checking state of reporter reporter=&health.reporterState{name:"int_dataplane", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf7e433f4b9e25b3, ext:20196315575, loc:(*time.Location)(0x2bbb9e0)}}
2020-01-10 15:18:29.990 [WARNING][48] health.go 66: Report timed out name="int_dataplane"
2020-01-10 15:18:29.990 [WARNING][48] health.go 184: Reporter is not live. name="int_dataplane"
2020-01-10 15:18:29.991 [WARNING][48] health.go 55: Report timed out name="int_dataplane"
2020-01-10 15:18:29.991 [WARNING][48] health.go 188: Reporter is not ready. name="int_dataplane"
2020-01-10 15:18:29.991 [DEBUG][48] health.go 182: Checking state of reporter reporter=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:true}, timestamp:time.Time{wall:0xbf7e4341d2585618, ext:30309180952, loc:(*time.Location)(0x2bbb9e0)}}
2020-01-10 15:18:29.991 [WARNING][48] health.go 66: Report timed out name="async_calc_graph"
2020-01-10 15:18:29.991 [WARNING][48] health.go 184: Reporter is not live. name="async_calc_graph"
2020-01-10 15:18:29.991 [WARNING][48] health.go 55: Report timed out name="async_calc_graph"
2020-01-10 15:18:29.991 [WARNING][48] health.go 188: Reporter is not ready. name="async_calc_graph"
2020-01-10 15:18:29.991 [DEBUG][48] health.go 199: Calculated health summary healthResult=&health.HealthReport{Live:false, Ready:false}
2020-01-10 15:18:29.991 [WARNING][48] health.go 165: Health: not live
2020-01-10 15:18:29.998 [DEBUG][48] iface_monitor.go 210: notifyIfaceAddrs ifIndex=329
2020-01-10 15:18:29.999 [DEBUG][48] iface_monitor.go 212: Known interface ifIndex=329
2020-01-10 15:18:29.999 [INFO][48] int_dataplane.go 638: Linux interface addrs changed. addrs=set.mapSet{"fe80::ecee:eeff:feee:eeee":set.empty{}} ifaceName="cali68eb3bab775"
2020-01-10 15:18:29.999 [DEBUG][48] iface_monitor.go 230: storeAndNotifyLink called ifaceExists=true link=&netlink.Veth{LinkAttrs:netlink.LinkAttrs{Index:330, MTU:1440, TxQLen:0, Name:"calidefac00e23e", HardwareAddr:net.HardwareAddr{0xee, 0xee, 0xee, 0xee, 0xee, 0xee}, Flags:0x13, RawFlags:0x11043, ParentIndex:4, MasterIndex:0, Namespace:interface {}(nil), Alias:"", Statistics:(*netlink.LinkStatistics)(0xc00075c5f4), Promisc:0, Xdp:(*netlink.LinkXdp)(nil), EncapType:"ether", Protinfo:(*netlink.Protinfo)(nil), OperState:0x6, NetNsID:91, NumTxQueues:0, NumRxQueues:0}, PeerName:""}
2020-01-10 15:18:29.999 [DEBUG][48] iface_monitor.go 249: storeAndNotifyLinkInner called ifaceExists=true ifaceName="calidefac00e23e" link=&netlink.Veth{LinkAttrs:netlink.LinkAttrs{Index:330, MTU:1440, TxQLen:0, Name:"calidefac00e23e", HardwareAddr:net.HardwareAddr{0xee, 0xee, 0xee, 0xee, 0xee, 0xee}, Flags:0x13, RawFlags:0x11043, ParentIndex:4, MasterIndex:0, Namespace:interface {}(nil), Alias:"", Statistics:(*netlink.LinkStatistics)(0xc00075c5f4), Promisc:0, Xdp:(*netlink.LinkXdp)(nil), EncapType:"ether", Protinfo:(*netlink.Protinfo)(nil), OperState:0x6, NetNsID:91, NumTxQueues:0, NumRxQueues:0}, PeerName:""}
2020-01-10 15:18:29.999 [DEBUG][48] iface_monitor.go 274: Interface now up ifaceName="calidefac00e23e"
```

**Comment by jinnzy** [comment] 2020-02-14 03:17
I also encountered this problem, but I found that it is caused by the high CPU usage of bird.

https://github.com/projectcalico/bird/issues/77

**Comment by spikecurtis** [comment] 2020-03-18 17:44
@strangeman can you confirm whether your issue is also accompanied by a high CPU usage of BIRD?

One other question is, are you using the IPVS backend on Kube-proxy?  We found some issues there that are fixed in the latest release.

**Comment by strangeman** [comment] 2020-03-18 22:46
@spikecurtis unfortunately, we're had switched from Calico, so I cannot check it. :(

**Comment by spikecurtis** [comment] 2020-03-18 23:18
I'm going to close this out under the assumption that it's a dupe of the BIRD CPU issue.  Other watchers please chime in if you're seeing something different.

**Closed by spikecurtis** 2020-03-18 23:18 UTC
Labels: impact/low, kind/bug, likelihood/high
