### ISSUE TITLE
“No Route to Host“ watched after one node reboot in cluster

### ISSUE THREAD

**Issue by HelenaZheng** [projectcalico/calico#3108] opened 2020-01-07 06:39 UTC
What happened:
One node in the k8s cluster was reboot， then we saw something wrong in our application.
We find some ingormation in ingress as follow:

2020/01/06 21:53:13 [error] 62741#62741: *590097349 connect() failed (113: No route to host) while connecting to upstream, client: 30.68.0.49, server: security-rule.lufax.app, request: "POST /security-rule-app/service/rt-rule/batch-risk-inspection HTTP/1.1", upstream: "http://30.69.91.110:8000/security-rule-app/service/rt-rule/batch-risk-inspection", host: "security-rule.lufax.app"

When we curl manual by this command, is ok.

What you expected to happen:
What happend after node reboot? What we can do to fix this problem

How to reproduce it (as minimally and precisely as possible):
Just we reboot node in cluster, this can be see again

Environment:

Kubernetes version (use kubectl version):
"v1.11.2"

Cloud provider or hardware configuration:
bare machine

OS (e.g: cat /etc/os-release):
redhat 7.6

Kernel (e.g. uname -a):
3.10.0-957.el7.x86_64

Network plugin and version (if this is a network-related bug):
calico
Client Version: v3.1.3
ospf
zebra

kube-proxy use iptables mode

**Comment by rafaelvanoni** [comment] 2020-01-13 21:20
@HelenaZheng Could you clarify if the connectivity issue persisted after the reboot or if it was a one off error (caused by the reboot) ?

**Comment by HelenaZheng** [comment] 2020-01-19 06:39
> @HelenaZheng Could you clarify if the connectivity issue persisted after the reboot or if it was a one off error (caused by the reboot) ?

I find more error in calico “ bird: Kernel dropped some netlink messages, will resync on next scan.”

**Comment by rafaelvanoni** [comment] 2020-02-07 00:04
@HelenaZheng Just trying to clarify the first issue you reported, was the `connection failed` error a one time problem caused by the reboot or did it continue to happen once the node came back up?

**Comment by caseydavenport** [comment] 2020-02-20 23:13
It's not obvious to me what is the error being described here - could you provide some more information about what the symptoms are?

**Comment by HelenaZheng** [comment] 2020-02-24 01:24
@rafaelvanoni  the connection failed error caused after node came back up. I have already close the service docker,calico,ospf,zebra,kubelet in /etc/rc.local. If I do not start the services in /etc/rc/local after the node starting up, the error can not come. But one node down, need added in cluster finally.

**Comment by HelenaZheng** [comment] 2020-02-24 01:39
@caseydavenport the front appliaction error 502 not found the hosts

**Comment by lmm** [comment] 2020-12-22 17:31
Going to close this for now, please file another issue if you're still having issues, thanks!

**Closed by lmm** 2020-12-22 17:31 UTC
Labels: kind/support
