### ISSUE TITLE
change registry for calico images

### ISSUE THREAD

**Issue by volker-raschek** [projectcalico/calico#5103] opened 2021-11-19 11:19 UTC
## Expected Behavior

Expect a setting in values.yaml or something else to customize the registry host for calico images. 

## Current Behavior

The tigera-operator creates the namespace `calico-system` with all calico pods. The container images are pulled from docker.io.

![Bildschirmfoto vom 2021-11-19 12-09-24](https://user-images.githubusercontent.com/18311012/142614358-70a55a4b-8b11-4cee-9090-f889e4f924f5.png)

## Possible Solution

Add a property in the values.yaml file of the tigera-operator helm chart to change the default registry for the calico container images.

## Context

In my cases the docker.io registry is not reachable - DMZ, firewall settings ect. It must be used a proxy registry which is reachable under a custom hostname provided by the adminstrator / user. Otherwise it is not possible to pull the container images. 

## Your Environment

* Calico version: 3.20.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: CentOS 7

**Comment by tmjd** [comment] 2021-11-19 14:04
Duplicate of #5057, see [this response](https://github.com/projectcalico/calico/issues/5057#issuecomment-961219108) for the solution.

**Closed by tmjd** 2021-11-19 14:04 UTC
