### ISSUE TITLE
Calico may not work properly after system reboots

### ISSUE THREAD

**Issue by patrickdung** [projectcalico/calico#5135] opened 2021-12-02 13:26 UTC
Calico was setup on RHEL7 and running properly. But all of the control plane and nodes requires reboot.
After the host rebooted, the pods are up and running.
But the pods are not connecting properly according to the (global) network policies normally.
Some rules are not effective.

The setting is default deny and allow some pods to communicate with two different namespaces.
Before reboot, pods are able to access internet.
After reboot, some policies (iptables rules) are not effective and they cannot access internet.
Sometimes, pods are not able to connect to another pod.

I have encounter this several times.

BTW, I am not sure this problem (caused by Calico CNI) may cause problem with coredns.
Sometimes after the node reboots, the coredns pod are up and running but the DNS inside it could not access internet (pod to internet problem, probably caused by CNI), so it would affect DNS resolution inside the pods.

## Expected Behavior

If the kubernetes cluster or nodes are rebooted (crashed or due to maintenance), the network policies should still work afterwards.

## Current Behavior

Some rules may not be effective and it's hard to find out where is the problem.

## Possible Solution

Better handling of individual host reboot or the whole kubernetes cluster reboot.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
Calico 3.20
Kubernetes 1.21
RHEL 7.9

**Comment by caseydavenport** [comment] 2021-12-13 23:32
@patrickdung this sounds very likely to be this existing issue: https://github.com/projectcalico/calico/issues/4955

Give it a look and see if it sounds similar, and see if any of the workarounds help mitigate your case.

**Comment by patrickdung** [comment] 2021-12-14 05:50
@caseydavenport Thanks, it sounds similar, but it's affecting TCP for my case. BTW, I had remembered problem occur in my environment several months ago (with older Calico version).

**Comment by caseydavenport** [comment] 2022-01-11 17:05
Going to leave this one open for now but I think it might be a duplicate of #4955 - I don't think UDP vs TCP matters much here. There is a fix in the works for that so we'll see if it also fixes your symptoms.

**Comment by Jc2k** [comment] 2022-01-12 11:49
I believe I am also hitting this on node reboots. Note that in the other issue talks about draining. Just to confirm that I do drain, so I don't believe not draining is the cause of the issue I have.

It seemed to start either on upgrading to calico 3.21 (from 3.19, and i did go via 3.20 if that matters) or when i started rolling out more egress rules. Unfortunately I had to upgrade to 3.21 as i needed the new `services` selector, so i can't seperate these 2 events appart.

A rolling restart of calico-node seems to fix it.

**Comment by caseydavenport** [comment] 2022-01-18 23:49
> Just to confirm that I do drain, so I don't believe not draining is the cause of the issue I have.

Could it be that pods are still starting on the node after reboot before calico/node is launched? That's the crux of the other issue - pods are launched before calico/node is up to program rules, and so conntrack kicks in before calico can write its iptables rules.

**Comment by Jc2k** [comment] 2022-02-14 09:02
Ah - i'm using kured to orchestrate the reboots. So yes, its quite possibly uncordoning too soon.

For anyone following this ticket, https://github.com/projectcalico/calico/pull/5399 was merged to fix #4955. So if this is a dupe, then we have a fix.

**Comment by caseydavenport** [comment] 2022-02-16 21:11
Going to close this one since I believe a fix will be in v3.23 (as linked above)

**Closed by caseydavenport** 2022-02-16 21:11 UTC
Labels: kind/bug, likelihood/high, impact/high

**Comment by Jc2k** [comment] 2022-02-16 21:17
@caseydavenport do you think that PR will get backported into stable? 3.22 only just came out so I imagine we are looking at a quarter until 3.23? It sucks pretty hard if you run into this via https://github.com/weaveworks/kured.

**Comment by caseydavenport** [comment] 2022-02-16 23:06
I'll look into it - it's a non-trivial bugfix so nominally not appropriate for a patch release (it has changes to the user-facing configuration surface in the CNI config)

**Comment by Jc2k** [comment] 2022-02-16 23:07
Thank you!
