### ISSUE TITLE
liveness and readiness probes failing on some nodes

### ISSUE THREAD

**Issue by der-ali** [projectcalico/calico#5627] opened 2022-02-17 10:19 UTC
Some calico pods are in crashloopbackoff state due to liveness and readiness probes failing.
The logs are not showing a clear error message:
```logs
2022-02-17 09:45:35.728 [DEBUG][46] felix/health.go 148: GET /readiness
2022-02-17 09:45:35.729 [DEBUG][46] felix/health.go 182: Checking state of reporter reporter=&health.reporterState{name:"felix-startup", reports:health.HealthReport{Live:true, Ready:true}, timeout:0, lates
t:health.HealthReport{Live:true, Ready:true}, timestamp:time.Time{wall:0xc07ba42ec3aa4eec, ext:1327941909, loc:(*time.Location)(0x37fb6c0)}}
2022-02-17 09:45:35.729 [DEBUG][46] felix/health.go 182: Checking state of reporter reporter=&health.reporterState{name:"int_dataplane", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000
000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xc07ba42f2b7e8697, ext:2996161222, loc:(*time.Location)(0x37fb6c0)}}
2022-02-17 09:45:35.729 [WARNING][46] felix/health.go 188: Reporter is not ready. name="int_dataplane"
2022-02-17 09:45:35.729 [DEBUG][46] felix/health.go 182: Checking state of reporter reporter=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000
000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xc07ba42f48b048ac, ext:3412219617, loc:(*time.Location)(0x37fb6c0)}}
2022-02-17 09:45:35.729 [WARNING][46] felix/health.go 188: Reporter is not ready. name="async_calc_graph"
2022-02-17 09:45:35.729 [INFO][46] felix/health.go 196: Overall health status changed newStatus=&health.HealthReport{Live:true, Ready:false}
2022-02-17 09:45:35.729 [DEBUG][46] felix/health.go 199: Calculated health summary healthResult=&health.HealthReport{Live:true, Ready:false}
2022-02-17 09:45:35.729 [WARNING][46] felix/health.go 154: Health: not ready

2022-02-17 09:45:32.269 [DEBUG][46] felix/sockmap_state.go 37: Created new Sockmap state.
2022-02-17 09:45:32.269 [DEBUG][46] felix/sockmap_state.go 191: Wiping old sockmap state.
2022-02-17 09:45:32.269 [DEBUG][46] felix/bpf.go 154: running: bpftool prog detach pinned /sys/fs/bpf/calico/sockmap/calico_sk_msg_v1 msg_verdict pinned /sys/fs/bpf/calico/sockmap/calico_sock_map_v1
2022-02-17 09:45:32.277 [DEBUG][46] felix/sockmap_state.go 194: Failed to detach sk_msg program from sockmap. error=failed to detach sk_msg prog from sockmap: exit status 255
Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sk_msg_v1): No such file or directory

2022-02-17 09:45:32.277 [DEBUG][46] felix/bpf.go 154: running: bpftool cgroup detach /run/calico/cgroup sock_ops pinned /sys/fs/bpf/calico/sockmap/calico_sockops_v1
2022-02-17 09:45:32.289 [DEBUG][46] felix/sockmap_state.go 198: Failed to detach sockops program from cgroup. error=failed to detach sockops prog from cgroup: exit status 255
Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sockops_v1): No such file or directory

2022-02-17 09:45:32.289 [DEBUG][46] felix/sockmap_state.go 202: Failed to remove sockops program. error=remove /sys/fs/bpf/calico/sockmap/calico_sockops_v1: no such file or directory
2022-02-17 09:45:32.289 [DEBUG][46] felix/sockmap_state.go 206: Failed to remove sk_msg program. error=remove /sys/fs/bpf/calico/sockmap/calico_sk_msg_v1: no such file or directory
2022-02-17 09:45:32.289 [DEBUG][46] felix/sockmap_state.go 210: Failed to remove sockmap endpoints map. error=remove /sys/fs/bpf/calico/sockmap/calico_sk_endpoints_v1: no such file or directory
2022-02-17 09:45:32.289 [DEBUG][46] felix/bpf.go 154: running: bpftool map --json getnext pinned /sys/fs/bpf/calico/sockmap/calico_sock_map_v1
2022-02-17 09:45:32.305 [DEBUG][46] felix/sockmap_state.go 214: Failed to remove sockmap program. error=failed to clear sock map: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sock_map_v1): No such file or directory
2022-02-17 09:45:32.306 [INFO][46] felix/connecttime.go 46: Running bpftool to look up programs attached to cgroup args=[]string{"bpftool", "-j", "-p", "cgroup", "show", "/run/calico/cgroup"}
2022-02-17 09:45:32.381 [DEBUG][46] felix/cleanup.go 33: Trying to clean up any left-over BPF state from a previous run.
2022-02-17 09:45:32.393 [DEBUG][46] felix/cleanup.go 53: Found calico map name="calico_failsafe"
2022-02-17 09:45:32.445 [INFO][46] felix/route_table.go 241: Calculated interface name regexp regex="^cali.*"
2022-02-17 09:45:32.445 [DEBUG][46] felix/int_dataplane.go 919: registering ManagerWithRouteTables manager=""
2022-02-17 09:45:32.445 [INFO][46] felix/ipsets.go 119: Queueing IP set for creation family="inet" setID="all-ipam-pools" setType="hash:net"
2022-02-17 09:45:32.445 [INFO][46] felix/ipsets.go 119: Queueing IP set for creation family="inet" setID="masq-ipam-pools" setType="hash:net"
2022-02-17 09:45:32.445 [INFO][46] felix/route_table.go 241: Calculated interface name regexp regex="^wireguard.cali$"
2022-02-17 09:45:32.445 [DEBUG][46] felix/int_dataplane.go 919: registering ManagerWithRouteTables manager=""
2022-02-17 09:45:32.445 [INFO][46] felix/int_dataplane.go 772: Registering to report health.
2022-02-17 09:45:32.457 [INFO][46] felix/int_dataplane.go 1500: attempted to modprobe nf_conntrack_proto_sctp error=exit status 1 output=""
```

## Your Environment

* Calico version v3.17.3
* Kubernetes v1.20.2
* Operating System and version: Ubuntu 20.04.1

**Comment by caseydavenport** [comment] 2022-02-18 16:51
> Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sk_msg_v1): No such file or directory

Looks like a BPF failure. FWIW, Calico v3.17 is quite old and we've made a huge number of fixes to the BPF dataplane in particular since then. I'd highly recommend attempting to reproduce on a newer Calico version before digging in further.

**Comment by fasaxc** [comment] 2022-03-03 17:37
I think those logs are a red herrring, it's just failing to clean up the old BPF programs (because they don't exist).  @der-ali are you running in eBPF mode?

What're the liveness/readiness errors shown by `kubectl describe pod <calico-node pod>` ?

**Comment by cpsrujana** [comment] 2022-03-05 15:27
Am also seeing the similar issue. Calico pod is not ready.

**Environment**
 * K8s version - 1.21.5
* calico version - v3.19.2
* Operating System - Debian 10 
*  Kernel : 4.19.81-OpenNetworkLinux

 **calico pod description**
  Warning  Unhealthy  26m (x2 over 26m)     kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
  Normal   Killing    25m                   kubelet            Container calico-node failed liveness probe, will be restarted
  Normal   Created    25m (x2 over 26m)     kubelet            Created container calico-node
  Normal   Pulled     25m (x2 over 26m)     kubelet            Container image "quay.io/calico/node:v3.19.2" already present on machine
  Warning  Unhealthy  16m (x44 over 26m)    kubelet            Liveness probe failed:
  Warning  BackOff    6m21s (x38 over 19m)  kubelet            Back-off restarting failed container
  Warning  Unhealthy  82s (x80 over 26m)    kubelet            Readiness probe failed:

**Calico pod log**

2022-03-05 15:20:37.156 [DEBUG][73] felix/int_dataplane.go 936: Checking if we need to clean up the VXLAN device
2022-03-05 15:20:37.156 [DEBUG][73] felix/int_dataplane.go 940: VXLAN disabled and no VXLAN device found
2022-03-05 15:20:37.157 [DEBUG][73] felix/lib.go 105: Raw kernel version rawVersion="Linux version 4.19.81-OpenNetworkLinux (root@mustaq-VirtualBox) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Thu Mar 3 05:12:02 UTC 2022\n"
2022-03-05 15:20:37.157 [DEBUG][73] felix/lib.go 113: Parsed kernel version version=4.19.81
2022-03-05 15:20:37.158 [DEBUG][73] felix/xdp_state.go 111: Created new xdpState.
2022-03-05 15:20:37.158 [INFO][73] felix/int_dataplane.go 466: XDP acceleration enabled.
2022-03-05 15:20:37.243 [DEBUG][73] felix/sockmap_state.go 37: Created new Sockmap state.
2022-03-05 15:20:37.243 [DEBUG][73] felix/sockmap_state.go 191: Wiping old sockmap state.
2022-03-05 15:20:37.243 [DEBUG][73] felix/bpf.go 154: running: bpftool prog detach pinned /sys/fs/bpf/calico/sockmap/calico_sk_msg_v1 msg_verdict pinned /sys/fs/bpf/calico/sockmap/calico_sock_map_v1
2022-03-05 15:20:37.245 [DEBUG][73] felix/sockmap_state.go 194: Failed to detach sk_msg program from sockmap. error=failed to detach sk_msg prog from sockmap: exit status 255
Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sk_msg_v1): No such file or directory

2022-03-05 15:20:37.245 [DEBUG][73] felix/bpf.go 154: running: bpftool cgroup detach /run/calico/cgroup sock_ops pinned /sys/fs/bpf/calico/sockmap/calico_sockops_v1
2022-03-05 15:20:37.247 [DEBUG][73] felix/sockmap_state.go 198: Failed to detach sockops program from cgroup. error=failed to detach sockops prog from cgroup: exit status 255
Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sockops_v1): No such file or directory

2022-03-05 15:20:37.247 [DEBUG][73] felix/sockmap_state.go 202: Failed to remove sockops program. error=remove /sys/fs/bpf/calico/sockmap/calico_sockops_v1: no such file or directory
2022-03-05 15:20:37.247 [DEBUG][73] felix/sockmap_state.go 206: Failed to remove sk_msg program. error=remove /sys/fs/bpf/calico/sockmap/calico_sk_msg_v1: no such file or directory
2022-03-05 15:20:37.248 [DEBUG][73] felix/sockmap_state.go 210: Failed to remove sockmap endpoints map. error=remove /sys/fs/bpf/calico/sockmap/calico_sk_endpoints_v1: no such file or directory
2022-03-05 15:20:37.248 [DEBUG][73] felix/bpf.go 154: running: bpftool map --json getnext pinned /sys/fs/bpf/calico/sockmap/calico_sock_map_v1
2022-03-05 15:20:37.249 [DEBUG][73] felix/sockmap_state.go 214: Failed to remove sockmap program. error=failed to clear sock map: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sock_map_v1): No such file or directory
2022-03-05 15:20:37.250 [INFO][73] felix/connecttime.go 51: Running bpftool to look up programs attached to cgroup args=[]string{"bpftool", "-j", "-p", "cgroup", "show", "/run/calico/cgroup"}
2022-03-05 15:20:37.252 [DEBUG][73] felix/cleanup.go 33: Trying to clean up any left-over BPF state from a previous run.
2022-03-05 15:20:37.258 [INFO][73] felix/route_table.go 249: Calculated interface name regexp regex="^cali.*"
2022-03-05 15:20:37.258 [DEBUG][73] felix/int_dataplane.go 981: registering ManagerWithRouteTables manager=""
2022-03-05 15:20:37.258 [INFO][73] felix/ipsets.go 126: Queueing IP set for creation family="inet" setID="all-ipam-pools" setType="hash:net"
2022-03-05 15:20:37.259 [INFO][73] felix/ipsets.go 126: Queueing IP set for creation family="inet" setID="masq-ipam-pools" setType="hash:net"
2022-03-05 15:20:37.259 [INFO][73] felix/route_table.go 249: Calculated interface name regexp regex="^wireguard.cali$"
2022-03-05 15:20:37.259 [DEBUG][73] felix/int_dataplane.go 981: registering ManagerWithRouteTables manager=""
2022-03-05 15:20:37.259 [INFO][73] felix/int_dataplane.go 834: Registering to report health.
2022-03-05 15:20:37.262 [INFO][73] felix/int_dataplane.go 1623: attempted to modprobe nf_conntrack_proto_sctp error=exit status 1 output=""
2022-03-05 15:20:37.262 [INFO][73] felix/int_dataplane.go 1625: Making sure IPv4 forwarding is enabled.
2022-03-05 15:20:37.263 [INFO][73] felix/table.go 506: Queueing update of chain. chainName="cali-failsafe-in" ipVersion=0x4 table="raw"
2022-03-05 15:20:37.263 [DEBUG][73] felix/table.go 939: Would invalidate dataplane cache but it was already invalid. ipVersion=0x4 reason="chain update" table="raw"
2022-03-05 15:20:37.263 [INFO][73] felix/table.go 506: Queueing update of chain. chainName="cali-failsafe-out" ipVersion=0x4 table="raw"
2022-03-05 15:20:37.263 [DEBUG][73] felix/table.go 939: Would invalidate dataplane cache but it was already invalid. ipVersion=0x4 reason="chain update" table="raw"
2022-03-05 15:20:37.263 [INFO][73] felix/table.go 506: Queueing update of chain. chainName="cali-PREROUTING" ipVersion=0x4 table="raw"
2022-03-05 15:20:37.263 [DEBUG][73] felix/table.go 577: Incref chain chainName="cali-from-host-endpoint"
2022-03-05 15:20:37.263 [INFO][73] felix/table.go 580: Chain became referenced, marking it for programming chainName="cali-from-host-endpoint"
2022-03-05 15:20:37.263 [DEBUG][73] felix/table.go 939: Would invalidate dataplane cache but it was already invalid. ipVersion=0x4 reason="chain update" table="raw"
2022-03-05 15:20:37.341 [INFO][73] felix/table.go 506: Queueing update of chain. chainName="cali-OUTPUT" ipVersion=0x4 table="raw"
2022-03-05 15:20:37.341 [DEBUG][73] felix/table.go 577: Incref chain chainName="cali-to-host-endpoint"
2022-03-05 15:20:37.342 [INFO][73] felix/table.go 580: Chain became referenced, marking it for programming chainName="cali-to-host-endpoint"
2022-03-05 15:20:37.342 [DEBUG][73] felix/table.go 939: Would invalidate dataplane cache but it was already invalid. ipVersion=0x4 reason="chain update" table="raw"
2022-03-05 15:20:37.342 [DEBUG][73] felix/table.go 459: Updating rule insertions chainName="PREROUTING" ipVersion=0x4 table="raw"
2022-03-05 15:20:37.342 [DEBUG][73] felix/table.go 577: Incref chain chainName="cali-PREROUTING"
2022-03-05 15:20:37.342 [INFO][73] felix/table.go 580: Chain became referenced, marking it for programming chainName="cali-PREROUTING"
2022-03-05 15:20:37.342 [DEBUG][73] felix/table.go 939: Would invalidate dataplane cache but it was already invalid. ipVersion=0x4 reason="insertion" table="raw"
2022-03-05 15:20:37.342 [DEBUG][73] felix/table.go 459: Updating rule insertions chainName="OUTPUT" ipVersion=0x4 table="raw"
2022-03-05 15:20:37.342 [DEBUG][73] felix/table.go 577: Incref chain chainName="cali-OUTPUT"
2022-03-05 15:20:37.343 [INFO][73] felix/table.go 580: Chain became referenced, marking it for programming chainName="cali-OUTPUT"
2022-03-05 15:20:37.343 [DEBUG][73] felix/table.go 939: Would invalidate dataplane cache but it was already invalid. ipVersion=0x4 reason="insertion" table="raw"
2022-03-05 15:20:37.343 [DEBUG][73] felix/static.go 556: Adding workload match rules ifacePrefix="cali"
2022-03-05 15:20:37.343 [DEBUG][73] felix/static.go 272: Adding workload match rules ifacePrefix="cali"
2022-03-05 15:20:37.343 [DEBUG][73] felix/static.go 653: Adding workload match rules ifacePrefix="cali"
2022-03-05 15:20:37.343 [DEBUG][73] felix/static.go 155: Adding workload match rules ifacePrefix="cali"

**Comment by lmm** [comment] 2022-03-08 18:04
@cpsrujana do your nodes with typha pods on them allow typha inbound traffic? Is traffic allowed on the BGP port?

**Comment by mgleung** [comment] 2022-03-22 16:42
I am going to close this due to inactivity but if the problem still persists, give us a shout and we'll reopen the issue.

**Comment by xiaomixin** [comment] 2023-09-08 09:45
@mgleung Could you please reopen this issue. 

I met the same issue when install calico with kubernetes. 

The exception happen during join one worker node to kubernetes cluster, could anyone help to take a look?

![image](https://github.com/projectcalico/calico/assets/130526722/fc394fce-c04e-4049-8540-9f0220929560)

**Comment by mgleung** [comment] 2023-09-19 16:51
@xiaomixin could I get you to share the details of your cluster and probably some of the logs requested above as well?

**Comment by coutinhop** [comment] 2023-11-28 18:17
@xiaomixin this issue is close to 2 years old, so most probably not the same problem you're facing. I will close this, could you please open a new issue and fill in all the requested info from the template (the more detailed the better). Thanks!

**Closed by coutinhop** 2023-11-28 18:17 UTC
