### ISSUE TITLE
couldn't get resource list for projectcalico.org/v3

### ISSUE THREAD

**Issue by cruggieri** [projectcalico/calico#8041] opened 2023-09-21 19:11 UTC
I've installed a new k8s cluster (1.26.9) with kubeadm, 3 controplane with etcd and 6 worker nodes. I followed the operator guide from here: https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises

I get this error with kubectl installed on mgmt host (not part of k8s cluster):

```$ kubectl get nodes
E0921 18:55:58.114102    7322 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 18:55:58.116498    7322 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 18:55:58.119811    7322 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 18:55:58.122889    7322 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
NAME                         STATUS   ROLES           AGE    VERSION
m1   Ready    control-plane   2d5h   v1.26.9
m2   Ready    control-plane   2d5h   v1.26.9
m3   Ready    control-plane   2d5h   v1.26.9
w1   Ready    <none>          10h    v1.26.9
w2   Ready    <none>          2d5h   v1.26.9
w3   Ready    <none>          10h    v1.26.9
w4   Ready    <none>          10h    v1.26.9
w5   Ready    <none>          10h    v1.26.9
w6   Ready    <none>          10h    v1.26.9
```

I read this docs https://docs.tigera.io/calico/latest/operations/install-apiserver but everything seems fine:

```
$ kubectl get tigerastatus apiserver
E0921 19:08:08.748858    7422 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 19:08:08.753272    7422 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 19:08:08.757313    7422 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 19:08:08.761084    7422 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
NAME        AVAILABLE   PROGRESSING   DEGRADED   SINCE
apiserver   True        False         False      2d5h
```

```
$ kubectl get ippools
E0921 19:10:29.772179    7482 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 19:10:29.774557    7482 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 19:10:29.778619    7482 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
E0921 19:10:29.784097    7482 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request
NAME                  AGE
default-ipv4-ippool   2d6h
```

kubectl from a controlplane node works fine.

What can I do?
Thanks

**Comment by tomastigera** [comment] 2023-10-03 16:55
Closing this as a duplicate of https://github.com/projectcalico/calico/issues/7555

**Closed by tomastigera** 2023-10-03 16:55 UTC
Labels: kind/support
