### ISSUE TITLE
serviceLoopPrevention is not working in eBPF mode

### ISSUE THREAD

**Issue by dmitry-sinina** [projectcalico/calico#5039] opened 2021-10-28 18:34 UTC
serviceLoopPrevention is not working in eBPF mode. 

I am announcing **serviceClusterIPs** and **serviceLoadBalancerIPs** over BGP to upstream routers but Calico doesn't install blackhole routes for such ranges(looks like it is by design, because such routes explicitly filtered in **calico_kernel_programming** BIRD function). I found when eBPF is disabled there  is **cali-cidr-block** iptables chain to drop traffic to not allocated IP addresses/ports from **serviceClusterIPs**/**serviceLoadBalancerIPs**  ranges.

## Expected Behavior
If IP address from **serviceClusterIPs**/**serviceLoadBalancerIPs**  not allocated to Service, or traffic directed to port not used by service, packets should be droppped/rejected somewhere( by BPF filter or blackhole route)

## Current Behavior
Currently node routes such packets according to routing table( using default route) as result we have routing loop for traffic from external system to IPs from  **serviceClusterIPs** and **serviceLoadBalancerIPs** ranges:
```
$ ping 10.11.136.2
PING 10.11.136.2 (10.11.136.2) 56(84) bytes of data.
From 10.11.13.3 icmp_seq=1 Time to live exceeded
From 10.11.13.3 icmp_seq=2 Time to live exceeded
```

## Possible Solution
BFP rule or blackhole route should be installed to prevent such routing loop.

## Steps to Reproduce (for bugs)
1. Announce **serviceClusterIPs**/ **serviceLoadBalancerIPs** over BGP to external router
2. Ping IP address within such range from external system. There is no loop.
3. enable eBPF mode
4. Ping IP address within such range from external system. Routing loop present, you will see **Time to live exceeded**

## Your Environment

* Calico version   v3.20.2, commit dcb4b76a
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.22.2
* Operating System and version: Debian 11, kernel 5.10.70-1

4

## Your Environment

* Calico version   v3.20.2, commit dcb4b76a
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.22.2
* Operating System and version: Debian 11, kernel 5.10.70-1

**Comment by alloran** [comment] 2021-12-01 14:17
Can confirm this.

Also, tcp traceroute is broken for such externally announced services.

`traceroute -n -T -p 443 service_ip`

tcp syn packet from traceroute has ttl=1 as it reaches ebpf tc filter, and when it nated to pod on another node, ttl is reduced to 0 (maybe [here](https://github.com/projectcalico/felix/blob/master/bpf-gpl/nat.h#L98)), and the packet is lost.

**Comment by ehsan310** [comment] 2024-05-16 12:42
is there any plan to fix this issue ?

**Comment by ehsan310** [comment] 2024-05-16 22:57
I have tried to block all icmp incoming traffic but that didn’t helped

**Comment by tomastigera** [comment] 2024-05-16 23:35
Ohhh thanks for bringing this issue forward again, seems like it got lost. I will try to reproduce the issue. What creates the loop? Do you have some simple config, service etc. which would help us to repro the issue? So detailed description would help us a lot! Thank you!

**Comment by ehsan310** [comment] 2024-05-17 06:34
It's exactly same situation as described in the beginning.

I have ServiceIP advertised over bgp , node to node is disabled , and I have my cluster advertised to ToR router.

When traffic hit the service ip on a port that is not used in service then icmp packets or traceroute (since default check is icmp i guess) is failing with Time to live exceeded message.

It only happens when eBPF enabled since iptables rule that drop packets on service ip is missing.

**Comment by tomastigera** [comment] 2024-05-17 15:49
>  since iptables rule that drop packets on service ip is missing.

ok, I got it. So we should drop packets, but we do not, let me have a look! :+1:

**Comment by ehsan310** [comment] 2024-05-24 06:37
> @ehsan310 I am trying to reproduce the problem. I have a cluster announcing cluster IP ranges via BGP to an external router. My cluster CIDR is 10.96.0.0/12 and these are the routes that I see in the external router.
> 
> ```
> 10.96.0.0/12 via 172.16.101.8 dev ens5 proto bird 
> 172.16.101.0/24 dev ens5 proto kernel scope link src 172.16.101.138 
> 172.16.101.1 dev ens5 proto dhcp scope link src 172.16.101.9 metric 100 
> 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
> 192.168.165.128/26 via 172.16.101.8 dev ens5 proto bird 
> 192.168.209.0/26 via 172.16.101.132 dev ens5 proto bird 
> ```
> 
> As you can see, service CIDR is reachable via the cluster node `172.16.101.8`. Now I create a service and the cluster IP is `10.103.202.200`. I can reach this service from the external router. IIUC, the test is to do a traceroute to another IP within the CIDR, say 10.103.202.201. Am I right?

do you have service ip advertised via bgp as well ?
the problem only happens when service ip is advertised 

when you try to ping the service ip with a backing pod i would expect you get `Time to live exceeded`
same happens for traceroute as traceroute default behavior is to use ICMP to figure out the endpoint reachable or not.

**Comment by sridhartigera** [comment] 2024-05-24 13:20
I have the service-cluster-ip-range advertised over BGP. The expectation is to drop the packets if I try to reach an IP within the ```serviceClusterIPRange``` which doesn't have a backing pod. Right?

**Comment by ehsan310** [comment] 2024-05-24 13:23
it does have a backpod but only port 80 for example, 
with `externaltrafficpolicy: local` we run into a loop between the nodes hosting the pod and without we run into a loop on all the nodes.

**Comment by sridhartigera** [comment] 2024-05-24 13:28
My service IP is ```10.203.202.200``` and port 80. I did ```sudo traceroute -T -n -p 80 10.103.202.200``` and I see the below in tcpdump 
```
traceroute to 10.103.202.200 (10.103.202.200), 30 hops max, 60 byte packets22:54:57.212093 IP ip-172-16-101-8.us-west-2.compute.internal > ip-172-16-101-138.us-west-2.compute.internal: ICMP time exceeded in-transit, length 88
22:54:57.212093 IP ip-172-16-101-8.us-west-2.compute.internal > ip-172-16-101-138.us-west-2.compute.internal: ICMP time exceeded in-transit, length 88
22:54:57.212093 IP ip-172-16-101-8.us-west-2.compute.internal > ip-172-16-101-138.us-west-2.compute.internal: ICMP time exceeded in-transit, length 88

 1  172.16.101.8  0.696 ms  0.652 ms  0.638 ms
 2  * * *
 3  10.103.202.200  2.419 ms  2.277 ms  2.395 ms
````

**Comment by ehsan310** [comment] 2024-05-25 07:58
> My service IP is `10.203.202.200` and port 80. I did `sudo traceroute -T -n -p 80 10.103.202.200` and this is what I see in tcpdump
> 
> ```
> traceroute to 10.103.202.200 (10.103.202.200), 30 hops max, 60 byte packets22:54:57.212093 IP ip-172-16-101-8.us-west-2.compute.internal > ip-172-16-101-138.us-west-2.compute.internal: ICMP time exceeded in-transit, length 88
> 22:54:57.212093 IP ip-172-16-101-8.us-west-2.compute.internal > ip-172-16-101-138.us-west-2.compute.internal: ICMP time exceeded in-transit, length 88
> 22:54:57.212093 IP ip-172-16-101-8.us-west-2.compute.internal > ip-172-16-101-138.us-west-2.compute.internal: ICMP time exceeded in-transit, length 88
> 
>  1  172.16.101.8  0.696 ms  0.652 ms  0.638 ms
>  2  * * *
>  3  10.103.202.200  2.419 ms  2.277 ms  2.395 ms
> ```
> 
> I should just do a traceroute to a different port.

you can see TTL exceeded in your log,

also i am not sure how many nodes do you have if more than 1 you also get into a loop between them.

so using traceroute on a non default port is not usual thing , i just mentioned to tell you what is the problem.

**Comment by sridhartigera** [comment] 2024-06-08 01:36
Fixed by https://github.com/projectcalico/calico/pull/8876

**Closed** 2024-06-08 01:36 UTC
Labels: kind/bug, likelihood/low, impact/high, area/bpf

**Comment by ehsan310** [comment] 2024-06-08 17:42
Nice work @sridhartigera
