### ISSUE TITLE
Ability to syntax check network policies using calicoctl dry-run 

### ISSUE THREAD

**Issue by hahasheminejad** [projectcalico/calico#3463] opened 2020-04-19 14:15 UTC
## Expected Behavior

Just wondering if there is a `--dry-run` option or anything similar for networkpolicy and globalnetworkpolicy kinds to check the validity of policies before applying.

The idea is to have a step in our pipeline for each PR to check the syntax/validity of rules before applying to the cluster.
## Possible Solution

Having `--dry-run` option.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment] 2020-05-11 20:23
What do you mean by checking the validity of a network policy? If you mean syntactically correct then that is probably possible but if you mean more like check if it will block or allow what you want I think would be next to impossible to tell based on a single policy by itself.

**Comment by caseydavenport** [comment] 2020-05-12 22:05
Going to close as a duplicate of https://github.com/projectcalico/calicoctl/issues/2117

**Closed by caseydavenport** 2020-05-12 22:05 UTC
Labels: help wanted, kind/enhancement
