### ISSUE TITLE
BGP not configured but running

### ISSUE THREAD

**Issue by telekomancer** [projectcalico/calico#4333] opened 2021-01-22 11:33 UTC
I installed calico according to the documentation but i guess that BGP shouldn't be running.

## Expected Behavior

If i see the logs, i see some bgp activity and try to peer with other devices

Review bgp configuration during install

## Current Behavior

If i see the logs, i see this:

```code
I0119 12:42:42.455673   19086 prober.go:112] Readiness probe for "calico-node-rszfd_kube-system(5cf624de-523b-43cd-8557-d2bbe6458f3e):calico-node" failed (failure): calico/node is not ready: BIRD is not ready: BGP not established with 192.168.31.62021-01-19 12:42:42.412 [INFO][1303] health.go 156: Number of node(s) with BGP peering established = 0

```

## Possible Solution

- No bgp activity

- First, don't start BGP and second, fix the log line.

**... BGP not established with 192.168.31.62021-01-19 ...**

## Steps to Reproduce (for bugs)

1. Just install kubernetes, rancher and use as CNI, Calico
2. You'll see in logs, bgp activities

## Context

- Not affected by this issue
- Try to improve logs and communication/services

## Your Environment

* Calico version: Calico-node/calicoctl version: container{Container{Name:calico-kube-controllers,Image:rancher/calico-kube-controllers:v3.13.4
* Orchestrator version (e.g. kubernetes, rkt, swarm, mesos): Kubernetes
* Operating System and version:

```code
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

This issue was originally opened at calico-bgp-daemon project: link of previous issue: https://github.com/projectcalico/calico-bgp-daemon/issues/51

**Comment by lwr20** [comment] 2021-01-26 17:17
Exactly how did you install Calico?  i.e. which URL did you follow?  Some installation methods need BGP to be working.

This error often occurs when the host that its running on has >1 network interface and calico has picked the wrong one to use.  That can be fixed by setting the IP_AUTODETECTION_METHOD - see https://docs.projectcalico.org/reference/node/configuration#ip-autodetection-methods

**Comment by telekomancer** [comment] 2021-01-26 17:46
Thanks for your reply @lwr20, i installed using kubectl:

```
kubectl apply -f https://docs.projectcalico.org/manifests/flannel-migration/migration-job.yaml
```

![Following this documentation](https://docs.projectcalico.org/getting-started/kubernetes/flannel/migration-from-flannel)

**Comment by caseydavenport** [comment] 2021-02-09 00:17
Do you see that log line about BGP peers repeatedly? Or is it a transient thing? 

Are your cross-host pod to pod connections actually working? 

The manifests in the document that you linked already disable BGP by deafult, as evidenced by the readiness probe, which would have a `--bird-ready` if BGP was being checked:

```
          readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-ready
```

As well as the networking backend, which would be "bird" if BGP was in use:

```
  # Configure the backend to use.
  calico_backend: "vxlan"
```

So, given that, I'm actually suprised you're seeing the above warning at all, since the readiness check shouldn't be checking BIRD status. Can you confirm that the DaemonSet on your cluster has config that matches the above?

**Comment by telekomancer** [comment] 2021-02-09 13:17
Thanks for your reply @caseydavenport, nowadays i only see this:

```code
kubectl logs -n kube-system calico-node-rszfd | grep -i BIRD
bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
2021-01-26 13:16:26.718 [INFO][48] resource.go 220: Target config /etc/calico/confd/config/bird6_ipam.cfg out of sync
2021-01-26 13:16:26.719 [INFO][48] resource.go 220: Target config /etc/calico/confd/config/bird6_aggr.cfg out of sync
2021-01-26 13:16:26.724 [INFO][48] resource.go 220: Target config /etc/calico/confd/config/bird_ipam.cfg out of sync
2021-01-26 13:16:26.725 [INFO][48] resource.go 220: Target config /etc/calico/confd/config/bird6.cfg out of sync
2021-01-26 13:16:26.725 [INFO][48] resource.go 220: Target config /etc/calico/confd/config/bird.cfg out of sync
2021-01-26 13:16:26.726 [INFO][48] resource.go 220: Target config /etc/calico/confd/config/bird_aggr.cfg out of sync
2021-01-26 13:16:26.945 [INFO][48] resource.go 260: Target config /etc/calico/confd/config/bird.cfg has been updated
2021-01-26 13:16:26.949 [INFO][48] resource.go 260: Target config /etc/calico/confd/config/bird_ipam.cfg has been updated
2021-01-26 13:16:26.950 [INFO][48] resource.go 260: Target config /etc/calico/confd/config/bird6_aggr.cfg has been updated
2021-01-26 13:16:26.951 [INFO][48] resource.go 260: Target config /etc/calico/confd/config/bird_aggr.cfg has been updated
2021-01-26 13:16:26.954 [INFO][48] resource.go 260: Target config /etc/calico/confd/config/bird6.cfg has been updated
2021-01-26 13:16:26.956 [INFO][48] resource.go 260: Target config /etc/calico/confd/config/bird6_ipam.cfg has been updated
bird: device1: Initializing
bird: direct1: Initializing
bird: device1: Starting
bird: device1: Connected to table master
bird: device1: State changed to feed
bird: direct1: Starting
bird: direct1: Connected to table master
bird: direct1: State changed to feed
bird: Graceful restart started
bird: Graceful restart done
bird: Started
bird: device1: State changed to up
bird: direct1: State changed to up
bird: device1: Initializing
bird: direct1: Initializing
bird: Mesh_192_168_31_99: Initializing
bird: Mesh_192_168_31_6: Initializing
bird: device1: Starting
bird: device1: Connected to table master
bird: device1: State changed to feed
bird: direct1: Starting
bird: direct1: Connected to table master
bird: direct1: State changed to feed
bird: Mesh_192_168_31_99: Starting
bird: Mesh_192_168_31_99: State changed to start
bird: Mesh_192_168_31_6: Starting
bird: Mesh_192_168_31_6: State changed to start
bird: Graceful restart started
bird: Started
bird: device1: State changed to up
bird: direct1: State changed to up
bird: Mesh_192_168_31_6: Connected to table master
bird: Mesh_192_168_31_6: State changed to wait
bird: Mesh_192_168_31_99: Connected to table master
bird: Mesh_192_168_31_99: State changed to wait
bird: Next hop address 10.42.3.0 resolvable through recursive route for 10.42.3.0/24
bird: Next hop address 10.42.0.0 resolvable through recursive route for 10.42.0.0/24
bird: Next hop address 10.42.1.0 resolvable through recursive route for 10.42.1.0/24
bird: Graceful restart done
bird: Mesh_192_168_31_99: State changed to feed
bird: Mesh_192_168_31_6: State changed to feed
bird: Next hop address 10.42.3.0 resolvable through recursive route for 10.42.3.0/24
bird: Next hop address 10.42.0.0 resolvable through recursive route for 10.42.0.0/24
bird: Next hop address 10.42.1.0 resolvable through recursive route for 10.42.1.0/24
bird: Mesh_192_168_31_99: State changed to up
bird: Mesh_192_168_31_6: State changed to up
bird: KIF: Received address message for unknown interface 189
bird: KIF: Received address message for unknown interface 193
```

Related to BIRD ... related to BGP (as BGP and not bgp) i don't have logs (TBH i don't use the cluster in this last 2 weeks) there are some things, related to BIRD that i cannot give you more information 'cause i don't know "when" the things happen, as you see from the previous output. BUT i can tell you that even i haven't log, BGP is UP and RUNNING:

![imagen](https://user-images.githubusercontent.com/27900350/107368422-4c84c700-6abf-11eb-8d99-5f593364e76d.png)

So i guess that the behaviour can be replicated (the log output). Are you have more information:

```code
sh-4.4# netstat -pontelu | grep 179
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      0          32864741   130/bird             off (0.00/0/0)
```

```code
sh-4.4# ps aux | grep 130
root       130  0.0  0.0    844   412 ?        S    Jan26   3:04 bird -R -s /var/run/calico/bird.ctl -d -c /etc/calico/confd/config/bird.cfg
root     21694  0.0  0.0   9168   704 pts/1    S+   13:16   0:00 grep 130
```

```code
sh-4.4# cat /etc/calico/confd/config/bird.cfg | grep -v '#' | grep -v '^$'
include "bird_aggr.cfg";
include "bird_ipam.cfg";
router id 192.168.31.203;
protocol kernel {
  import all;
}
protocol device {
  debug { states };
}
protocol direct {
  debug { states };
}
template bgp bgp_template {
  debug { states };
  description "Connection to BGP peer";
  local as 64512;
  multihop;
  add paths on;
  connect delay time 2;
  connect retry time 5;
  error wait time 5,30;
}
protocol bgp Mesh_192_168_31_99 from bgp_template {
  neighbor 192.168.31.99 as 64512;
}
protocol bgp Mesh_192_168_31_6 from bgp_template {
  neighbor 192.168.31.6 as 64512;
}
sh-4.4# 
```

**Comment by caseydavenport** [comment] 2021-02-09 19:47
I am afraid I still don't understand what the problem is here, if any.

>  Can you confirm that the DaemonSet on your cluster has config that matches the above?

The fact that BGP is running is only a problem if your DaemonSet is configured to disable BGP. If the DS has BGP enabled, then it is expected. Could you please share the DaemonSet that is running on your cluster so we can confirm that BGP is actually disabled?

**Comment by telekomancer** [comment] 2021-02-09 20:18
The only DaemonSet that i have is "calico-node" which content is (on topic):

```code
        name: calico-node
        readinessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-ready
            - -bird-ready
```
I guess that is necessary to say that i just migrate from flannel to calico with the ![manifest copied before](https://github.com/projectcalico/calico/issues/4333#issuecomment-767712717)

So i didn't "tuned in" the services or make something different from the comment that i pasted again.

**Comment by lmm** [comment] 2021-02-25 17:52
@telekomancer from that snippet of your calico-node daemonset, bird is enabled since with `-bird-ready` flag indicates that calico-node won't get to a ready state unless bird is also running.

If you started with a Flannel cluster, and ran our Flannel migration tool, we bring up a VXLAN cluster I believe. I wonder if we disable BGP as part of the migration - @song-jiang would you happen to know?

**Comment by song-jiang** [comment] 2021-03-23 16:42
I downloaded latest `calico.yaml` from Calico doc. 
`curl -LO https://docs.projectcalico.org/manifests/flannel-migration/calico.yaml` There is no `-bird-ready` flag on calico-node daemonset.
```
         livenessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-live
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-ready
```

**Comment by lmm** [comment] 2021-04-06 16:38
I'm closing this for now since I think we've identified the issue here - please reopen if you have any questions or open a new issue if you're still having problems, thanks!

**Closed by lmm** 2021-04-06 16:38 UTC
