### ISSUE TITLE
Calico in BGP-mode and IPIP-tunnel with an external BGP-agent on linux

### ISSUE THREAD

**Issue by marco-a-itl** [projectcalico/calico#4647] opened 2021-06-01 12:42 UTC
This is not a bug report, but more of a support-request related to a very specific deployment.
Consider the following use case:
* Deploy in a public cloud (i.e. AWS) with kubernetes cluster nodes in multiple subnets (multi-AZ)
* Pods running inside kubernetes cluster (specifically EKS), and one VM running outside of the cluster
* Pods needs to be routable outside of the cluster so that the VM can contact the Pods "directly" without NAT involved, similarly to when the cloud-provider CNI plugin (AWS VPC CNI plugin) is used
* Calico CNI plugin provides unique features (like "floating IP to a pod" and "specific IP address for a pod") that are missing when cloud-provider CNI plugin is used
* KubeVirt is not an option

The possible solution seemed:

* Use Calico in BGP mode
* Deploy, inside the external VM, a BGP agent (i.e. BIRD) configured as a Global-BGP-Peer in Calico, so that the external VM gets the routes to reach the Pods
* Enable IPIP tunneling on Calico, because some kubernetes nodes are in different subnets, and cloud-provider network is not aware of BGP
* Fork of BIRD by Calico (projectcalico/bird) seems necessary, because of support for IPIP tunneling

However:

* Did not find much documentation/examples of a similar solution, in particular regarding use of Calico-BIRD as a standalone agent on an external linux machine. Is this a viable solution or there are better choices ?
* After having tried to configure Calico-BIRD on the external VM (by looking at how it is configured when run inside pod/calico-node), the IPIP tunneled packets coming from the external-VM to a kubernetes-node are dropped somewhere inside the network stack. Do kubernetes-nodes need additional configurations to receive IPIP packets from machines different from other cluster-nodes ?

So, first of all, I would need to understand if this strategy can be considered feasible, or I've just entered a dead end

**Comment by lwr20** [comment] 2021-06-01 16:30
This scenario is indeed possible.  Its documented in the "install on non-cluster hosts" doc. https://docs.projectcalico.org/getting-started/bare-metal/about

**Comment by marco-a-itl** [comment] 2021-06-03 10:26
Thank you. I'm trying to follow the guide.
The first problem that I see is that the Docker container calico/node is required to have network setup (in addtion to policy).
However calico/node image does not have aws-cli binary installed; use of aws-cli is triggered in my case by kubeconfig "user->exec" section.
Installing aws-cli in a new layer above calico/node is not easy, because a lot of libraries are missing.

**Comment by lwr20** [comment] 2021-06-03 10:31
I'm not sure I understand why you would need aws-cli on the node at all in this setup?

**Comment by marco-a-itl** [comment] 2021-06-03 10:42
The kubeconfig file passed to `calico/node` container via `KUBECONFIG` environment variable ends like this:
```
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - my-region
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      command: aws
```
So `aws` binary gets called...

**Comment by marco-a-itl** [comment] 2021-06-03 17:02
Not sure if it is the best way, but I rebuilt `calico/node` modifying its Dockerfile to add the aws-cli binary.
Now `calico/node` starts, but when I launch it as stated in the docs:
```
/usr/bin/docker run --net=host --privileged \
...
calico/node:v3.19.1 /bin/calico-node -felix
```
only felix is run (BIRD, confd, etc. are not started).
If the container is launched without arguments like:
```
/usr/bin/docker run --net=host --privileged \
...
calico/node:v3.19.1
```
I get instead this error, that I have seen in other issues like #3551:
```
2021-06-03 16:44:01.554 [ERROR][10] startup/startup.go 204: Unable to set node resource configuration error=operation Create is not supported on Node
```

**Comment by lwr20** [comment] 2021-06-03 17:25
Hmm.  @caseydavenport - any ideas?

**Comment by marco-a-itl** [comment] 2021-06-07 09:53
Actually I'm on a public cloud (AWS).
I'm not aware of any way to access the etcd inside the control-plane (EKS is a managed service).
I also tried to manually create a node resource via `calicoctl`, but I get:
` ` `
Failed to create 'Node' resource: [operation Create is not supported on Node
` ` `

**Comment by caseydavenport** [comment] 2021-09-21 16:49
Yeah, this is a known gap. We need to enhance Calico to support this. This is a duplicate of https://github.com/projectcalico/calico/issues/3407

**Closed by caseydavenport** 2021-09-21 16:49 UTC
Labels: kind/support
