### ISSUE TITLE
Kubernetes Webhooks not working in vxlan mode

### ISSUE THREAD

**Issue by ragunathan23** [projectcalico/calico#3818] opened 2020-07-22 05:20 UTC
Kubernetes Webhooks not working in vxlan mode
## Expected Behavior

After enabling backend to vxlan, the kubernetes webhooks should work without any issue.
## Current Behavior

Webhooks are failing with following error:
Failed calling webhook, failing open validation.istio.io: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded

## Steps to Reproduce (for bugs)

1. Install kubernetes cluster with calico vxlan mode as backend
2. Install Istio 1.5.2 and enable sidecar injection for the namespace
3. Create the pod in the desired namespace
4. Pod is not created due to webhook failure

## Your Environment

* Calico version - v3.15.1
* Orchestrator version (e.g. kubernetes, Mesos, rkt): Kubernetes 1.18.1
* Operating System and version: Centos 7 VM, on-premise
* Link to your project (optional):

**NOTE:
The webhooks works perfectly fine when backend is enabled in ipipmode.**

**Comment by caseydavenport** [comment] 2020-08-06 19:10
@ragunathan23 this is likely due to an issue with the control plane nodes being unable to create outgoing connections to pods. How is your network configured? Does it allow VXLAN encap'd packets in its firewall? 

On a cluster with VXLAN enabled, do you see routes to pod IP addresses on the control plane nodes? Is Calico running on those nodes? 

e.g., `ip route show` on a node with the apiserver running. 

I think we need to figure out where in the network the traffic is being dropped:
- At the origin node
- Somewhere in the network
- At the destination node
- On the return traffic.

if we can pinpoint that, then we'll be able to identify if this is a bug or a misconfiguration in some way.

**Comment by gnz00** [comment] 2020-08-20 02:35
I've encountered this issue on EKS for both ipipMode and vxlanMode.

```
# https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks
eksctl create cluster --name my-calico-cluster --without-nodegroup
kubectl delete daemonset -n kube-system aws-node
kubectl apply -f https://docs.projectcalico.org/manifests/calico-vxlan.yaml
eksctl create nodegroup --cluster my-calico-cluster --node-type t3.medium --node-ami auto --max-pods-per-node 100
```
```
# https://docs.projectcalico.org/getting-started/kubernetes/hardway/istio-integration
istioctl install --set profile=minimal
kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/alp/istio-inject-configmap-1.1.7.yaml
```

Any subsequent deployments tagged for istio injection fail with the OP issue. Unfortunately, can't justify adding `hostNetwork:true` to every single pod (might be missing the point of that).

**Comment by caseydavenport** [comment] 2020-08-20 17:12
> I've encountered this issue on EKS for both ipipMode and vxlanMode.

Yeah, on EKS this is currently a known limitation if you're using Calico networking rather than the Amazon VPC CNI plugin.

The original issue reported is not on EKS though, so I assume is a slightly different root cause.

**Comment by Zhiw** [comment] 2020-09-17 09:11
> I've encountered this issue on EKS for both ipipMode and vxlanMode.
> 
> ```
> # https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks
> eksctl create cluster --name my-calico-cluster --without-nodegroup
> kubectl delete daemonset -n kube-system aws-node
> kubectl apply -f https://docs.projectcalico.org/manifests/calico-vxlan.yaml
> eksctl create nodegroup --cluster my-calico-cluster --node-type t3.medium --node-ami auto --max-pods-per-node 100
> ```
> 
> ```
> # https://docs.projectcalico.org/getting-started/kubernetes/hardway/istio-integration
> istioctl install --set profile=minimal
> kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/alp/istio-inject-configmap-1.1.7.yaml
> ```
> 
> Any subsequent deployments tagged for istio injection fail with the OP issue. Unfortunately, can't justify adding `hostNetwork:true` to every single pod (might be missing the point of that).

I‘ve encountered the same issue as you:fearful:. If it can't be solved, I have to give up on Calico.

**Comment by ragunathan23** [comment] 2020-09-24 08:40
> @ragunathan23 this is likely due to an issue with the control plane nodes being unable to create outgoing connections to pods. How is your network configured? Does it allow VXLAN encap'd packets in its firewall?
> 
> On a cluster with VXLAN enabled, do you see routes to pod IP addresses on the control plane nodes? Is Calico running on those nodes?

**Yes calico is running on all the nodes**

> 
> e.g., `ip route show` on a node with the apiserver running.
> 
> I think we need to figure out where in the network the traffic is being dropped:

**How do we do that?**

> 
> * At the origin node
> * Somewhere in the network
> * At the destination node
> * On the return traffic.
> 
> if we can pinpoint that, then we'll be able to identify if this is a bug or a misconfiguration in some way.

**Comment by fasaxc** [comment] 2020-09-29 12:28
@ragunathan23 what MTU settings are you using for Calico, that's a good first thing to check? VXLAN has a lower MTU than IPIP and you need to restart pods to pick up new MTU.
 
Are your control plane nodes in a different subnet from your worker nodes? 

Do you have any network policy in place?

**Comment by ragunathan23** [comment] 2020-09-29 12:39
> @ragunathan23 what MTU settings are you using for Calico, that's a good first thing to check? VXLAN has a lower MTU than IPIP and you need to restart pods to pick up new MTU.

**It's default MTU we have not changed or configured any new MTU value.**

> 
> Are your control plane nodes in a different subnet from your worker nodes?

**No, they are in the same subnet** 

> Do you have any network policy in place?

**No, there is no network policy in place.**

@fasaxc please find the response inline.

**Comment by fasaxc** [comment] 2020-09-29 12:52
Please share your calico-config config map and your IP pool in YAML format `calicoctl get ippool -o yaml` should do the trick.

Are your control plane nodes configured to use the kubernetes DNS service?  Is kube-proxy running?

**Comment by fasaxc** [comment] 2020-09-29 13:01
Since you're on Centos, worth checking that you don't have firewalld, networkd, or one of the other ----d's adding iptables rules that block traffic.

I find this command useful for spotting when an iptables rule drops traffic:
```
sudo watch "iptables-save -c | grep DROP | grep -v 0:0"
```
After running that, try doing a DNS lookup and it will tell you which rule (if any) dropped the packet.

**Comment by mgleung** [comment] 2020-12-10 17:45
Closing due to lack of recent activity. If this problem still persists, please reopen.

**Comment by Mnbill** [comment] 2020-12-14 18:13
Hello,

I have the same problem on my on-premise cluster but with validate.nginx.ingress.kubernetes.io webhooks


**Context
Your Environment**

K8s version 1.18.3
Calico v3.17.0
vxlan mode
Openstack cloud.
MTU 1400 (but i tried also 1410 and 1450)

**Comment by yiyan-wish** [comment] 2021-02-02 15:01
Same problem EKS with calico cni plugin

**Comment by gautam2187** [comment] 2021-04-29 05:00
@yiyan-wish @Mnbill @ragunathan23 Did you guys figure out a solution to make it work. Thanks!

**Comment by gautam2187** [comment] 2021-05-04 16:57
So I found the problem in my case. It was the srcdst pod which had the bad cert mount path due to the recent change in kops 
https://github.com/kubernetes/kops/pull/10169/files. It worked fine after fixing the cert path, so calico was not causing it. @mgleung

**Comment by lwr20** [comment] 2021-05-20 16:09
> Same problem EKS with calico cni plugin

@yiyan-wish on EKS this is expected.  See https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks

>Note: Calico networking cannot currently be installed on the EKS control plane nodes. As a result the control plane nodes will not be able to initiate network connections to Calico pods. (This is a general limitation of EKS’s custom networking support, not specific to Calico.) As a workaround, trusted pods that require control plane nodes to connect to them, such as those implementing admission controller webhooks, can include hostNetwork:true in their pod spec. See the Kuberentes API pod spec definition for more information on this setting.

**Comment by mgleung** [comment] 2021-06-07 23:29
@Mnbill are you still seeing this issue in your cluster? Mind sharing any of the debug info that @fasaxc has mentioned above if you are?

**Closed** 2021-06-29 17:31 UTC
Labels: kind/support
