### ISSUE TITLE
tigera-operator blocks deployment if one node cannot run calico-node

### ISSUE THREAD

**Issue by christian-schlichtherle** [projectcalico/calico#9540] opened 2024-11-28 12:36 UTC
I was following the instructions for multi-node K3s from your [documentation](https://docs.tigera.io/calico/latest/getting-started/kubernetes/k3s/multi-node-install) and installed the tigera-operator resource manifests for version 3.29.1 and then deployed my custom resource manifests of kind=Installation and kind=APIServer.

In my test setup, there is an edge node which fails the readiness probe for it's calico-node container because it can't use ipset for some reason:

```
2024-11-28 12:21:04.487 [ERROR][147075] felix/ipsets.go 671: Bad return code from 'ipset list -name'. error=exit status 1 family="inet" stderr="ipset v7.11: Kernel error received: Invalid argument\n"                                                                  │
2024-11-28 12:21:04.487 [ERROR][147075] felix/ipsets.go 409: Failed to get the list of ipsets error=exit status 1 family="inet"
```

In turn, this triggers the tigera-operator being blocked with the deployment because it waits for ALL daemonset pods to report ready state. In result, calico is not rolled out and it looks like the CNI on the cluster is completely broken.

## Expected Behavior

From my point of view this is a bug: In a distributed system, there's always a chance that a node is not working for some reason. In our case, the node in question is an IoT device where we have only limited control over the Linux Kernel (because it's part of a Linux distribution provided by the hardware vendor). The tigera-operator should tolerate the outage of nodes to some extent and just continue with the deployment.

In my case, I had to delete the edge node from the cluster to see the tigera-operator advancing with the rollout for the cloud nodes and then add the edge node back later.

## Your Environment

* Calico version: 3.29.1
* Calico dataplane: iptables

```
$ kubectl get nodes -o wide
[...]
cloud-node-123  Ready    <none>  9d    v1.31.2+k3s1   172.18.0.16   1.2.3.4  Debian GNU/Linux 12 (bookworm)   6.1.0-28-arm64   containerd://1.7.22-k3s1
edge-node-123   Ready    <none>  89m   v1.31.2+k3s1   100.65.0.13   <none>   Ubuntu 24.04.1 LTS               5.15.137         containerd://1.7.22-k3s1
```

**Comment by caseydavenport** [comment] 2024-12-03 00:03
The tigera/operator Installation API provides a mechanism within the `CalicoNodeDaemonset` sub-section to configure things like affinity, node selection, and tolerations which I believe enables the necessary nobs to tell the operator which nodes calico/node should run on. This is the API spec here for that: https://github.com/tigera/operator/blob/master/api/v1/calico_node_types.go#L68-L88

I think it's totally valid for the operator to fail if it's unable to properly roll out the configuration it has been given (by default it expects all nodes to be valid targets for Calico). Using the nodeSelector / affinity sections you should be able to keep that node in your cluster and also configure calico/node not to run there.

**Comment by caseydavenport** [comment] 2024-12-03 00:04
> In result, calico is not rolled out and it looks like the CNI on the cluster is completely broken

This part is surprising though - I would not expect a single failing node to break actual network connectivity. The only thing I can imagine is that it would prevent rolling out the API server on Initial install, which I think is OK - it signals that configuration changes should be made in order to install Calico on this cluster.

**Comment by caseydavenport** [comment] 2024-12-03 19:58
> I've abandoned it and went on with Cilium.

That's fine, but I want to make some things clear for future readers since I think this issue is mis-characterizing Calico's behavior here.

There are two parts to this:

- Will the software silently run even when there are unmet requirements in the cluster?
- Will other nodes continue to function even if one node is broken.

Calico will continue to function even if there are broken nodes in the cluster. A single node won't break other nodes network configuration nor will it break network policy enforcement. This is by design and obviously an important part of a software like this.

But Calico won't silently ignore problematic nodes. If you try to install on a cluster with a handful of nodes that don't meet Calico's requirements, that installation will fail. And as mentioned in my previous comment, the Installation API provides the knobs necessary to exclude those problematic nodes from your installation. But it would be a huge problem if users thought that everything was functioning correctly but in fact their network policy was being bypassed, for example.

> rolling out changes (installation, upgrades etc) should not be blocked just because a single node is broken

Kubernetes disagrees. Rolling updates are fundamentally a mechanism to prevent rolling out a broken configuration - if you start an upgrade to your software and the first replica fails, you generally want to hold upgrading the remaining replicas until you can diagnose and address the problem in order to ensure service availability. 

I'm going to close this for now since I don't think there is any problem here to be addressed. Appreciate you taking the time to raise this!

**Closed** 2024-12-03 19:59 UTC
Labels: kind/support
