### ISSUE TITLE
After some time calico-node needs to be restarted in order to accept new BGP peers

### ISSUE THREAD

**Issue by r7vme** [projectcalico/calico#1420] opened 2017-11-29 18:08 UTC
We use calico 2.6.1 with BGP and IPIP tunnels. We frequently experiencing situation, if master node recreated with new ip address (etcd data stays the same on persistent volume), existing workers will reject new BGP peer.

EDIT: calico-node can stuck w/o master node recreation. Usually this happens if cluster older than few days. And can only be detected if new node was added.

I was creating issue before https://github.com/projectcalico/calico/issues/1031 , but one was mix of two issues actually (One is fixed [here](https://github.com/projectcalico/calico/issues/1357), second one is this bug). 

```
IPv4 BGP status
+--------------+-------------------+-------+----------+--------------------------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+--------------+-------------------+-------+----------+--------------------------------+
| 172.23.5.254 | node-to-node mesh | start | 16:46:08 | Active Socket: Connection      |
|              |                   |       |          | reset by peer                  |
| 172.23.5.62  | node-to-node mesh | start | 16:46:08 | Active Socket: Connection      |
|              |                   |       |          | reset by peer                  |
| 172.23.5.226 | node-to-node mesh | start | 16:46:08 | Connect Socket: Connection     |
|              |                   |       |          | reset by peer                  |
| 172.23.5.230 | node-to-node mesh | wait  | 16:46:12 | Established                    |
+--------------+-------------------+-------+----------+--------------------------------+
```

## Expected Behavior
New node able to join BGP

## Current Behavior
New node rejected as unknown by existing BGP peers

## Possible Solution
As workaround we are restarting all calico-node pods.

## Steps to Reproduce (for bugs)

No better way to reproduce unfortunately.
1. Recreate master node (etcd, k8s-api, calico-node, other master k8s services) with new ip address and hostname
2. Check BGP peers for new node

## Context
[Logs](https://gist.github.com/r7vme/0717de0f3f76500d20446a5637b92d69) from old calico-node does not contain anything suspicious.

## Your Environment
* Calico version 2.6.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.8.1
* Operating System and version: CoreOS 1409.7.0
* Link to your project (optional): Master vm [template](https://github.com/giantswarm/k8scloudconfig/blob/master/v_0_1_0/master_template.go)

**Comment by caseydavenport** [comment] 2017-11-29 18:17
@r7vme could you share logs from the calico/node instance on the new master node? It might give some insight as to why it's not happy with its config.

**Comment by r7vme** [comment] 2017-11-30 09:21
From other cluster with the same issue.

I have this situation in new master.
```
r7vme@master-w3p6j-3696049930-sqgh9 ~ $ sudo ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+--------------------------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+--------------+-------------------+-------+----------+--------------------------------+
| 172.23.2.42  | node-to-node mesh | wait  | 09:14:16 | Established                    |
| 172.23.2.170 | node-to-node mesh | start | 09:14:15 | Active Socket: Connection      |
|              |                   |       |          | refused                        |
| 172.23.2.70  | node-to-node mesh | wait  | 09:14:18 | Established                    |
+--------------+-------------------+-------+----------+--------------------------------+
```

And here is the [calico-node logs](https://gist.github.com/r7vme/aa0ac07fcc340886529f1f359b82c492) from new master.

**Comment by caseydavenport** [comment] 2017-12-04 06:57
@r7vme what does the output of `calicoctl get nodes` show?  Is there an entry for the new master present in the output? Wondering if the data isn't being written to etcd properly.

It would be useful as well to see debug logs from one of the old nodes to see if it's being told about the new peer. In the logs provided I see BIRD try to connect to the listed peers. Would be useful to see say logs from node `172.23.2.170` to see if it also sees the same peers.

**Comment by r7vme** [comment] 2017-12-04 14:05
@caseydavenport I don't have fresh logs as cluster already gone. Anyway please see my comments

> output of `calicoctl get nodes` show?

old master removed by https://github.com/giantswarm/calico-node-controller (forked from your project), as soon as new master started. We bind this service to master node and run in host network mode, so no dependency on Calico.

> Would be useful to see say logs from node 172.23.2.170 to see if it also sees the same peers.

I remember, when i checked other cluster with the same issue, BIRD config did not have new peer. That's why it has rejected BGP TCP connection.

Do i understand correct that confd takes configuration from etcd and applies to filesystem? Did you see issues with confd <> etcd connection reconciliation? We had this problem regularly on AWS installations, where AWS ELB idle timeout was set to 1 minute, after we switched to 1 hour issue completely gone.

**Comment by tmjd** [comment] 2017-12-04 17:16
You understand correctly that confd takes configuration from etcd and applies to the filesystem (specifically writing BIRD configuration and then reloading BIRD).  I'm not aware of confd <> etcd connection issues.

**Comment by r7vme** [comment] 2017-12-06 22:02
I was debugging other issue that happens when master recreated and found smth interesting. Inside pod (app that calls k8s api) i see that tcp connection in ESTABLISHED state for a while (17min in last test) to dead master. Pod connecting to k8s api via regular kubernetes service (e.g. 172.31.x.x) w/o external loadbalancer. I think this also can be related to current issue as confd uses long-living etcd connections probably, like k8s client does.

We observing same behaviour with external load balancer (Haproxy and F5 BIG IP) and with kubernetes iptables-based load balancer.

Here is [kubernetes issue](https://github.com/kubernetes/kubernetes/issues/46753) that describes such use case.

For Haproxy i found solution that solves issue with k8s api (i can not check quickly calico-node as it's not 100% reprodusable for new clusters)
```
    timeout client          30s
    timeout client-fin      30s
    timeout tunnel          1h
    timeout server          30s
```
In this case haproxy will drop dead connection after 30 second and will work fine for long-living ones (like `kubectl exec` or `kubectl logs`). This helps to detect dead TCP connections.

So now i'm not so confident that issue in Calico. But may be you have ideas how this can be mitigated? tcp keepalives are inefficient in that case.

**Comment by r7vme** [comment] 2017-12-06 22:03
When we hit Calico issue next time, i'll try to check for dead tcp connections inside pod.

**Comment by r7vme** [comment] 2017-12-15 09:30
We hit similar issue on one of AWS clusters. Cluster was scaled +1 node, but existing nodes did not update BGP peers list.

Here are calico-node logs from node that did not get new node (etcd located on the same node and master was NOT restarted).

https://gist.github.com/r7vme/3741c006f485122169e636e478d22cbb

**Comment by r7vme** [comment] 2017-12-15 10:24
Second cluster that experience the same problem on AWS. In this case all worker vms were recreated, master is old one and did not get info about new workers (still expects to see old ones.)

From (stalled) master:
```
ip-10-0-5-126 r7vme # ./calicoctl get node
NAME                                          
ip-10-0-5-11.eu-central-1.compute.internal    
ip-10-0-5-126.eu-central-1.compute.internal   
ip-10-0-5-142.eu-central-1.compute.internal   
ip-10-0-5-223.eu-central-1.compute.internal   
ip-10-0-5-64.eu-central-1.compute.internal    

ip-10-0-5-126 r7vme # ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+------------+--------------------------------+
| PEER ADDRESS |     PEER TYPE     | STATE |   SINCE    |              INFO              |
+--------------+-------------------+-------+------------+--------------------------------+
| 10.0.5.203   | node-to-node mesh | start | 2017-12-14 | Connect Socket: Connection     |
|              |                   |       |            | refused                        |
| 10.0.5.57    | node-to-node mesh | start | 2017-12-14 | Active Socket: Host is         |
|              |                   |       |            | unreachable                    |
| 10.0.5.84    | node-to-node mesh | start | 2017-12-14 | Active Socket: Host is         |
|              |                   |       |            | unreachable                    |
| 10.0.5.178   | node-to-node mesh | start | 2017-12-14 | Connect Socket: Connection     |
|              |                   |       |            | refused                        |
+--------------+-------------------+-------+------------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.

```

From new (healthy) worker:
```
ip-10-0-5-11 r7vme # ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+------------+--------------------------------+
| PEER ADDRESS |     PEER TYPE     | STATE |   SINCE    |              INFO              |
+--------------+-------------------+-------+------------+--------------------------------+
| 10.0.5.126   | node-to-node mesh | start | 2017-12-14 | Active Socket: Connection      |
|              |                   |       |            | reset by peer                  |
| 10.0.5.142   | node-to-node mesh | up    | 2017-12-14 | Established                    |
| 10.0.5.223   | node-to-node mesh | up    | 2017-12-14 | Established                    |
| 10.0.5.64    | node-to-node mesh | up    | 2017-12-14 | Established                    |
+--------------+-------------------+-------+------------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.
```

This time full log from broken calico-node: https://gist.github.com/r7vme/9e331c8b17d2451df494bbac052f20c9

There are a lot of errors like this
```
2017-12-15T07:32:38Z ip-10-0-5-126.eu-central-1.compute.internal confd[90]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [19262/8373]) [20261]
```

**Comment by fasaxc** [comment] 2017-12-15 16:11
I believe that issue is fixed in Calico v2.6.3, which included `confd` `v0.12.1-calico-0.4.1`

**Comment by r7vme** [comment] 2017-12-15 16:49
Cool, let us check this

**Comment by zihaoyu** [comment] 2017-12-15 18:00
We saw the same symptom after rebuilding all master nodes. New masters could not join the cluster, showing:
```
Active Socket: Connection reset by peer 
```
On existing nodes we saw:
```
bird: BGP: Unexpected connect from unknown address 10.72.101.162 (port 53107)
```
The IP address in the message above is the new master.

**Comment by zihaoyu** [comment] 2017-12-15 18:17
@fasaxc Is this the commit that's supposed to fix it? https://github.com/projectcalico/confd/commit/a82f6eea9f9bfef0762d4c005f4b0a82de450c30

**Comment by fasaxc** [comment] 2017-12-15 18:42
@zihaoyu I think that one fixes this particular issue.

**Comment by zihaoyu** [comment] 2017-12-15 19:07
@fasaxc Thanks! We will give v2.6.3 a go soon!

**Comment by zihaoyu** [comment] 2017-12-18 15:17
@fasaxc @caseydavenport Just wanted to give an update. We were unable to reproduce the same issue on Calico v2.6.3. This version seems to have it fixed.

**Comment by r7vme** [comment] 2018-01-23 13:41
We don't see this issue after upgrading to 2.6.5. Thanks.

**Comment by fasaxc** [comment] 2018-01-23 15:17
OK, great, I'll close this issue.  Please open a new one if you see this again with v2.6.5+

**Closed by fasaxc** 2018-01-23 15:17 UTC
Labels: priority/P1
